-Sources:
-http://s0.2mdn.net/instream/video/client.js:
-Evaluate in console:
(function(){var k=this,l=function(a){return void 0!==a},aa=function(){},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},n=function(a){return"array"==ba(a)},q=function(a){return"string"==typeof a},r=function(a){return"function"==ba(a)},ca=function(a,b,c){return a.call.apply(a.bind,arguments)},da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,
d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},t=function(a,b,c){t=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return t.apply(null,arguments)},u=Date.now||function(){return+new Date},w=function(a,b){var c,d=b,e=a.split(".");c=c||k;e[0]in c||!c.execScript||c.execScript("var "+e[0]);for(var f;e.length&&(f=e.shift());)!e.length&&l(d)?c[f]=d:c=c[f]?c[f]:c[f]={}},x=function(a,b){function c(){}c.prototype=b.prototype;a.Ia=b.prototype;
a.prototype=new c;a.La=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var ea=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},fa=function(a,b){return a<b?-1:a>b?1:0};var ga=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(q(a))return q(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ha=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ia=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,
b):Array.prototype.slice.call(a,b,c)};var ja=function(a,b){var c,d;for(d in a)b.call(c,a[d],d,a)},ka=function(a,b){var c,d;for(d in a)if(b.call(c,a[d],d,a))return!0;return!1},y=function(a,b,c){return null!==a&&b in a?a[b]:c},la="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),ma=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<la.length;f++)c=la[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},na=function(a){var b=
arguments.length;if(1==b&&n(arguments[0]))return na.apply(null,arguments[0]);if(b%2)throw Error("Uneven number of arguments");for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};var z;a:{var oa=k.navigator;if(oa){var pa=oa.userAgent;if(pa){z=pa;break a}}z=""}var A=function(a){var b=z;return-1!=b.indexOf(a)},qa=function(){var a="WebKit",b=z;return-1!=b.toLowerCase().indexOf(a.toLowerCase())};var ra=function(){return A("Opera")||A("OPR")};var sa=function(a,b){this.x=l(a)?a:0;this.y=l(b)?b:0};sa.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};sa.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};var ta=ra(),B=A("Trident")||A("MSIE"),ua=A("Edge"),C=A("Gecko")&&!(qa()&&!A("Edge"))&&!(A("Trident")||A("MSIE"))&&!A("Edge"),D=qa()&&!A("Edge"),xa=function(){if(ta&&k.opera){var a;var b=k.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=va())&&(a=b?b[1]:"");return B&&(b=wa(),null!=b&&b>parseFloat(a))?String(b):a},va=function(){var a=z;if(C)return/rv\:([^\);]+)(\)|;)/.exec(a);if(ua)return/Edge\/([\d\.]+)/.exec(a);if(B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(D)return/WebKit\/(\S+)/.exec(a)},
wa=function(){var a=k.document;return a?a.documentMode:void 0},ya=xa(),za={},E=function(a){var b;if(!(b=za[a])){var c=a;b=ya;var d=0;b=ea(String(b)).split(".");for(var c=ea(String(c)).split("."),e=Math.max(b.length,c.length),f=0;0==d&&f<e;f++){var g=b[f]||"",h=c[f]||"",m=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var v=m.exec(g)||["","",""],P=p.exec(h)||["","",""];if(0==v[0].length&&0==P[0].length)break;var d=0==v[1].length?0:parseInt(v[1],10),Pb=0==P[1].length?0:parseInt(P[1],10),
d=fa(d,Pb)||fa(0==v[2].length,0==P[2].length)||fa(v[2],P[2])}while(0==d)}b=d;b=za[a]=0<=b}return b},Ba=function(){var a=9;return Number(Aa)>=a},Ca,Da=k.document,Ea=wa(),Aa=Ca=Da&&B?Ea||("CSS1Compat"==Da.compatMode?parseInt(ya,10):5):void 0;!C&&!B||B&&Ba()||C&&E("1.9.1");B&&E("9");var F=function(a){return a?a.parentWindow||a.defaultView:window};var Fa=function(){var a=F().top;try{return!!a.location.href||""===a.location.href}catch(b){return!1}};var Ga=[],Ha=!1,Ia=function(a){if(Ha)for(var b=0;b<Ga.length;b++)a(t(Ga[b].Ua,Ga[b]))};var Ja=function(a){Ja[" "](a);return a};Ja[" "]=aa;var Ka=!B||Ba(),La=B&&!E("9");!D||E("528");C&&E("1.9b")||B&&E("8")||ta&&E("9.5")||D&&E("528");C&&!E("8")||B&&E("9");var Ma=function(){this.ha=this.ha;this.Ba=this.Ba};Ma.prototype.ha=!1;var G=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.B=!1;this.na=!0};G.prototype.preventDefault=function(){this.defaultPrevented=!0;this.na=!1};var H=function(a,b){G.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.aa=this.state=null;if(a){var c=a,d=b,e=this.type=c.type,f=c.changedTouches?c.changedTouches[0]:null;this.target=c.target||c.srcElement;this.currentTarget=d;if(d=c.relatedTarget){if(C){var g;a:{var h="nodeName";try{Ja(d[h]);
g=!0;break a}catch(m){}g=!1}g||(d=null)}}else"mouseover"==e?d=c.fromElement:"mouseout"==e&&(d=c.toElement);this.relatedTarget=d;null===f?(this.offsetX=D||void 0!==c.offsetX?c.offsetX:c.layerX,this.offsetY=D||void 0!==c.offsetY?c.offsetY:c.layerY,this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=void 0!==c.clientY?c.clientY:c.pageY,this.screenX=c.screenX||0,this.screenY=c.screenY||0):(this.clientX=void 0!==f.clientX?f.clientX:f.pageX,this.clientY=void 0!==f.clientY?f.clientY:f.pageY,this.screenX=
f.screenX||0,this.screenY=f.screenY||0);this.button=c.button;this.keyCode=c.keyCode||0;this.charCode=c.charCode||("keypress"==e?c.keyCode:0);this.ctrlKey=c.ctrlKey;this.altKey=c.altKey;this.shiftKey=c.shiftKey;this.metaKey=c.metaKey;this.state=c.state;this.aa=c;c.defaultPrevented&&this.preventDefault()}};x(H,G);
H.prototype.preventDefault=function(){H.Ia.preventDefault.call(this);var a=this.aa;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,La)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var I="closure_listenable_"+(1E6*Math.random()|0),Na=0;var Oa=function(a,b,c,d,e){var f=null;this.listener=a;this.P=f;this.src=b;this.type=c;this.H=!!d;this.J=e;this.key=++Na;this.C=this.G=!1},Pa=function(a){a.C=!0;a.listener=null;a.P=null;a.src=null;a.J=null};var J=function(a){this.src=a;this.f={};this.W=0};J.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.f[f];a||(a=this.f[f]=[],this.W++);var g=Qa(a,b,d,e);-1<g?(b=a[g],c||(b.G=!1)):(b=new Oa(b,this.src,f,!!d,e),b.G=c,a.push(b));return b};J.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.f))return!1;var e=this.f[a];b=Qa(e,b,c,d);return-1<b?(c=e[b],Pa(c),c=e,Array.prototype.splice.call(c,b,1),0==e.length&&(delete this.f[a],this.W--),!0):!1};
var Ra=function(a,b){var c=b.type;if(c in a.f){var d,e=a.f[c],f=ga(e,b);(d=0<=f)&&Array.prototype.splice.call(e,f,1);d&&(Pa(b),0==a.f[c].length&&(delete a.f[c],a.W--))}};J.prototype.ca=function(a,b,c,d){a=this.f[a.toString()];var e=-1;a&&(e=Qa(a,b,c,d));return-1<e?a[e]:null};var Qa=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.C&&f.listener==b&&f.H==!!c&&f.J==d)return e}return-1};var Sa="closure_lm_"+(1E6*Math.random()|0),Ta={},Ua=0,K=function(a,b,c,d,e){if(n(b))for(var f=0;f<b.length;f++)K(a,b[f],c,d,e);else c=Va(c),a&&a[I]?a.o.add(String(b),c,!1,d,e):Wa(a,b,c,!1,d,e)},Wa=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=!!e,h=L(a);h||(a[Sa]=h=new J(a));c=h.add(b,c,d,e,f);if(!c.P){d=Xa();c.P=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,g);else if(a.attachEvent)a.attachEvent(Ya(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");
Ua++}},Xa=function(){var a=Za,b=Ka?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},$a=function(a,b,c,d,e){if(n(b))for(var f=0;f<b.length;f++)$a(a,b[f],c,d,e);else c=Va(c),a&&a[I]?a.o.add(String(b),c,!0,d,e):Wa(a,b,c,!0,d,e)},ab=function(a,b,c,d,e){if(n(b))for(var f=0;f<b.length;f++)ab(a,b[f],c,d,e);else c=Va(c),a&&a[I]?a.o.remove(String(b),c,d,e):a&&(d=!!d,(a=L(a))&&(b=a.ca(b,c,d,e))&&bb(b))},bb=function(a){if("number"!=typeof a&&a&&
!a.C){var b=a.src;if(b&&b[I])Ra(b.o,a);else{var c=a.type,d=a.P;b.removeEventListener?b.removeEventListener(c,d,a.H):b.detachEvent&&b.detachEvent(Ya(c),d);Ua--;(c=L(b))?(Ra(c,a),0==c.W&&(c.src=null,b[Sa]=null)):Pa(a)}}},Ya=function(a){return a in Ta?Ta[a]:Ta[a]="on"+a},db=function(a,b,c,d){var e=!0;if(a=L(a))if(b=a.f[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.H==c&&!f.C&&(f=cb(f,d),e=e&&!1!==f)}return e},cb=function(a,b){var c=a.listener,d=a.J||a.src;a.G&&bb(a);return c.call(d,
b)},Za=function(a,b){if(a.C)return!0;if(!Ka){var c;if(!(c=b))a:{var d;c="window.event";c=c.split(".");d=d||k;for(var e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;d=new H(e,this);c=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(m){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=d.currentTarget;f;f=f.parentNode)e.push(f);for(var f=a.type,g=e.length-1;!d.B&&0<=g;g--){d.currentTarget=e[g];var h=db(e[g],f,!0,d);c=
c&&h}for(g=0;!d.B&&g<e.length;g++)d.currentTarget=e[g],h=db(e[g],f,!1,d),c=c&&h}return c}return cb(a,new H(b,this))},L=function(a){a=a[Sa];return a instanceof J?a:null},eb="__closure_events_fn_"+(1E9*Math.random()>>>0),Va=function(a){if(r(a))return a;a[eb]||(a[eb]=function(b){return a.handleEvent(b)});return a[eb]};Ia(function(a){Za=a(Za)});var M=function(a){this.A=na.apply(null,arguments);return this};M.prototype.remove=function(a){var b=this.A;a in b&&delete b[a]};M.prototype.set=function(a,b){this.A[a]=b};M.prototype.get=function(a){return y(this.A,a,null)};M.prototype.extend=function(a){ma(this.A,a)};M.prototype.i=function(){var a=[],b;for(b in this.A)a.push(b+this.A[b]);return a.join("_")};var N=function(){return Math.round(u()/1E3)},fb=function(a){return window.performance&&window.performance.timing&&window.performance.timing.domLoading&&0<window.performance.timing[a]?(a=u()-window.performance.timing[a],Math.round(a/1E3)):null},gb=function(){this.domLoading=fb("domLoading");this.domComplete=fb("domComplete");this.unloadEventStart=fb("unloadEventStart")};
gb.prototype.toString=function(){function a(a){a=y(c,a);null!=a?b.push(""+a):b.push("u")}var b=[],c=this;a("domLoading");a("domComplete");a("unloadEventStart");return b.join(".")};var hb=function(){return new gb};window.console&&"function"===typeof window.console.log&&t(window.console.log,window.console);var ib=function(a){if(/^\s*$/.test(a))return!1;var b=/\\["\\\/bfnrtu]/g,c=/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},jb=function(a){a=String(a);if(ib(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},kb=function(a){this.R=a};
kb.prototype.i=function(a){var b=[];lb(this,a,b);return b.join("")};
var lb=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(n(b)){var d=a;a=b;b=a.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=a[f],lb(d,d.R?d.R.call(a,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),mb(d,c),c.push(":"),lb(a,a.R?a.R.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":mb(b,
c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}},nb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},ob=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g,mb=function(a,b){b.push('"',a.replace(ob,function(a){var b=nb[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),
nb[a]=b);return b}),'"')};var pb=function(){var a;if(!a)return this;var b=a.Oa(),c=a.Pa(),d=a.Na(),e=a.ja(),f=a.da();a=a.g;b&&(this.er=b.i());c&&(this.vi=c.i());null!=d&&(this.buckets=d);null!=e&&(this.tt=e);null!=f&&(this.pd=f);null!=a&&(this.lt=a);return this};var qb=null,rb=function(){var a="google_video_inner_static_iframe",b=document;if(b.body){var c;try{c=b.createElement('<iframe name="'+a+'" id="'+a+'" src="about:blank" style="height: 0px; width: 0px; display:none">'),b.body.appendChild(c)}catch(d){c=b.createElement("iframe"),c.setAttribute("name",a),c.setAttribute("id",a),c.setAttribute("src","about:blank"),c.setAttribute("style","height: 0px; width: 0px; display:none"),b.body.appendChild(c)}}else b.write("<iframe frameBorder='0' src='about:blank' id='"+
a+"' name='"+a+"' style='height:0px;width:0px;display:none'></iframe>")},sb=function(a){a=a.aa;if(F().top==a.source){var b;a:{a=a.data;var c="data";try{if(0==a.lastIndexOf(c,0)){var d=a.substring(c.length),e=new pb;0<d.length&&ma(e,jb(d));b=e;break a}}catch(f){}b=null}null!=b&&(qb=b)}},tb=function(){if(!Fa()){var a=F().frames;(a=a.length&&a.google_video_inner_static_iframe)||rb();K(F(),"message",sb);w("ima.video.client.getLastSnapshotFromTop",function(){return qb});F().top.postMessage&&F().top.postMessage("get",
"*")}};var O=function(a,b){this.kv={};this.update(a,b);return this},ub={m:!0,c:!0,s:!0,t:!0},vb=function(a,b){var c=null!==ub&&a in ub,d="m"==a,e=d&&100<=b;return c&&(e||!d)&&0<b};O.prototype.update=function(a,b){if(a){var c=b?b:1,d=y(this.kv,a,0);this.kv[a]=d+c}};O.prototype.extend=function(a){var b=this;a&&ja(a.kv,function(a,d){b.kv[d]=y(b.kv,d,0)+a})};O.prototype.i=function(a){var b="";ja(this.kv,function(a,d){b+=vb(d,a)?d+a:""});return b?a+b:b};
var wb=function(a){return ka(a.kv,function(a,c){return vb(c,a)})};var xb=function(a,b){this.Z=a;this.F=N();this.za=b;this.a=[];this.g=-1};xb.prototype.length=function(){return this.a.length};var yb=function(a,b){var c=Math.floor((b-a.F)/a.Z);return Math.max(0,c)};xb.prototype.add=function(a,b){var c=N();vb(a,"number"==typeof b?b:1)&&(this.g=c);var d=c,e=yb(this,d),e=e+1-this.za;0==this.a.length?this.F=d:e>=this.a.length?(this.F=d,this.a=[]):0<e&&(this.a=ia(this.a,e),this.F+=e*this.Z);c=yb(this,c);d=a;e=b;this.a[c]?this.a[c].update(d,e):this.a[c]=new O(d,e)};var Q=function(){Ma.call(this);this.o=new J(this);this.pa=this;this.ma=null};x(Q,Ma);var zb=Q;zb.prototype[I]=!0;Q.prototype.addEventListener=function(a,b,c,d){K(this,a,b,c,d)};Q.prototype.removeEventListener=function(a,b,c,d){ab(this,a,b,c,d)};
Q.prototype.dispatchEvent=function(a){var b,c=this.ma;if(c){b=[];for(var d=1;c;c=c.ma)b.push(c),++d}c=this.pa;d=a.type||a;if(q(a))a=new G(a,c);else if(a instanceof G)a.target=a.target||c;else{var e=a;a=new G(d,c);ma(a,e)}var e=!0,f;if(b)for(var g=b.length-1;!a.B&&0<=g;g--)f=a.currentTarget=b[g],e=Ab(f,d,!0,a)&&e;a.B||(f=a.currentTarget=c,e=Ab(f,d,!0,a)&&e,a.B||(e=Ab(f,d,!1,a)&&e));if(b)for(g=0;!a.B&&g<b.length;g++)f=a.currentTarget=b[g],e=Ab(f,d,!1,a)&&e;return c=e};
var Ab=function(a,b,c,d){b=a.o.f[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.C&&g.H==c){var h=g.listener,m=g.J||g.src;g.G&&Ra(a.o,g);e=!1!==h.call(m,d)&&e}}return e&&0!=d.na};Q.prototype.ca=function(a,b,c,d){return this.o.ca(String(a),b,c,d)};var Bb=function(a,b,c){this.ya=c;this.ta=a;this.Ha=b;this.N=0;this.K=null};Bb.prototype.get=function(){var a;0<this.N?(this.N--,a=this.K,this.K=a.next,a.next=null):a=this.ta();return a};Bb.prototype.put=function(a){this.Ha(a);this.N<this.ya&&(this.N++,a.next=this.K,this.K=a)};var Cb=function(a){return a};var Db=function(a){k.setTimeout(function(){throw a;},0)},Eb,Fb=function(){var a=k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var c=a.contentWindow,a=c.document;a.open();a.write("");a.close();var b="callImmediate"+Math.random(),d="file:"==c.location.protocol?"*":c.location.protocol+"//"+c.location.host,
a=t(function(a){if(("*"==d||a.origin==d)&&a.data==b)this.port1.onmessage()},this);c.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){c.postMessage(b,d)}}});if("undefined"!==typeof a&&!A("Trident")&&!A("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(l(c.next)){c=c.next;var a=c.ga;c.ga=null;a()}};return function(a){d.next={ga:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?
function(a){var c=document.createElement("SCRIPT");c.onreadystatechange=function(){c.onreadystatechange=null;c.parentNode.removeChild(c);c=null;a();a=null};document.documentElement.appendChild(c)}:function(a){k.setTimeout(a,0)}},Gb=Cb;Ia(function(a){Gb=a});var Hb=function(){this.X=this.D=null},Jb=new Bb(function(){return new Ib},function(a){a.reset()},100);Hb.prototype.add=function(a,b){var c=Jb.get();c.set(a,b);this.X?this.X.next=c:this.D=c;this.X=c};Hb.prototype.remove=function(){var a=null;this.D&&(a=this.D,this.D=this.D.next,this.D||(this.X=null),a.next=null);return a};var Ib=function(){this.next=this.scope=this.ba=null};Ib.prototype.set=function(a,b){this.ba=a;this.scope=b;this.next=null};
Ib.prototype.reset=function(){this.next=this.scope=this.ba=null};var Ob=function(a,b){Kb||Lb();Mb||(Kb(),Mb=!0);Nb.add(a,b)},Kb,Lb=function(){if(k.Promise&&k.Promise.resolve){var a=k.Promise.resolve(void 0);Kb=function(){a.then(Qb)}}else Kb=function(){var a,c,d=Qb,e=d;a&&(e=t(d,a));e=Gb(e);!r(k.setImmediate)||!c&&k.Window&&k.Window.prototype&&!A("Edge")&&k.Window.prototype.setImmediate==k.setImmediate?(Eb||(Eb=Fb()),Eb(e)):k.setImmediate(e)}},Mb=!1,Nb=new Hb,Qb=function(){for(var a=null;a=Nb.remove();){try{a.ba.call(a.scope)}catch(b){Db(b)}Jb.put(a)}Mb=!1};var Rb=function(){this.next=this.context=this.la=this.ka=this.sa=null;this.qa=!1};Rb.prototype.reset=function(){this.context=this.la=this.ka=this.sa=null;this.qa=!1};
var Sb=new Bb(function(){return new Rb},function(a){a.reset()},100),Tb=function(a,b,c){var d=Sb.get();d.ka=a;d.la=b;d.context=c;return d},Vb=function(a,b){a.ra||2!=a.S&&3!=a.S||Ub(a);var c=a,d=b;c.fa?c.fa.next=d:c.ra=d;c.fa=d},Yb=function(a,b,c){if(0==a.S){a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.S=1;var d;a:{var e=c,f=a.Sa,g=a.Ta,h=a,m;if(e)try{m=!!e.$goog_Thenable}catch(v){m=!1}else m=!1;if(m)e.then(f,g,h),d=!0;else{m=typeof e;if(m="object"==m&&null!=e||"function"==m)try{var p=
e.then;if(r(p)){Wb(e,p,f,g,h);d=!0;break a}}catch(v){g.call(h,v);d=!0;break a}d=!1}}d||(a.Ra=c,a.S=b,a.Qa=null,Ub(a),3!=b||Xb(a,c))}},Wb=function(a,b,c,d,e){var f=!1,g=function(a){f||(f=!0,c.call(e,a))},h=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,g,h)}catch(m){h(m)}},Ub=function(a){a.ua||(a.ua=!0,Ob(a.Ma,a))},Xb=function(a,b){a.xa=!0;Ob(function(){a.xa&&Zb.call(null,b)})},Zb=Db;var R=function(a,b){Q.call(this);this.L=a||1;this.U=b||k;this.Y=t(this.Ja,this);this.ea=u()};x(R,Q);R.prototype.enabled=!1;R.prototype.v=null;R.prototype.Ja=function(){if(this.enabled){var a=u()-this.ea;0<a&&a<.8*this.L?this.v=this.U.setTimeout(this.Y,this.L-a):(this.v&&(this.U.clearTimeout(this.v),this.v=null),this.dispatchEvent("tick"),this.enabled&&(this.v=this.U.setTimeout(this.Y,this.L),this.ea=u()))}};
R.prototype.start=function(){this.enabled=!0;this.v||(this.v=this.U.setTimeout(this.Y,this.L),this.ea=u())};var S=function(a,b,c){this.l=c;this.M=null;this.I=0;this.Aa=500;this.T=null;$b(this,a,b);c=document.documentElement;var d;try{if(Fa()){var e;b=[];var f=F(c.ownerDocument);for(c=f;c!=f.top;c=c.parent)if(c.frameElement)b.push(c.frameElement);else break;d=(e=b)&&0!=e.length?"1":"0"}else d="2"}catch(h){d="2"}try{if("1"==d){for(var g=a.parent;g!=a.top;g=g.parent)$b(this,g,g.document);$b(this,a.top,a.top.document)}}catch(h){}},$b=function(a,b,c){K(c,"mousedown",t(a.Ca,a));K(b,"scroll",t(a.Fa,a));K(c,"touchstart",
t(a.Ga,a));K(c,"mousemove",t(a.Ea,a))};S.prototype.Ga=function(){this.l&&this.l("t")};S.prototype.Ca=function(){this.l&&this.l("c")};S.prototype.Fa=function(){this.l&&this.l("s")};
S.prototype.Ea=function(a){a=new sa(a.clientX,a.clientY);if(this.M){var b,c=this.M;b=c.x-a.x;c=c.y-a.y;b=Math.sqrt(b*b+c*c);this.I+=Math.round(b)}this.M=a;this.T&&k.clearTimeout(this.T);a=this.Da;b=this.Aa;if(r(a))this&&(a=t(a,this));else if(a&&"function"==typeof a.handleEvent)a=t(a.handleEvent,a);else throw Error("Invalid listener argument");this.T=a=2147483647<Number(b)?-1:k.setTimeout(a,b||0)};S.prototype.Da=function(){this.l&&this.l("m",this.I);this.M=this.T=null;this.I=0};var ac=0,T=null,bc=function(){ac=N();T=new xb(10,12);new S(F(),document,t(T.add,T))},cc=function(a,b){a&&(N=a);b&&(hb=b)};var U=function(a,b){var c;T||bc();c=T;this.j=new M("tt",N()-ac,"pd",a,"bs",c.Z);this.g=c.g;b&&b>this.g&&(this.g=b);c.add();for(var d=[],e=0;e<c.a.length;e++){var f;6>=c.a.length?f=e:(f=c.a.length-6,f=e<=f?0:e-f);d[f]||(d[f]=new O);c.a[e]&&d[f].extend(c.a[e])}c=d;this.a=c.reverse();a:{for(c=0;c<this.a.length;c++)if(this.a[c]&&wb(this.a[c]))break a;c=null}null!=c&&this.j.set("es",c);return this};U.prototype.ja=function(){return this.j.get("tt")};U.prototype.da=function(){return this.j.get("pd")};
U.prototype.wa=function(){return this.a};var dc=function(a,b){var c=a;ha(b,function(a,b){if(b>=c.a.length||!c.a[b])c.a[b]=new O;c.a[b].extend(a)})};U.prototype.va=function(a,b,c,d){dc(this,a);null!=b&&this.j.set("tt",Math.max(this.j.get("tt"),b));null!=c&&this.j.set("pd",Math.max(this.j.get("pd"),c));d&&-1!=d&&(this.g=Math.max(this.g,d))};
U.prototype.i=function(){var a=[],b;b=[];for(var c=0;c<this.a.length;c++)if(this.a[c]){var d=this.a[c].i("ed"+c);d&&b.push(d)}(b=b.join("_"))&&a.push(b);(b=this.j.i())&&a.push(b);b=-1==this.g?-1:N()-this.g;-1!=b&&(b*=1E3);a.push("la"+b);return a.join("_")};U.prototype.getTimeSinceTagLoadSeconds=U.prototype.ja;U.prototype.getPlaylistTimeDiff=U.prototype.da;U.prototype.getPlaylistTimeDiff=U.prototype.da;U.prototype.getBuckets=U.prototype.wa;U.prototype.extendWithDataFromTopIframe=U.prototype.va;
U.prototype.serialize=U.prototype.i;var ec=A("Safari")&&!((A("Chrome")||A("CriOS"))&&!ra()&&!A("Edge")||A("Coast")||ra()||A("Edge")||A("Silk")||A("Android"))&&!(A("iPhone")&&!A("iPod")&&!A("iPad")||A("iPad")||A("iPod"));var V=null,fc=null,gc=null,hc=C||D&&!ec||ta,ic=hc||"function"==typeof k.btoa,jc=hc||!ec&&!B&&"function"==typeof k.atob,lc=function(a,b){var c=a;ba(c);kc();for(var c=b?gc:V,d=[],e=0;e<a.length;e+=3){var f=a[e],g=e+1<a.length,h=g?a[e+1]:0,m=e+2<a.length,p=m?a[e+2]:0,v=f>>2,f=(f&3)<<4|h>>4,h=(h&15)<<2|p>>6,p=p&63;m||(p=64,g||(h=64));d.push(c[v],c[f],c[h],c[p])}return d.join("")},nc=function(a){var b=!0;function c(a){d+=String.fromCharCode(a)}if(jc&&!b)return k.atob(a);var d="";mc(a,c);return d},mc=function(a,
b){function c(c){for(;d<a.length;){var b=a.charAt(d++),e=fc[b];if(null!=e)return e;if(!/^[\s\xa0]*$/.test(b))throw Error("Unknown base64 encoding at char: "+b);}return c}kc();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;e=e<<2|f>>4;b(e);64!=g&&(f=f<<4&240|g>>2,b(f),64!=h&&(g=g<<6&192|h,b(g)))}},kc=function(){if(!V){V={};fc={};gc={};for(var a=0;65>a;a++)V[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a),fc[V[a]]=a,gc[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a),
62<=a&&(fc["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a)]=a)}};var oc=function(){this.h=-1};var W=function(){this.h=-1;this.h=64;this.b=[];this.$=[];this.oa=[];this.O=[];this.O[0]=128;for(var a=1;a<this.h;++a)this.O[a]=0;this.V=this.w=0;this.reset()};x(W,oc);W.prototype.reset=function(){this.b[0]=1732584193;this.b[1]=4023233417;this.b[2]=2562383102;this.b[3]=271733878;this.b[4]=3285377520;this.V=this.w=0};
var pc=function(a,b,c){c||(c=0);var d=a.oa;if(q(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.b[0];c=a.b[1];for(var g=a.b[2],h=a.b[3],m=a.b[4],p,e=0;80>e;e++)40>e?20>e?(f=h^c&(g^h),p=1518500249):(f=c^g^h,p=1859775393):60>e?(f=c&g|h&(c|g),p=2400959708):(f=c^g^h,p=3395469782),
f=(b<<5|b>>>27)+f+m+p+d[e]&4294967295,m=h,h=g,g=(c<<30|c>>>2)&4294967295,c=b,b=f;a.b[0]=a.b[0]+b&4294967295;a.b[1]=a.b[1]+c&4294967295;a.b[2]=a.b[2]+g&4294967295;a.b[3]=a.b[3]+h&4294967295;a.b[4]=a.b[4]+m&4294967295};
W.prototype.update=function(a,b){if(null!=a){l(b)||(b=a.length);for(var c=b-this.h,d=0,e=this.$,f=this.w;d<b;){if(0==f)for(;d<=c;)pc(this,a,d),d+=this.h;if(q(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.h){pc(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.h){pc(this,e);f=0;break}}this.w=f;this.V+=b}};
W.prototype.digest=function(){var a=[],b=8*this.V;56>this.w?this.update(this.O,56-this.w):this.update(this.O,this.h-(this.w-56));for(var c=this.h-1;56<=c;c--)this.$[c]=b&255,b/=256;pc(this,this.$);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.b[c]>>d&255,++b;return a};var X=function(a){this.ia=a},qc=/\s*;\s*/;X.prototype.isEnabled=function(){return navigator.cookieEnabled};X.prototype.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');l(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";0>c?c="":(c=0==c?new Date(1970,1,1):new Date(u()+1E3*c),c=";expires="+c.toUTCString());this.ia.cookie=a+"="+b+e+d+c+f};
X.prototype.get=function(a,b){for(var c=a+"=",d=(this.ia.cookie||"").split(qc),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};X.prototype.remove=function(a,b,c){var d=l(this.get(a));this.set(a,"",0,b,c);return d};var Y=new X(document);Y.Ka=3950;var rc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;var Z=null,sc=null,tc=function(a,b,c,d,e,f){this.u=c;this.t=a;this.ed=b;this.nv=d;this.pl=e;this.lt=f},uc=function(a){a=a.split("#")[0];var b=new W;b.update(a);a=b.digest();return lc(a).slice(0,4)},wc=function(){var a=vc(),b=0,c;var d=vc();if(d&&d.t){c=hb().unloadEventStart;var e=N(),d=d.t;c=c&&d>=e-c?!0:8>=sc-d}else c=!1;a:{e=uc(document.URL);if(Z)for(d=0;d<Z.length;d++)if(Z[d].u==e){e=!0;break a}e=!1}d=vc();d=!!d&&0<d.nv;(c=c&&!e&&!d)&&a&&a.pl&&(b=a.pl);return N()-ac+b},xc=function(){var a=null;
if(Y.isEnabled()&&l(Y.get("GED_PLAYLIST_ACTIVITY"))){var b=Y.get("GED_PLAYLIST_ACTIVITY");if(b)try{b=nc(b),a=jb(b)}catch(c){}}return a},vc=function(){if(Z)for(var a=uc(document.referrer),b=0;b<Z.length;b++)if(Z[b].u==a)return Z[b];return null},yc=function(){if(Y.isEnabled()){var a=wc(),b=new U(a,-1),c;a:{c=Math.min(b.a.length,2);for(var d=0;d<c;d++){var e;if(e=b.a[d])e="c",e=e in b.a[d].kv;if(e){c=!0;break a}}c=!1}d=b.g;e=N();var f=uc(document.URL),a=new tc(e,b,f,c?1:0,a,d),b=xc();c=[];if(b){c=b.length;
if(0<c){d=Array(c);for(e=0;e<c;e++)d[e]=b[e];b=d}else b=[];c=document.URL;c=uc(c);d=N();for(e=0;e<b.length;e++)if(b[e].u==c||1200<=d-b[e].t)b.splice(e,1),e--;c=b}a&&c.unshift(a);c=c.slice(0,3);var g,a=g=(new kb(g)).i(c);g=!0;if(ic&&!g)g=k.btoa(a);else{b=[];for(d=c=0;d<a.length;d++){for(e=a.charCodeAt(d);255<e;)b[c++]=e&255,e>>=8;b[c++]=e}a=b;g=lc(a,g)}a=document.URL;b=1;a=a.match(rc)[b]||null;a="http"==a;Y.set("GED_PLAYLIST_ACTIVITY",g,-1,"/",null,!a)}};var zc=function(){function a(){try{yc()}catch(a){}}if(!(window.ima&&window.ima.video&&window.ima.video.client&&window.ima.video.client.tagged)){bc();$a(F(),"unload",a);try{sc||(sc=N(),Z=xc())}catch(c){}var b=new R(1E3);b.start();K(b,"tick",function(){try{yc()}catch(a){}});w("ima.video.client.getEData",function(){var a=wc(),b;a:{if(Z)for(b=0;b<Z.length;b++){var e;e=Z[b];if(e=null!==e&&"lt"in e){b=Z[b].lt;break a}}b=-1}return new U(a,b)});w("ima.video.client.setupEDHooks",bc);w("ima.video.client.resetEDForTesting",
cc);w("ima.video.client.tagged",!0)}};w("ima.video.client.jsTag",!0);tb();zc();})()

Error saving setting with name: consoleHistory, value length: 5426047. Error: Failed to set the 'consoleHistory' property on 'Storage': Setting the value of 'consoleHistory' exceeded the quota.
Ten largest settings: 
Setting: 'consoleHistory', size: 5234863
Setting: 'previouslyViewedFiles', size: 4052
Setting: 'savedURLs', size: 3514
Setting: 'breakpoints', size: 227
Setting: 'watchExpressions', size: 13
Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
Setting: 'domBreakpoints', size: 2
Setting: 'eventListenerBreakpoints', size: 2
Setting: 'experiments', size: 2
Setting: 'workspaceExcludedFolders', size: 2
undefined
Error saving setting with name: savedURLs, value length: 3637. Error: Failed to set the 'savedURLs' property on 'Storage': Setting the value of 'savedURLs' exceeded the quota.
Ten largest settings: 
Setting: 'consoleHistory', size: 5234863
Setting: 'previouslyViewedFiles', size: 4052
Setting: 'savedURLs', size: 3514
Setting: 'breakpoints', size: 227
Setting: 'watchExpressions', size: 13
Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
Setting: 'domBreakpoints', size: 2
Setting: 'eventListenerBreakpoints', size: 2
Setting: 'experiments', size: 2
Setting: 'workspaceExcludedFolders', size: 2
Error saving setting with name: savedURLs, value length: 3678. Error: Failed to set the 'savedURLs' property on 'Storage': Setting the value of 'savedURLs' exceeded the quota.
Ten largest settings: 
Setting: 'consoleHistory', size: 5234863
Setting: 'previouslyViewedFiles', size: 4052
Setting: 'savedURLs', size: 3514
Setting: 'breakpoints', size: 227
Setting: 'watchExpressions', size: 13
Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
Setting: 'domBreakpoints', size: 2
Setting: 'eventListenerBreakpoints', size: 2
Setting: 'experiments', size: 2
Setting: 'workspaceExcludedFolders', size: 2

