-My build DIGITAL Command Language:
-Muhammad Adi Nugroho,S.Adm.Neg.:
-Web Browser:
-Mozilla Firefox:
-Via My Notepad++ (HTML Editor):
<!DOCTYPE html><html prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#"  lang="id-ID"  style="font-size:62.5%"  class="hiperf"  dir="ltr" >

 <body>
 
 <SCRIPT TYPE = "text/javascript" 
         SRC = " C:\Users\Axioo\Favorites\headData.js "></SCRIPT>
			
	 
		 </body>
		 </html>
		 		 
-Function Identifier:
asdfgo1312
true
-
applicationCache
OfflineResourceList { status: 0, onchecking: null, onerror: null, onnoupdate: null, ondownloading: null, onprogress: null, onupdateready: null, oncached: null, onobsolete: null, mozItems: DOMStringList[0] }
-
unreachable code after return statement client:380:1
unreachable code after return statement client:380:1
SyntaxError: expected expression, got '<' extension.js:1:0
aff
"mikes-top-picks.com"
Prefixed Fullscreen API is deprecated. Please use unprefixed API for fullscreen. For more help https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API rhpop_1.1.45.js:1:2519
'mozHidden' and 'mozVisibilityState' are deprecated.  Please use the unprefixed 'hidden' and 'visibilityState' instead. rhpop_1.1.45.js:1:2519
-
a8
"navigator"
-
a
"file:///C:/Users/Axioo/Favorites/pub.html"
-
a.__proto__
String
-
crypto
Crypto { subtle: SubtleCrypto }
-
content
Window → file:///C:/Users/Axioo/Favorites/pub.html
-
closed
false
-
Controllers
DOMPrototype { , 1 more… }
-
domain_for_sanity
undefined
-
document
HTMLDocument → file:///C:/Users/Axioo/Favorites/pub.html
23:56:21.808 HTMLDocument → file:///C:/Users/Axioo/Favorites/pub.html

-
dispached
true
-
devicePixelRatio
1
-
DealPlyDomParams
Object { partner: "crbfii", channel: "crbfiicrdr_300303410029000000", sset: "1", dom: "", fq: "", itype: "i", countryCode: "ID", appTitle: "Deal 4 Us", scriptTagUrl: "//i.crbfiijs.info/crbfii/javascript…", firstTime: "false", 8 more… }
-
-Via Google Chrome:
external
Object {}AddSearchProvider: ()arguments: nullcaller: nulllength: 1name: ""prototype: Object__proto__: ()<function scope>IsSearchProviderInstalled: ()__proto__: Object
-
frames
Window {external: Object, chrome: Object, document: document, c: undefined, speechSynthesis: SpeechSynthesis…}Infinity: InfinityAnalyserNode: AnalyserNode()arguments: nullcaller: nulllength: 0name: "AnalyserNode"prototype: AnalyserNode__proto__: AudioNode()<function scope>AnimationEvent: AnimationEvent()AppBannerPromptResult: AppBannerPromptResult()ApplicationCache: ApplicationCache()ApplicationCacheErrorEvent: ApplicationCacheErrorEvent()Array: Array()ArrayBuffer: ArrayBuffer()Attr: Attr()Audio: HTMLAudioElement()AudioBuffer: AudioBuffer()AudioBufferSourceNode: AudioBufferSourceNode()AudioContext: AudioContext()AudioDestinationNode: AudioDestinationNode()AudioListener: AudioListener()AudioNode: AudioNode()AudioParam: AudioParam()AudioProcessingEvent: AudioProcessingEvent()AutocompleteErrorEvent: AutocompleteErrorEvent()BarProp: BarProp()BatteryManager: BatteryManager()BeforeInstallPromptEvent: BeforeInstallPromptEvent()BeforeUnloadEvent: BeforeUnloadEvent()BiquadFilterNode: BiquadFilterNode()Blob: Blob()BlobEvent: BlobEvent()Boolean: Boolean()CDATASection: CDATASection()CSS: CSS()CSSFontFaceRule: CSSFontFaceRule()CSSGroupingRule: CSSGroupingRule()CSSImportRule: CSSImportRule()CSSKeyframeRule: CSSKeyframeRule()CSSKeyframesRule: CSSKeyframesRule()CSSMediaRule: CSSMediaRule()CSSNamespaceRule: CSSNamespaceRule()CSSPageRule: CSSPageRule()CSSRule: CSSRule()CSSRuleList: CSSRuleList()CSSStyleDeclaration: CSSStyleDeclaration()CSSStyleRule: CSSStyleRule()CSSStyleSheet: CSSStyleSheet()CSSSupportsRule: CSSSupportsRule()CSSViewportRule: CSSViewportRule()Cache: Cache()CacheStorage: CacheStorage()CanvasCaptureMediaStreamTrack: CanvasCaptureMediaStreamTrack()CanvasGradient: CanvasGradient()CanvasPattern: CanvasPattern()CanvasRenderingContext2D: CanvasRenderingContext2D()ChannelMergerNode: ChannelMergerNode()ChannelSplitterNode: ChannelSplitterNode()CharacterData: CharacterData()ClientRect: ClientRect()ClientRectList: ClientRectList()ClipboardEvent: ClipboardEvent()CloseEvent: CloseEvent()Comment: Comment()CompositionEvent: CompositionEvent()ConvolverNode: ConvolverNode()Credential: Credential()CredentialsContainer: CredentialsContainer()Crypto: Crypto()CryptoKey: CryptoKey()CustomEvent: CustomEvent()DOMError: DOMError()DOMException: DOMException()DOMImplementation: DOMImplementation()DOMParser: DOMParser()DOMStringList: DOMStringList()DOMStringMap: DOMStringMap()DOMTokenList: DOMTokenList()DataTransfer: DataTransfer()DataTransferItem: DataTransferItem()DataTransferItemList: DataTransferItemList()DataView: DataView()Date: Date()DelayNode: DelayNode()DeviceMotionEvent: DeviceMotionEvent()DeviceOrientationEvent: DeviceOrientationEvent()Document: Document()DocumentFragment: DocumentFragment()DocumentType: DocumentType()DragEvent: DragEvent()DynamicsCompressorNode: DynamicsCompressorNode()Element: Element()Error: Error()ErrorEvent: ErrorEvent()EvalError: EvalError()Event: Event()EventSource: EventSource()EventTarget: EventTarget()FederatedCredential: FederatedCredential()File: File()FileError: FileError()FileList: FileList()FileReader: FileReader()Float32Array: Float32Array()Float64Array: Float64Array()FocusEvent: FocusEvent()FontFace: FontFace()FormData: FormData()Function: Function()GainNode: GainNode()Gamepad: Gamepad()GamepadButton: GamepadButton()GamepadEvent: GamepadEvent()HTMLAllCollection: HTMLAllCollection()HTMLAnchorElement: HTMLAnchorElement()HTMLAreaElement: HTMLAreaElement()HTMLAudioElement: HTMLAudioElement()HTMLBRElement: HTMLBRElement()HTMLBaseElement: HTMLBaseElement()HTMLBodyElement: HTMLBodyElement()HTMLButtonElement: HTMLButtonElement()HTMLCanvasElement: HTMLCanvasElement()HTMLCollection: HTMLCollection()HTMLContentElement: HTMLContentElement()HTMLDListElement: HTMLDListElement()HTMLDataListElement: HTMLDataListElement()HTMLDetailsElement: HTMLDetailsElement()HTMLDialogElement: HTMLDialogElement()HTMLDirectoryElement: HTMLDirectoryElement()HTMLDivElement: HTMLDivElement()HTMLDocument: HTMLDocument()HTMLElement: HTMLElement()HTMLEmbedElement: HTMLEmbedElement()HTMLFieldSetElement: HTMLFieldSetElement()HTMLFontElement: HTMLFontElement()HTMLFormControlsCollection: HTMLFormControlsCollection()HTMLFormElement: HTMLFormElement()HTMLFrameElement: HTMLFrameElement()HTMLFrameSetElement: HTMLFrameSetElement()HTMLHRElement: HTMLHRElement()HTMLHeadElement: HTMLHeadElement()HTMLHeadingElement: HTMLHeadingElement()HTMLHtmlElement: HTMLHtmlElement()HTMLIFrameElement: HTMLIFrameElement()HTMLImageElement: HTMLImageElement()HTMLInputElement: HTMLInputElement()HTMLKeygenElement: HTMLKeygenElement()HTMLLIElement: HTMLLIElement()HTMLLabelElement: HTMLLabelElement()HTMLLegendElement: HTMLLegendElement()HTMLLinkElement: HTMLLinkElement()HTMLMapElement: HTMLMapElement()HTMLMarqueeElement: HTMLMarqueeElement()HTMLMediaElement: HTMLMediaElement()HTMLMenuElement: HTMLMenuElement()HTMLMetaElement: HTMLMetaElement()HTMLMeterElement: HTMLMeterElement()HTMLModElement: HTMLModElement()HTMLOListElement: HTMLOListElement()HTMLObjectElement: HTMLObjectElement()HTMLOptGroupElement: HTMLOptGroupElement()HTMLOptionElement: HTMLOptionElement()HTMLOptionsCollection: HTMLOptionsCollection()HTMLOutputElement: HTMLOutputElement()HTMLParagraphElement: HTMLParagraphElement()HTMLParamElement: HTMLParamElement()HTMLPictureElement: HTMLPictureElement()HTMLPreElement: HTMLPreElement()HTMLProgressElement: HTMLProgressElement()HTMLQuoteElement: HTMLQuoteElement()HTMLScriptElement: HTMLScriptElement()HTMLSelectElement: HTMLSelectElement()HTMLShadowElement: HTMLShadowElement()HTMLSourceElement: HTMLSourceElement()HTMLSpanElement: HTMLSpanElement()HTMLStyleElement: HTMLStyleElement()HTMLTableCaptionElement: HTMLTableCaptionElement()HTMLTableCellElement: HTMLTableCellElement()HTMLTableColElement: HTMLTableColElement()HTMLTableElement: HTMLTableElement()HTMLTableRowElement: HTMLTableRowElement()HTMLTableSectionElement: HTMLTableSectionElement()HTMLTemplateElement: HTMLTemplateElement()HTMLTextAreaElement: HTMLTextAreaElement()HTMLTitleElement: HTMLTitleElement()HTMLTrackElement: HTMLTrackElement()HTMLUListElement: HTMLUListElement()HTMLUnknownElement: HTMLUnknownElement()HTMLVideoElement: HTMLVideoElement()HashChangeEvent: HashChangeEvent()Headers: Headers()History: History()IDBCursor: IDBCursor()IDBCursorWithValue: IDBCursorWithValue()IDBDatabase: IDBDatabase()IDBFactory: IDBFactory()IDBIndex: IDBIndex()IDBKeyRange: IDBKeyRange()IDBObjectStore: IDBObjectStore()IDBOpenDBRequest: IDBOpenDBRequest()IDBRequest: IDBRequest()IDBTransaction: IDBTransaction()IDBVersionChangeEvent: IDBVersionChangeEvent()IIRFilterNode: IIRFilterNode()IdleDeadline: IdleDeadline()Image: HTMLImageElement()ImageBitmap: ImageBitmap()ImageData: ImageData()InputDeviceCapabilities: InputDeviceCapabilities()Int8Array: Int8Array()Int16Array: Int16Array()Int32Array: Int32Array()IntersectionObserver: IntersectionObserver()IntersectionObserverEntry: IntersectionObserverEntry()Intl: ObjectJSON: JSONKeyboardEvent: KeyboardEvent()Location: Location()MIDIAccess: MIDIAccess()MIDIConnectionEvent: MIDIConnectionEvent()MIDIInput: MIDIInput()MIDIInputMap: MIDIInputMap()MIDIMessageEvent: MIDIMessageEvent()MIDIOutput: MIDIOutput()MIDIOutputMap: MIDIOutputMap()MIDIPort: MIDIPort()Map: Map()Math: MathMediaDevices: MediaDevices()MediaElementAudioSourceNode: MediaElementAudioSourceNode()MediaEncryptedEvent: MediaEncryptedEvent()MediaError: MediaError()MediaKeyMessageEvent: MediaKeyMessageEvent()MediaKeySession: MediaKeySession()MediaKeyStatusMap: MediaKeyStatusMap()MediaKeySystemAccess: MediaKeySystemAccess()MediaKeys: MediaKeys()MediaList: MediaList()MediaQueryList: MediaQueryList()MediaQueryListEvent: MediaQueryListEvent()MediaRecorder: MediaRecorder()MediaSource: MediaSource()MediaStreamAudioDestinationNode: MediaStreamAudioDestinationNode()MediaStreamAudioSourceNode: MediaStreamAudioSourceNode()MediaStreamEvent: MediaStreamEvent()MediaStreamTrack: MediaStreamTrack()MessageChannel: MessageChannel()MessageEvent: MessageEvent()MessagePort: MessagePort()MimeType: MimeType()MimeTypeArray: MimeTypeArray()MouseEvent: MouseEvent()MutationEvent: MutationEvent()MutationObserver: MutationObserver()MutationRecord: MutationRecord()NaN: NaNNamedNodeMap: NamedNodeMap()Navigator: Navigator()Node: Node()NodeFilter: NodeFilter()NodeIterator: NodeIterator()NodeList: NodeList()Notification: Notification()Number: Number()Object: Object()OfflineAudioCompletionEvent: OfflineAudioCompletionEvent()OfflineAudioContext: OfflineAudioContext()Option: HTMLOptionElement()OscillatorNode: OscillatorNode()PageTransitionEvent: PageTransitionEvent()PasswordCredential: PasswordCredential()Path2D: Path2D()Performance: Performance()PerformanceEntry: PerformanceEntry()PerformanceMark: PerformanceMark()PerformanceMeasure: PerformanceMeasure()PerformanceNavigation: PerformanceNavigation()PerformanceResourceTiming: PerformanceResourceTiming()PerformanceTiming: PerformanceTiming()PeriodicWave: PeriodicWave()PermissionStatus: PermissionStatus()Permissions: Permissions()Plugin: Plugin()PluginArray: PluginArray()PopStateEvent: PopStateEvent()Presentation: Presentation()PresentationAvailability: PresentationAvailability()PresentationConnection: PresentationConnection()PresentationConnectionAvailableEvent: PresentationConnectionAvailableEvent()PresentationConnectionCloseEvent: PresentationConnectionCloseEvent()PresentationRequest: PresentationRequest()ProcessingInstruction: ProcessingInstruction()ProgressEvent: ProgressEvent()Promise: Promise()PromiseRejectionEvent: PromiseRejectionEvent()Proxy: Proxy()PushManager: PushManager()PushSubscription: PushSubscription()RTCCertificate: RTCCertificate()RTCIceCandidate: RTCIceCandidate()RTCSessionDescription: RTCSessionDescription()RadioNodeList: RadioNodeList()Range: Range()RangeError: RangeError()ReadableByteStream: ReadableByteStream()ReadableStream: ReadableStream()ReferenceError: ReferenceError()Reflect: ObjectRegExp: RegExp()Request: Request()Response: Response()SVGAElement: SVGAElement()SVGAngle: SVGAngle()SVGAnimateElement: SVGAnimateElement()SVGAnimateMotionElement: SVGAnimateMotionElement()SVGAnimateTransformElement: SVGAnimateTransformElement()SVGAnimatedAngle: SVGAnimatedAngle()SVGAnimatedBoolean: SVGAnimatedBoolean()SVGAnimatedEnumeration: SVGAnimatedEnumeration()SVGAnimatedInteger: SVGAnimatedInteger()SVGAnimatedLength: SVGAnimatedLength()SVGAnimatedLengthList: SVGAnimatedLengthList()SVGAnimatedNumber: SVGAnimatedNumber()SVGAnimatedNumberList: SVGAnimatedNumberList()SVGAnimatedPreserveAspectRatio: SVGAnimatedPreserveAspectRatio()SVGAnimatedRect: SVGAnimatedRect()SVGAnimatedString: SVGAnimatedString()SVGAnimatedTransformList: SVGAnimatedTransformList()SVGAnimationElement: SVGAnimationElement()SVGCircleElement: SVGCircleElement()SVGClipPathElement: SVGClipPathElement()SVGComponentTransferFunctionElement: SVGComponentTransferFunctionElement()SVGCursorElement: SVGCursorElement()SVGDefsElement: SVGDefsElement()SVGDescElement: SVGDescElement()SVGDiscardElement: SVGDiscardElement()SVGElement: SVGElement()SVGEllipseElement: SVGEllipseElement()SVGFEBlendElement: SVGFEBlendElement()SVGFEColorMatrixElement: SVGFEColorMatrixElement()SVGFEComponentTransferElement: SVGFEComponentTransferElement()SVGFECompositeElement: SVGFECompositeElement()SVGFEConvolveMatrixElement: SVGFEConvolveMatrixElement()SVGFEDiffuseLightingElement: SVGFEDiffuseLightingElement()SVGFEDisplacementMapElement: SVGFEDisplacementMapElement()SVGFEDistantLightElement: SVGFEDistantLightElement()SVGFEDropShadowElement: SVGFEDropShadowElement()SVGFEFloodElement: SVGFEFloodElement()SVGFEFuncAElement: SVGFEFuncAElement()SVGFEFuncBElement: SVGFEFuncBElement()SVGFEFuncGElement: SVGFEFuncGElement()SVGFEFuncRElement: SVGFEFuncRElement()SVGFEGaussianBlurElement: SVGFEGaussianBlurElement()SVGFEImageElement: SVGFEImageElement()SVGFEMergeElement: SVGFEMergeElement()SVGFEMergeNodeElement: SVGFEMergeNodeElement()SVGFEMorphologyElement: SVGFEMorphologyElement()SVGFEOffsetElement: SVGFEOffsetElement()SVGFEPointLightElement: SVGFEPointLightElement()SVGFESpecularLightingElement: SVGFESpecularLightingElement()SVGFESpotLightElement: SVGFESpotLightElement()SVGFETileElement: SVGFETileElement()SVGFETurbulenceElement: SVGFETurbulenceElement()SVGFilterElement: SVGFilterElement()SVGForeignObjectElement: SVGForeignObjectElement()SVGGElement: SVGGElement()SVGGeometryElement: SVGGeometryElement()SVGGradientElement: SVGGradientElement()SVGGraphicsElement: SVGGraphicsElement()SVGImageElement: SVGImageElement()SVGLength: SVGLength()SVGLengthList: SVGLengthList()SVGLineElement: SVGLineElement()SVGLinearGradientElement: SVGLinearGradientElement()SVGMPathElement: SVGMPathElement()SVGMarkerElement: SVGMarkerElement()SVGMaskElement: SVGMaskElement()SVGMatrix: SVGMatrix()SVGMetadataElement: SVGMetadataElement()SVGNumber: SVGNumber()SVGNumberList: SVGNumberList()SVGPathElement: SVGPathElement()SVGPatternElement: SVGPatternElement()SVGPoint: SVGPoint()SVGPointList: SVGPointList()SVGPolygonElement: SVGPolygonElement()SVGPolylineElement: SVGPolylineElement()SVGPreserveAspectRatio: SVGPreserveAspectRatio()SVGRadialGradientElement: SVGRadialGradientElement()SVGRect: SVGRect()SVGRectElement: SVGRectElement()SVGSVGElement: SVGSVGElement()SVGScriptElement: SVGScriptElement()SVGSetElement: SVGSetElement()SVGStopElement: SVGStopElement()SVGStringList: SVGStringList()SVGStyleElement: SVGStyleElement()SVGSwitchElement: SVGSwitchElement()SVGSymbolElement: SVGSymbolElement()SVGTSpanElement: SVGTSpanElement()SVGTextContentElement: SVGTextContentElement()SVGTextElement: SVGTextElement()SVGTextPathElement: SVGTextPathElement()SVGTextPositioningElement: SVGTextPositioningElement()SVGTitleElement: SVGTitleElement()SVGTransform: SVGTransform()SVGTransformList: SVGTransformList()SVGUnitTypes: SVGUnitTypes()SVGUseElement: SVGUseElement()SVGViewElement: SVGViewElement()SVGViewSpec: SVGViewSpec()SVGZoomEvent: SVGZoomEvent()Screen: Screen()ScreenOrientation: ScreenOrientation()ScriptProcessorNode: ScriptProcessorNode()SecurityPolicyViolationEvent: SecurityPolicyViolationEvent()Selection: Selection()ServiceWorker: ServiceWorker()ServiceWorkerContainer: ServiceWorkerContainer()ServiceWorkerMessageEvent: ServiceWorkerMessageEvent()ServiceWorkerRegistration: ServiceWorkerRegistration()Set: Set()ShadowRoot: ShadowRoot()SharedWorker: SharedWorker()SourceBuffer: SourceBuffer()SourceBufferList: SourceBufferList()SpeechSynthesisEvent: SpeechSynthesisEvent()SpeechSynthesisUtterance: SpeechSynthesisUtterance()Storage: Storage()StorageEvent: StorageEvent()String: String()StyleSheet: StyleSheet()StyleSheetList: StyleSheetList()SubtleCrypto: SubtleCrypto()Symbol: Symbol()SyncManager: SyncManager()SyntaxError: SyntaxError()Text: Text()TextDecoder: TextDecoder()TextEncoder: TextEncoder()TextEvent: TextEvent()TextMetrics: TextMetrics()TextTrack: TextTrack()TextTrackCue: TextTrackCue()TextTrackCueList: TextTrackCueList()TextTrackList: TextTrackList()TimeRanges: TimeRanges()Touch: Touch()TouchEvent: TouchEvent()TouchList: TouchList()TrackEvent: TrackEvent()TransitionEvent: TransitionEvent()TreeWalker: TreeWalker()TypeError: TypeError()UIEvent: UIEvent()URIError: URIError()URL: URL()URLSearchParams: URLSearchParams()Uint8Array: Uint8Array()Uint8ClampedArray: Uint8ClampedArray()Uint16Array: Uint16Array()Uint32Array: Uint32Array()VTTCue: VTTCue()ValidityState: ValidityState()WaveShaperNode: WaveShaperNode()WeakMap: WeakMap()WeakSet: WeakSet()WebGLActiveInfo: WebGLActiveInfo()WebGLBuffer: WebGLBuffer()WebGLContextEvent: WebGLContextEvent()WebGLFramebuffer: WebGLFramebuffer()WebGLProgram: WebGLProgram()WebGLRenderbuffer: WebGLRenderbuffer()WebGLRenderingContext: WebGLRenderingContext()WebGLShader: WebGLShader()WebGLShaderPrecisionFormat: WebGLShaderPrecisionFormat()WebGLTexture: WebGLTexture()WebGLUniformLocation: WebGLUniformLocation()WebKitAnimationEvent: AnimationEvent()WebKitCSSMatrix: WebKitCSSMatrix()WebKitMutationObserver: MutationObserver()WebKitTransitionEvent: TransitionEvent()WebSocket: WebSocket()WheelEvent: WheelEvent()Window: Window()Worker: Worker()XMLDocument: XMLDocument()XMLHttpRequest: XMLHttpRequest()XMLHttpRequestEventTarget: XMLHttpRequestEventTarget()XMLHttpRequestUpload: XMLHttpRequestUpload()XMLSerializer: XMLSerializer()XPathEvaluator: XPathEvaluator()XPathExpression: XPathExpression()XPathResult: XPathResult()XSLTProcessor: XSLTProcessor()alert: alert()applicationCache: ApplicationCacheatob: atob()blur: ()btoa: btoa()c: undefinedcaches: CacheStoragecancelAnimationFrame: cancelAnimationFrame()cancelIdleCallback: cancelIdleCallback()captureEvents: captureEvents()chrome: ObjectclearInterval: clearInterval()clearTimeout: clearTimeout()clientInformation: Navigatorclose: ()closed: falseconfirm: confirm()console: ConsolecreateImageBitmap: createImageBitmap()crypto: CryptodecodeURI: decodeURI()decodeURIComponent: decodeURIComponent()defaultStatus: ""defaultstatus: ""devicePixelRatio: 2document: documentencodeURI: encodeURI()encodeURIComponent: encodeURIComponent()escape: escape()eval: eval()event: undefinedexternal: Objectfetch: fetch()find: find()focus: ()frameElement: nullframes: WindowgetComputedStyle: getComputedStyle()getMatchedCSSRules: getMatchedCSSRules()getSelection: getSelection()history: HistoryindexedDB: IDBFactoryinnerHeight: 1341innerWidth: 980isFinite: isFinite()isNaN: isNaN()isSecureContext: truelength: 0localStorage: Storagelocation: Locationlocationbar: BarPropmatchMedia: matchMedia()menubar: BarPropmoveBy: moveBy()moveTo: moveTo()name: ""navigator: NavigatoroffscreenBuffering: trueonabort: nullonanimationend: nullonanimationiteration: nullonanimationstart: nullonautocomplete: nullonautocompleteerror: nullonbeforeunload: nullonblur: nulloncancel: nulloncanplay: nulloncanplaythrough: nullonchange: nullonclick: nullonclose: nulloncontextmenu: nulloncuechange: nullondblclick: nullondevicemotion: nullondeviceorientation: nullondeviceorientationabsolute: nullondrag: nullondragend: nullondragenter: nullondragleave: nullondragover: nullondragstart: nullondrop: nullondurationchange: nullonemptied: nullonended: nullonerror: nullonfocus: nullonhashchange: nulloninput: nulloninvalid: nullonkeydown: nullonkeypress: nullonkeyup: nullonlanguagechange: nullonload: nullonloadeddata: nullonloadedmetadata: nullonloadstart: nullonmessage: nullonmousedown: nullonmouseenter: nullonmouseleave: nullonmousemove: nullonmouseout: nullonmouseover: nullonmouseup: nullonmousewheel: nullonoffline: nullononline: nullonpagehide: nullonpageshow: nullonpause: nullonplay: nullonplaying: nullonpopstate: nullonprogress: nullonratechange: nullonrejectionhandled: nullonreset: nullonresize: nullonscroll: nullonsearch: nullonseeked: nullonseeking: nullonselect: nullonshow: nullonstalled: nullonstorage: nullonsubmit: nullonsuspend: nullontimeupdate: nullontoggle: nullontransitionend: nullonunhandledrejection: nullonunload: nullonvolumechange: nullonwaiting: nullonwebkitanimationend: nullonwebkitanimationiteration: nullonwebkitanimationstart: nullonwebkittransitionend: nullonwheel: nullopen: open()openDatabase: openDatabase()opener: nullouterHeight: 547outerWidth: 400pageXOffset: 0pageYOffset: 0parent: WindowparseFloat: parseFloat()parseInt: parseInt()performance: Performancepersonalbar: BarProppostMessage: ()print: print()prompt: prompt()releaseEvents: releaseEvents()requestAnimationFrame: requestAnimationFrame()requestIdleCallback: requestIdleCallback()resizeBy: resizeBy()resizeTo: resizeTo()screen: ScreenscreenLeft: 0screenTop: 0screenX: 0screenY: 0scroll: scroll()scrollBy: scrollBy()scrollTo: scrollTo()scrollX: 0scrollY: 0scrollbars: BarPropself: WindowsessionStorage: StoragesetInterval: setInterval()setTimeout: setTimeout()speechSynthesis: SpeechSynthesisstatus: ""statusbar: BarPropstop: stop()styleMedia: StyleMediatoolbar: BarProptop: Windowundefined: undefinedunescape: unescape()webkitAudioContext: AudioContext()webkitCancelAnimationFrame: webkitCancelAnimationFrame()webkitCancelRequestAnimationFrame: webkitCancelRequestAnimationFrame()webkitIDBCursor: IDBCursor()webkitIDBDatabase: IDBDatabase()webkitIDBFactory: IDBFactory()webkitIDBIndex: IDBIndex()webkitIDBKeyRange: IDBKeyRange()webkitIDBObjectStore: IDBObjectStore()webkitIDBRequest: IDBRequest()webkitIDBTransaction: IDBTransaction()webkitIndexedDB: IDBFactorywebkitMediaStream: MediaStream()webkitOfflineAudioContext: OfflineAudioContext()webkitRTCPeerConnection: RTCPeerConnection()webkitRequestAnimationFrame: webkitRequestAnimationFrame()webkitRequestFileSystem: webkitRequestFileSystem()webkitResolveLocalFileSystemURL: webkitResolveLocalFileSystemURL()webkitSpeechGrammar: SpeechGrammar()webkitSpeechGrammarList: SpeechGrammarList()webkitSpeechRecognition: SpeechRecognition()webkitSpeechRecognitionError: SpeechRecognitionError()webkitSpeechRecognitionEvent: SpeechRecognitionEvent()webkitStorageInfo: DeprecatedStorageInfowebkitURL: URL()window: Window__proto__: Window
-
getEventListeners
getEventListeners(node) { [Command Line API] }
-
history
History {length: 1, state: null, scrollRestoration: "auto"}length: 1scrollRestoration: "auto"state: null__proto__: History
-
innerHeight
1341
-
innerWidth
980
-
inspect
inspect(object) { [Command Line API] }
-
isSecureContext
true
-
JSON
JSON {Symbol(Symbol.toStringTag): "JSON"}parse: parse()arguments: (...)caller: (...)length: 2name: "parse"__proto__: ()apply: apply()arguments: (...)get arguments: ThrowTypeError()set arguments: ThrowTypeError()bind: bind()call: call()caller: (...)get caller: ThrowTypeError()set caller: ThrowTypeError()constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()__proto__: Object<function scope><function scope>No Scopesstringify: stringify()arguments: (...)caller: (...)length: 3name: "stringify"__proto__: ()<function scope>Symbol(Symbol.toStringTag): "JSON"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()
-
keys
keys(object) { [Command Line API] }
-
localStorage
Storage {google_experiment_mod: "285", google_sra_enabled: "1", length: 2}
-
location
Location {hash: "", search: "", pathname: "/C:/Users/Axioo/Favorites/pub.html", port: "", hostname: ""…}ancestorOrigins: DOMStringListlength: 0__proto__: DOMStringListconstructor: DOMStringList()contains: contains()item: item()length: (...)get length: ()Symbol(Symbol.iterator): values()Symbol(Symbol.toStringTag): "DOMStringList"__proto__: Objectassign: ()arguments: nullcaller: nulllength: 1name: ""prototype: Object__proto__: ()<function scope>hash: ""host: ""hostname: ""href: "file:///C:/Users/Axioo/Favorites/pub.html"origin: "file://"pathname: "/C:/Users/Axioo/Favorites/pub.html"port: ""protocol: "file:"reload: reload()arguments: nullcaller: nulllength: 0name: "reload"__proto__: ()<function scope>replace: ()arguments: nullcaller: nulllength: 1name: ""prototype: Object__proto__: ()<function scope>search: ""toString: toString()arguments: nullcaller: nulllength: 0name: "toString"__proto__: ()<function scope>valueOf: valueOf()arguments: nullcaller: nulllength: 0name: "valueOf"__proto__: ()<function scope>__proto__: Locationconstructor: Location()Symbol(Symbol.toStringTag): "Location"__proto__: Object
-
locationbar
BarProp {visible: true}
-
monitor
monitor(fn) { [Command Line API] }
-
menubar
BarProp {visible: true}
-
Math
Math {E: 2.718281828459045, LN10: 2.302585092994046, LN2: 0.6931471805599453, LOG2E: 1.4426950408889634, LOG10E: 0.4342944819032518…}
-
-Via Internet Explorer:
navigator
{
   [functions]: ,
   __proto__: { },
   appCodeName: "Mozilla",
   appMinorVersion: "0",
   appName: "Netscape",
   appVersion: "5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET CLR 1.1.4322; .NET4.0C; .NET4.0E; rv:11.0) like Gecko",
   browserLanguage: "en-US",
   connectionSpeed: <Permission denied>,
   constructor: { },
   cookieEnabled: true,
   cpuClass: "x86",
   geolocation: { },
   language: "id-ID",
   maxTouchPoints: 0,
   mimeTypes: { },
   msManipulationViewsEnabled: false,
   msMaxTouchPoints: 0,
   msPointerEnabled: true,
   onLine: true,
   platform: "Win32",
   plugins: { },
   pointerEnabled: true,
   product: "Gecko",
   systemLanguage: "id-ID",
   userAgent: "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET CLR 1.1.4322; .NET4.0C; .NET4.0E; rv:11.0) like Gecko",
   userLanguage: "id-ID",
   vendor: "",
   webdriver: false
}
-Via Mozilla Firefox:
netscape
Object { , 1 more… }
-
navigator
Navigator { mozContacts: ContactManager, permissions: Permissions, mimeTypes: MimeTypeArray, plugins: PluginArray, doNotTrack: "unspecified", battery: BatteryManager, oscpu: "Windows NT 6.0", vendor: "", vendorSub: "", productSub: "20100101" }
-
outerWidth
1382
-
outerHeight
744
-Via Mozilla Firefox:
protocol
"file:"
-
pntr
"pe2"
-
personalbar
BarProp { visible: true }
-
performance
Performance { timing: PerformanceTiming, navigation: PerformanceNavigation, onresourcetimingbufferfull: null }
-
parent
Window → file:///C:/Users/Axioo/Favorites/pub.html
-
query_for_sanity
undefined
-
rand
31
-
str
"388bd40c"
-
statusbar
BarProp { visible: true }
-
-I.E:
screen
{
   [functions]: ,
   __proto__: { },
   availHeight: 728,
   availWidth: 1366,
   bufferDepth: 0,
   colorDepth: 24,
   constructor: { },
   deviceXDPI: 96,
   deviceYDPI: 96,
   fontSmoothingEnabled: true,
   height: 768,
   logicalXDPI: 96,
   logicalYDPI: 96,
   pixelDepth: 24,
   systemXDPI: 96,
   systemYDPI: 96,
   width: 1366
}
-
Screen
{
   [functions]: ,
   __proto__: { },
   prototype: { }
}
-
screenLeft
391
-
screenTop
189
-
screenX
383
-
screenY
50
-
self
{
   [functions]: ,
   $_: { },
   __BROWSERTOOLS_CONSOLE: { },
   __BROWSERTOOLS_DEBUGGER: { },
   __BROWSERTOOLS_DOMEXPLORER_ADDED: true,
   __BROWSERTOOLS_EMULATIONTOOLS_ADDED: { },
   __BROWSERTOOLS_MEMORYANALYZER_ADDED: { },
   __proto__: { },
   ActiveXObject: undefined,
   AesGcmEncryptResult: { },
   ANGLE_instanced_arrays: { },
   AnimationEvent: { },
   animationStartTime: 2334197.706975824,
   applicationCache: { },
   ApplicationCache: { },
   Attr: { },
   AudioTrack: { },
   AudioTrackList: { },
   BeforeUnloadEvent: { },
   BookmarkCollection: { },
   c: undefined,
   CanvasGradient: { },
   CanvasPattern: { },
   CanvasRenderingContext2D: { },
   CDATASection: { },
   CharacterData: { },
   clientInformation: { },
   ClientRect: { },
   ClientRectList: { },
   clipboardData: { },
   closed: false,
   CloseEvent: { },
   Comment: { },
   CompositionEvent: { },
   console: { },
   Console: { },
   constructor: { },
   ControlRangeCollection: { },
   Coordinates: { },
   Crypto: { },
   CryptoOperation: { },
   CSSFontFaceRule: { },
   CSSImportRule: { },
   CSSKeyframeRule: { },
   CSSKeyframesRule: { },
   CSSMediaRule: { },
   CSSNamespaceRule: { },
   CSSPageRule: { },
   CSSRule: { },
   CSSRuleList: { },
   CSSStyleDeclaration: { },
   CSSStyleRule: { },
   CSSStyleSheet: { },
   CustomEvent: { },
   DataTransfer: { },
   Debug: { },
   defaultStatus: "",
   devicePixelRatio: 1,
   Document: { },
   document: { },
   DocumentFragment: { },
   DocumentType: { },
   DOMError: { },
   DOMException: { },
   DOMImplementation: { },
   DOMSettableTokenList: { },
   DOMStringList: { },
   DOMStringMap: { },
   DOMTokenList: { },
   doNotTrack: null,
   DragEvent: { },
   Element: { },
   ErrorEvent: { },
   event: undefined,
   Event: { },
   EventException: { },
   EXT_texture_filter_anisotropic: { },
   external: { },
   File: { },
   FileList: { },
   FocusEvent: { },
   frameElement: null,
   frames: { },
   Geolocation: { },
   history: { },
   History: { },
   HTMLAllCollection: { },
   HTMLAnchorElement: { },
   HTMLAppletElement: { },
   HTMLAreaElement: { },
   HTMLAreasCollection: { },
   HTMLAudioElement: { },
   HTMLBaseElement: { },
   HTMLBaseFontElement: { },
   HTMLBGSoundElement: { },
   HTMLBlockElement: { },
   HTMLBodyElement: { },
   HTMLBRElement: { },
   HTMLButtonElement: { },
   HTMLCanvasElement: { },
   HTMLCollection: { },
   HTMLDataListElement: { },
   HTMLDDElement: { },
   HTMLDirectoryElement: { },
   HTMLDivElement: { },
   HTMLDListElement: { },
   HTMLDocument: { },
   HTMLDTElement: { },
   HTMLElement: { },
   HTMLEmbedElement: { },
   HTMLFieldSetElement: { },
   HTMLFontElement: { },
   HTMLFormElement: { },
   HTMLFrameElement: { },
   HTMLFrameSetElement: { },
   HTMLHeadElement: { },
   HTMLHeadingElement: { },
   HTMLHRElement: { },
   HTMLHtmlElement: { },
   HTMLIFrameElement: { },
   HTMLImageElement: { },
   HTMLInputElement: { },
   HTMLIsIndexElement: { },
   HTMLLabelElement: { },
   HTMLLegendElement: { },
   HTMLLIElement: { },
   HTMLLinkElement: { },
   HTMLMapElement: { },
   HTMLMarqueeElement: { },
   HTMLMediaElement: { },
   HTMLMenuElement: { },
   HTMLMetaElement: { },
   HTMLModElement: { },
   HTMLNextIdElement: { },
   HTMLObjectElement: { },
   HTMLOListElement: { },
   HTMLOptGroupElement: { },
   HTMLOptionElement: { },
   HTMLParagraphElement: { },
   HTMLParamElement: { },
   HTMLPhraseElement: { },
   HTMLPreElement: { },
   HTMLProgressElement: { },
   HTMLQuoteElement: { },
   HTMLScriptElement: { },
   HTMLSelectElement: { },
   HTMLSourceElement: { },
   HTMLSpanElement: { },
   HTMLStyleElement: { },
   HTMLTableCaptionElement: { },
   HTMLTableCellElement: { },
   HTMLTableColElement: { },
   HTMLTableDataCellElement: { },
   HTMLTableElement: { },
   HTMLTableHeaderCellElement: { },
   HTMLTableRowElement: { },
   HTMLTableSectionElement: { },
   HTMLTextAreaElement: { },
   HTMLTitleElement: { },
   HTMLTrackElement: { },
   HTMLUListElement: { },
   HTMLUnknownElement: { },
   HTMLVideoElement: { },
   IDBCursor: { },
   IDBCursorWithValue: { },
   IDBDatabase: { },
   IDBFactory: { },
   IDBIndex: { },
   IDBKeyRange: { },
   IDBObjectStore: { },
   IDBOpenDBRequest: { },
   IDBRequest: { },
   IDBTransaction: { },
   IDBVersionChangeEvent: { },
   ImageData: { },
   indexedDB: undefined,
   Infinity: Infinity,
   innerHeight: 226,
   innerWidth: 828,
   Intl: { },
   JSON: { },
   Key: { },
   KeyboardEvent: { },
   KeyOperation: { },
   KeyPair: { },
   length: 0,
   localStorage: undefined,
   Location: { },
   location: { },
   Math: { },
   maxConnectionsPerServer: 6,
   MediaError: { },
   MediaList: { },
   MediaQueryList: { },
   MessageEvent: { },
   MessagePort: { },
   MimeType: { },
   MimeTypeArray: { },
   MouseEvent: { },
   MouseWheelEvent: { },
   msAnimationStartTime: 2334197.706975824,
   MSBehaviorUrnsCollection: { },
   MSCompatibleInfo: { },
   MSCompatibleInfoCollection: { },
   msCrypto: { },
   MSCSSProperties: { },
   MSCSSRuleList: { },
   MSCurrentStyleCSSProperties: { },
   MSEventObj: { },
   MSGestureEvent: { },
   msIndexedDB: undefined,
   MSInputMethodContext: { },
   MSManipulationEvent: { },
   MSMimeTypesCollection: { },
   MSPluginsCollection: { },
   MSPointerEvent: { },
   MSRangeCollection: { },
   MSSiteModeEvent: { },
   MSStream: { },
   MSStyleCSSProperties: { },
   MutationEvent: { },
   MutationRecord: { },
   name: "",
   NamedNodeMap: { },
   NaN: NaN,
   navigator: { },
   Navigator: { },
   Node: { },
   NodeFilter: { },
   NodeIterator: { },
   NodeList: { },
   OES_element_index_uint: { },
   OES_standard_derivatives: { },
   OES_texture_float: { },
   OES_texture_float_linear: { },
   offscreenBuffering: "auto",
   onabort: null,
   onafterprint: null,
   onbeforeprint: null,
   onbeforeunload: null,
   onblur: null,
   oncanplay: null,
   oncanplaythrough: null,
   onchange: null,
   onclick: null,
   oncontextmenu: null,
   ondblclick: null,
   ondrag: null,
   ondragend: null,
   ondragenter: null,
   ondragleave: null,
   ondragover: null,
   ondragstart: null,
   ondrop: null,
   ondurationchange: null,
   onemptied: null,
   onended: null,
   onerror: null,
   onfocus: null,
   onfocusin: null,
   onfocusout: null,
   onhashchange: null,
   onhelp: null,
   oninput: null,
   onkeydown: null,
   onkeypress: null,
   onkeyup: null,
   onload: null,
   onloadeddata: null,
   onloadedmetadata: null,
   onloadstart: null,
   onmessage: null,
   onmousedown: null,
   onmouseenter: null,
   onmouseleave: null,
   onmousemove: null,
   onmouseout: null,
   onmouseover: null,
   onmouseup: null,
   onmousewheel: null,
   onmsgesturechange: null,
   onmsgesturedoubletap: null,
   onmsgestureend: null,
   onmsgesturehold: null,
   onmsgesturestart: null,
   onmsgesturetap: null,
   onmsinertiastart: null,
   onmspointercancel: null,
   onmspointerdown: null,
   onmspointerenter: null,
   onmspointerleave: null,
   onmspointermove: null,
   onmspointerout: null,
   onmspointerover: null,
   onmspointerup: null,
   onoffline: null,
   ononline: null,
   onpagehide: null,
   onpageshow: null,
   onpause: null,
   onplay: null,
   onplaying: null,
   onpointercancel: null,
   onpointerdown: null,
   onpointerenter: null,
   onpointerleave: null,
   onpointermove: null,
   onpointerout: null,
   onpointerover: null,
   onpointerup: null,
   onpopstate: null,
   onprogress: null,
   onratechange: null,
   onreadystatechange: null,
   onreset: null,
   onresize: null,
   onscroll: null,
   onseeked: null,
   onseeking: null,
   onselect: null,
   onstalled: null,
   onstorage: null,
   onsubmit: null,
   onsuspend: null,
   ontimeupdate: null,
   onunload: null,
   onvolumechange: null,
   onwaiting: null,
   opener: undefined,
   outerHeight: 600,
   outerWidth: 844,
   PageTransitionEvent: { },
   pageXOffset: 0,
   pageYOffset: 0,
   parent: { },
   performance: { },
   Performance: { },
   PerformanceEntry: { },
   PerformanceMark: { },
   PerformanceMeasure: { },
   PerformanceNavigation: { },
   PerformanceNavigationTiming: { },
   PerformanceResourceTiming: { },
   PerformanceTiming: { },
   Plugin: { },
   PluginArray: { },
   PointerEvent: { },
   PopStateEvent: { },
   Position: { },
   PositionError: { },
   ProcessingInstruction: { },
   ProgressEvent: { },
   Range: { },
   RangeException: { },
   screen: { },
   Screen: { },
   screenLeft: 391,
   screenTop: 189,
   screenX: 383,
   screenY: 50,
   Selection: { },
   self: { },
   sessionStorage: undefined,
   status: "",
   Storage: { },
   StorageEvent: { },
   styleMedia: { },
   StyleMedia: { },
   StyleSheet: { },
   StyleSheetList: { },
   StyleSheetPageList: { },
   SubtleCrypto: { },
   SVGAElement: { },
   SVGAngle: { },
   SVGAnimatedAngle: { },
   SVGAnimatedBoolean: { },
   SVGAnimatedEnumeration: { },
   SVGAnimatedInteger: { },
   SVGAnimatedLength: { },
   SVGAnimatedLengthList: { },
   SVGAnimatedNumber: { },
   SVGAnimatedNumberList: { },
   SVGAnimatedPreserveAspectRatio: { },
   SVGAnimatedRect: { },
   SVGAnimatedString: { },
   SVGAnimatedTransformList: { },
   SVGCircleElement: { },
   SVGClipPathElement: { },
   SVGComponentTransferFunctionElement: { },
   SVGDefsElement: { },
   SVGDescElement: { },
   SVGElement: { },
   SVGElementInstance: { },
   SVGElementInstanceList: { },
   SVGEllipseElement: { },
   SVGException: { },
   SVGFEBlendElement: { },
   SVGFEColorMatrixElement: { },
   SVGFEComponentTransferElement: { },
   SVGFECompositeElement: { },
   SVGFEConvolveMatrixElement: { },
   SVGFEDiffuseLightingElement: { },
   SVGFEDisplacementMapElement: { },
   SVGFEDistantLightElement: { },
   SVGFEFloodElement: { },
   SVGFEFuncAElement: { },
   SVGFEFuncBElement: { },
   SVGFEFuncGElement: { },
   SVGFEFuncRElement: { },
   SVGFEGaussianBlurElement: { },
   SVGFEImageElement: { },
   SVGFEMergeElement: { },
   SVGFEMergeNodeElement: { },
   SVGFEMorphologyElement: { },
   SVGFEOffsetElement: { },
   SVGFEPointLightElement: { },
   SVGFESpecularLightingElement: { },
   SVGFESpotLightElement: { },
   SVGFETileElement: { },
   SVGFETurbulenceElement: { },
   SVGFilterElement: { },
   SVGGElement: { },
   SVGGradientElement: { },
   SVGImageElement: { },
   SVGLength: { },
   SVGLengthList: { },
   SVGLinearGradientElement: { },
   SVGLineElement: { },
   SVGMarkerElement: { },
   SVGMaskElement: { },
   SVGMatrix: { },
   SVGMetadataElement: { },
   SVGNumber: { },
   SVGNumberList: { },
   SVGPathElement: { },
   SVGPathSeg: { },
   SVGPathSegArcAbs: { },
   SVGPathSegArcRel: { },
   SVGPathSegClosePath: { },
   SVGPathSegCurvetoCubicAbs: { },
   SVGPathSegCurvetoCubicRel: { },
   SVGPathSegCurvetoCubicSmoothAbs: { },
   SVGPathSegCurvetoCubicSmoothRel: { },
   SVGPathSegCurvetoQuadraticAbs: { },
   SVGPathSegCurvetoQuadraticRel: { },
   SVGPathSegCurvetoQuadraticSmoothAbs: { },
   SVGPathSegCurvetoQuadraticSmoothRel: { },
   SVGPathSegLinetoAbs: { },
   SVGPathSegLinetoHorizontalAbs: { },
   SVGPathSegLinetoHorizontalRel: { },
   SVGPathSegLinetoRel: { },
   SVGPathSegLinetoVerticalAbs: { },
   SVGPathSegLinetoVerticalRel: { },
   SVGPathSegList: { },
   SVGPathSegMovetoAbs: { },
   SVGPathSegMovetoRel: { },
   SVGPatternElement: { },
   SVGPoint: { },
   SVGPointList: { },
   SVGPolygonElement: { },
   SVGPolylineElement: { },
   SVGPreserveAspectRatio: { },
   SVGRadialGradientElement: { },
   SVGRect: { },
   SVGRectElement: { },
   SVGScriptElement: { },
   SVGStopElement: { },
   SVGStringList: { },
   SVGStyleElement: { },
   SVGSVGElement: { },
   SVGSwitchElement: { },
   SVGSymbolElement: { },
   SVGTextContentElement: { },
   SVGTextElement: { },
   SVGTextPathElement: { },
   SVGTextPositioningElement: { },
   SVGTitleElement: { },
   SVGTransform: { },
   SVGTransformList: { },
   SVGTSpanElement: { },
   SVGUnitTypes: { },
   SVGUseElement: { },
   SVGViewElement: { },
   SVGZoomAndPan: { },
   SVGZoomEvent: { },
   Text: { },
   TextEvent: { },
   TextMetrics: { },
   TextRange: { },
   TextRangeCollection: { },
   TextTrack: { },
   TextTrackCueList: { },
   TextTrackList: { },
   TimeRanges: { },
   top: { },
   TrackEvent: { },
   TransitionEvent: { },
   TreeWalker: { },
   TsCmcObj: { },
   UIEvent: { },
   undefined: undefined,
   URL: { },
   ValidityState: { },
   WEBGL_compressed_texture_s3tc: { },
   WEBGL_debug_renderer_info: { },
   WebGLActiveInfo: { },
   WebGLBuffer: { },
   WebGLFramebuffer: { },
   WebGLObject: { },
   WebGLProgram: { },
   WebGLRenderbuffer: { },
   WebGLRenderingContext: { },
   WebGLShader: { },
   WebGLShaderPrecisionFormat: { },
   WebGLTexture: { },
   WebGLUniformLocation: { },
   WheelEvent: { },
   window: { },
   Window: { },
   XMLDocument: { },
   XMLHttpRequestEventTarget: { }
}
-
__proto__
{
   [functions]: ,
   __proto__: { },
   animationStartTime: <Permission denied>,
   applicationCache: <Permission denied>,
   clientInformation: <Permission denied>,
   clipboardData: <Permission denied>,
   closed: <Permission denied>,
   console: <Permission denied>,
   constructor: { },
   defaultStatus: <Permission denied>,
   devicePixelRatio: <Permission denied>,
   document: <Permission denied>,
   doNotTrack: <Permission denied>,
   event: <Permission denied>,
   external: <Permission denied>,
   frameElement: <Permission denied>,
   frames: <Permission denied>,
   history: <Permission denied>,
   indexedDB: <Permission denied>,
   innerHeight: <Permission denied>,
   innerWidth: <Permission denied>,
   length: <Permission denied>,
   localStorage: <Permission denied>,
   location: <Permission denied>,
   maxConnectionsPerServer: <Permission denied>,
   msAnimationStartTime: <Permission denied>,
   msCrypto: <Permission denied>,
   msIndexedDB: <Permission denied>,
   name: <Permission denied>,
   navigator: <Permission denied>,
   offscreenBuffering: <Permission denied>,
   onabort: <Permission denied>,
   onafterprint: <Permission denied>,
   onbeforeprint: <Permission denied>,
   onbeforeunload: <Permission denied>,
   onblur: <Permission denied>,
   oncanplay: <Permission denied>,
   oncanplaythrough: <Permission denied>,
   onchange: <Permission denied>,
   onclick: <Permission denied>,
   oncontextmenu: <Permission denied>,
   ondblclick: <Permission denied>,
   ondrag: <Permission denied>,
   ondragend: <Permission denied>,
   ondragenter: <Permission denied>,
   ondragleave: <Permission denied>,
   ondragover: <Permission denied>,
   ondragstart: <Permission denied>,
   ondrop: <Permission denied>,
   ondurationchange: <Permission denied>,
   onemptied: <Permission denied>,
   onended: <Permission denied>,
   onerror: <Permission denied>,
   onfocus: <Permission denied>,
   onfocusin: <Permission denied>,
   onfocusout: <Permission denied>,
   onhashchange: <Permission denied>,
   onhelp: <Permission denied>,
   oninput: <Permission denied>,
   onkeydown: <Permission denied>,
   onkeypress: <Permission denied>,
   onkeyup: <Permission denied>,
   onload: <Permission denied>,
   onloadeddata: <Permission denied>,
   onloadedmetadata: <Permission denied>,
   onloadstart: <Permission denied>,
   onmessage: <Permission denied>,
   onmousedown: <Permission denied>,
   onmouseenter: <Permission denied>,
   onmouseleave: <Permission denied>,
   onmousemove: <Permission denied>,
   onmouseout: <Permission denied>,
   onmouseover: <Permission denied>,
   onmouseup: <Permission denied>,
   onmousewheel: <Permission denied>,
   onmsgesturechange: <Permission denied>,
   onmsgesturedoubletap: <Permission denied>,
   onmsgestureend: <Permission denied>,
   onmsgesturehold: <Permission denied>,
   onmsgesturestart: <Permission denied>,
   onmsgesturetap: <Permission denied>,
   onmsinertiastart: <Permission denied>,
   onmspointercancel: <Permission denied>,
   onmspointerdown: <Permission denied>,
   onmspointerenter: <Permission denied>,
   onmspointerleave: <Permission denied>,
   onmspointermove: <Permission denied>,
   onmspointerout: <Permission denied>,
   onmspointerover: <Permission denied>,
   onmspointerup: <Permission denied>,
   onoffline: <Permission denied>,
   ononline: <Permission denied>,
   onpagehide: <Permission denied>,
   onpageshow: <Permission denied>,
   onpause: <Permission denied>,
   onplay: <Permission denied>,
   onplaying: <Permission denied>,
   onpointercancel: <Permission denied>,
   onpointerdown: <Permission denied>,
   onpointerenter: <Permission denied>,
   onpointerleave: <Permission denied>,
   onpointermove: <Permission denied>,
   onpointerout: <Permission denied>,
   onpointerover: <Permission denied>,
   onpointerup: <Permission denied>,
   onpopstate: <Permission denied>,
   onprogress: <Permission denied>,
   onratechange: <Permission denied>,
   onreadystatechange: <Permission denied>,
   onreset: <Permission denied>,
   onresize: <Permission denied>,
   onscroll: <Permission denied>,
   onseeked: <Permission denied>,
   onseeking: <Permission denied>,
   onselect: <Permission denied>,
   onstalled: <Permission denied>,
   onstorage: <Permission denied>,
   onsubmit: <Permission denied>,
   onsuspend: <Permission denied>,
   ontimeupdate: <Permission denied>,
   onunload: <Permission denied>,
   onvolumechange: <Permission denied>,
   onwaiting: <Permission denied>,
   opener: <Permission denied>,
   outerHeight: <Permission denied>,
   outerWidth: <Permission denied>,
   pageXOffset: <Permission denied>,
   pageYOffset: <Permission denied>,
   parent: <Permission denied>,
   performance: <Permission denied>,
   screen: <Permission denied>,
   screenLeft: <Permission denied>,
   screenTop: <Permission denied>,
   screenX: <Permission denied>,
   screenY: <Permission denied>,
   self: <Permission denied>,
   sessionStorage: <Permission denied>,
   status: <Permission denied>,
   styleMedia: <Permission denied>,
   top: <Permission denied>,
   window: <Permission denied>
}
-
ActiveXObject
undefined
-
TextEvent
{
   [functions]: ,
   __proto__: { },
   DOM_INPUT_METHOD_DROP: 3,
   DOM_INPUT_METHOD_HANDWRITING: 6,
   DOM_INPUT_METHOD_IME: 4,
   DOM_INPUT_METHOD_KEYBOARD: 1,
   DOM_INPUT_METHOD_MULTIMODAL: 8,
   DOM_INPUT_METHOD_OPTION: 5,
   DOM_INPUT_METHOD_PASTE: 2,
   DOM_INPUT_METHOD_SCRIPT: 9,
   DOM_INPUT_METHOD_UNKNOWN: 0,
   DOM_INPUT_METHOD_VOICE: 7,
   prototype: { }
}
-
TextTrack
{
   [functions]: ,
   __proto__: { },
   DISABLED: 0,
   ERROR: 3,
   HIDDEN: 1,
   LOADED: 2,
   LOADING: 1,
   NONE: 0,
   prototype: { },
   SHOWING: 2
}
-
this
{
   [functions]: ,
   $_: { },
   __BROWSERTOOLS_CONSOLE: { },
   __BROWSERTOOLS_DEBUGGER: { },
   __BROWSERTOOLS_DOMEXPLORER_ADDED: true,
   __BROWSERTOOLS_EMULATIONTOOLS_ADDED: { },
   __BROWSERTOOLS_MEMORYANALYZER_ADDED: { },
   __proto__: { },
   ActiveXObject: undefined,
   AesGcmEncryptResult: { },
   ANGLE_instanced_arrays: { },
   AnimationEvent: { },
   animationStartTime: 3254380.3600618015,
   applicationCache: { },
   ApplicationCache: { },
   Attr: { },
   AudioTrack: { },
   AudioTrackList: { },
   BeforeUnloadEvent: { },
   BookmarkCollection: { },
   c: undefined,
   CanvasGradient: { },
   CanvasPattern: { },
   CanvasRenderingContext2D: { },
   CDATASection: { },
   CharacterData: { },
   clientInformation: { },
   ClientRect: { },
   ClientRectList: { },
   clipboardData: { },
   closed: false,
   CloseEvent: { },
   Comment: { },
   CompositionEvent: { },
   console: { },
   Console: { },
   constructor: { },
   ControlRangeCollection: { },
   Coordinates: { },
   Crypto: { },
   CryptoOperation: { },
   CSSFontFaceRule: { },
   CSSImportRule: { },
   CSSKeyframeRule: { },
   CSSKeyframesRule: { },
   CSSMediaRule: { },
   CSSNamespaceRule: { },
   CSSPageRule: { },
   CSSRule: { },
   CSSRuleList: { },
   CSSStyleDeclaration: { },
   CSSStyleRule: { },
   CSSStyleSheet: { },
   CustomEvent: { },
   DataTransfer: { },
   Debug: { },
   defaultStatus: "",
   devicePixelRatio: 1,
   Document: { },
   document: { },
   DocumentFragment: { },
   DocumentType: { },
   DOMError: { },
   DOMException: { },
   DOMImplementation: { },
   DOMSettableTokenList: { },
   DOMStringList: { },
   DOMStringMap: { },
   DOMTokenList: { },
   doNotTrack: null,
   DragEvent: { },
   Element: { },
   ErrorEvent: { },
   event: undefined,
   Event: { },
   EventException: { },
   EXT_texture_filter_anisotropic: { },
   external: { },
   File: { },
   FileList: { },
   FocusEvent: { },
   frameElement: null,
   frames: { },
   Geolocation: { },
   history: { },
   History: { },
   HTMLAllCollection: { },
   HTMLAnchorElement: { },
   HTMLAppletElement: { },
   HTMLAreaElement: { },
   HTMLAreasCollection: { },
   HTMLAudioElement: { },
   HTMLBaseElement: { },
   HTMLBaseFontElement: { },
   HTMLBGSoundElement: { },
   HTMLBlockElement: { },
   HTMLBodyElement: { },
   HTMLBRElement: { },
   HTMLButtonElement: { },
   HTMLCanvasElement: { },
   HTMLCollection: { },
   HTMLDataListElement: { },
   HTMLDDElement: { },
   HTMLDirectoryElement: { },
   HTMLDivElement: { },
   HTMLDListElement: { },
   HTMLDocument: { },
   HTMLDTElement: { },
   HTMLElement: { },
   HTMLEmbedElement: { },
   HTMLFieldSetElement: { },
   HTMLFontElement: { },
   HTMLFormElement: { },
   HTMLFrameElement: { },
   HTMLFrameSetElement: { },
   HTMLHeadElement: { },
   HTMLHeadingElement: { },
   HTMLHRElement: { },
   HTMLHtmlElement: { },
   HTMLIFrameElement: { },
   HTMLImageElement: { },
   HTMLInputElement: { },
   HTMLIsIndexElement: { },
   HTMLLabelElement: { },
   HTMLLegendElement: { },
   HTMLLIElement: { },
   HTMLLinkElement: { },
   HTMLMapElement: { },
   HTMLMarqueeElement: { },
   HTMLMediaElement: { },
   HTMLMenuElement: { },
   HTMLMetaElement: { },
   HTMLModElement: { },
   HTMLNextIdElement: { },
   HTMLObjectElement: { },
   HTMLOListElement: { },
   HTMLOptGroupElement: { },
   HTMLOptionElement: { },
   HTMLParagraphElement: { },
   HTMLParamElement: { },
   HTMLPhraseElement: { },
   HTMLPreElement: { },
   HTMLProgressElement: { },
   HTMLQuoteElement: { },
   HTMLScriptElement: { },
   HTMLSelectElement: { },
   HTMLSourceElement: { },
   HTMLSpanElement: { },
   HTMLStyleElement: { },
   HTMLTableCaptionElement: { },
   HTMLTableCellElement: { },
   HTMLTableColElement: { },
   HTMLTableDataCellElement: { },
   HTMLTableElement: { },
   HTMLTableHeaderCellElement: { },
   HTMLTableRowElement: { },
   HTMLTableSectionElement: { },
   HTMLTextAreaElement: { },
   HTMLTitleElement: { },
   HTMLTrackElement: { },
   HTMLUListElement: { },
   HTMLUnknownElement: { },
   HTMLVideoElement: { },
   IDBCursor: { },
   IDBCursorWithValue: { },
   IDBDatabase: { },
   IDBFactory: { },
   IDBIndex: { },
   IDBKeyRange: { },
   IDBObjectStore: { },
   IDBOpenDBRequest: { },
   IDBRequest: { },
   IDBTransaction: { },
   IDBVersionChangeEvent: { },
   ImageData: { },
   indexedDB: undefined,
   Infinity: Infinity,
   innerHeight: 226,
   innerWidth: 828,
   Intl: { },
   JSON: { },
   Key: { },
   KeyboardEvent: { },
   KeyOperation: { },
   KeyPair: { },
   length: 0,
   localStorage: undefined,
   Location: { },
   location: { },
   Math: { },
   maxConnectionsPerServer: 6,
   MediaError: { },
   MediaList: { },
   MediaQueryList: { },
   MessageEvent: { },
   MessagePort: { },
   MimeType: { },
   MimeTypeArray: { },
   MouseEvent: { },
   MouseWheelEvent: { },
   msAnimationStartTime: 3254380.3600618015,
   MSBehaviorUrnsCollection: { },
   MSCompatibleInfo: { },
   MSCompatibleInfoCollection: { },
   msCrypto: { },
   MSCSSProperties: { },
   MSCSSRuleList: { },
   MSCurrentStyleCSSProperties: { },
   MSEventObj: { },
   MSGestureEvent: { },
   msIndexedDB: undefined,
   MSInputMethodContext: { },
   MSManipulationEvent: { },
   MSMimeTypesCollection: { },
   MSPluginsCollection: { },
   MSPointerEvent: { },
   MSRangeCollection: { },
   MSSiteModeEvent: { },
   MSStream: { },
   MSStyleCSSProperties: { },
   MutationEvent: { },
   MutationRecord: { },
   name: "",
   NamedNodeMap: { },
   NaN: NaN,
   navigator: { },
   Navigator: { },
   Node: { },
   NodeFilter: { },
   NodeIterator: { },
   NodeList: { },
   OES_element_index_uint: { },
   OES_standard_derivatives: { },
   OES_texture_float: { },
   OES_texture_float_linear: { },
   offscreenBuffering: "auto",
   onabort: null,
   onafterprint: null,
   onbeforeprint: null,
   onbeforeunload: null,
   onblur: null,
   oncanplay: null,
   oncanplaythrough: null,
   onchange: null,
   onclick: null,
   oncontextmenu: null,
   ondblclick: null,
   ondrag: null,
   ondragend: null,
   ondragenter: null,
   ondragleave: null,
   ondragover: null,
   ondragstart: null,
   ondrop: null,
   ondurationchange: null,
   onemptied: null,
   onended: null,
   onerror: null,
   onfocus: null,
   onfocusin: null,
   onfocusout: null,
   onhashchange: null,
   onhelp: null,
   oninput: null,
   onkeydown: null,
   onkeypress: null,
   onkeyup: null,
   onload: null,
   onloadeddata: null,
   onloadedmetadata: null,
   onloadstart: null,
   onmessage: null,
   onmousedown: null,
   onmouseenter: null,
   onmouseleave: null,
   onmousemove: null,
   onmouseout: null,
   onmouseover: null,
   onmouseup: null,
   onmousewheel: null,
   onmsgesturechange: null,
   onmsgesturedoubletap: null,
   onmsgestureend: null,
   onmsgesturehold: null,
   onmsgesturestart: null,
   onmsgesturetap: null,
   onmsinertiastart: null,
   onmspointercancel: null,
   onmspointerdown: null,
   onmspointerenter: null,
   onmspointerleave: null,
   onmspointermove: null,
   onmspointerout: null,
   onmspointerover: null,
   onmspointerup: null,
   onoffline: null,
   ononline: null,
   onpagehide: null,
   onpageshow: null,
   onpause: null,
   onplay: null,
   onplaying: null,
   onpointercancel: null,
   onpointerdown: null,
   onpointerenter: null,
   onpointerleave: null,
   onpointermove: null,
   onpointerout: null,
   onpointerover: null,
   onpointerup: null,
   onpopstate: null,
   onprogress: null,
   onratechange: null,
   onreadystatechange: null,
   onreset: null,
   onresize: null,
   onscroll: null,
   onseeked: null,
   onseeking: null,
   onselect: null,
   onstalled: null,
   onstorage: null,
   onsubmit: null,
   onsuspend: null,
   ontimeupdate: null,
   onunload: null,
   onvolumechange: null,
   onwaiting: null,
   opener: undefined,
   outerHeight: 600,
   outerWidth: 844,
   PageTransitionEvent: { },
   pageXOffset: 0,
   pageYOffset: 0,
   parent: { },
   performance: { },
   Performance: { },
   PerformanceEntry: { },
   PerformanceMark: { },
   PerformanceMeasure: { },
   PerformanceNavigation: { },
   PerformanceNavigationTiming: { },
   PerformanceResourceTiming: { },
   PerformanceTiming: { },
   Plugin: { },
   PluginArray: { },
   PointerEvent: { },
   PopStateEvent: { },
   Position: { },
   PositionError: { },
   ProcessingInstruction: { },
   ProgressEvent: { },
   Range: { },
   RangeException: { },
   screen: { },
   Screen: { },
   screenLeft: 391,
   screenTop: 189,
   screenX: 383,
   screenY: 50,
   Selection: { },
   self: { },
   sessionStorage: undefined,
   status: "",
   Storage: { },
   StorageEvent: { },
   styleMedia: { },
   StyleMedia: { },
   StyleSheet: { },
   StyleSheetList: { },
   StyleSheetPageList: { },
   SubtleCrypto: { },
   SVGAElement: { },
   SVGAngle: { },
   SVGAnimatedAngle: { },
   SVGAnimatedBoolean: { },
   SVGAnimatedEnumeration: { },
   SVGAnimatedInteger: { },
   SVGAnimatedLength: { },
   SVGAnimatedLengthList: { },
   SVGAnimatedNumber: { },
   SVGAnimatedNumberList: { },
   SVGAnimatedPreserveAspectRatio: { },
   SVGAnimatedRect: { },
   SVGAnimatedString: { },
   SVGAnimatedTransformList: { },
   SVGCircleElement: { },
   SVGClipPathElement: { },
   SVGComponentTransferFunctionElement: { },
   SVGDefsElement: { },
   SVGDescElement: { },
   SVGElement: { },
   SVGElementInstance: { },
   SVGElementInstanceList: { },
   SVGEllipseElement: { },
   SVGException: { },
   SVGFEBlendElement: { },
   SVGFEColorMatrixElement: { },
   SVGFEComponentTransferElement: { },
   SVGFECompositeElement: { },
   SVGFEConvolveMatrixElement: { },
   SVGFEDiffuseLightingElement: { },
   SVGFEDisplacementMapElement: { },
   SVGFEDistantLightElement: { },
   SVGFEFloodElement: { },
   SVGFEFuncAElement: { },
   SVGFEFuncBElement: { },
   SVGFEFuncGElement: { },
   SVGFEFuncRElement: { },
   SVGFEGaussianBlurElement: { },
   SVGFEImageElement: { },
   SVGFEMergeElement: { },
   SVGFEMergeNodeElement: { },
   SVGFEMorphologyElement: { },
   SVGFEOffsetElement: { },
   SVGFEPointLightElement: { },
   SVGFESpecularLightingElement: { },
   SVGFESpotLightElement: { },
   SVGFETileElement: { },
   SVGFETurbulenceElement: { },
   SVGFilterElement: { },
   SVGGElement: { },
   SVGGradientElement: { },
   SVGImageElement: { },
   SVGLength: { },
   SVGLengthList: { },
   SVGLinearGradientElement: { },
   SVGLineElement: { },
   SVGMarkerElement: { },
   SVGMaskElement: { },
   SVGMatrix: { },
   SVGMetadataElement: { },
   SVGNumber: { },
   SVGNumberList: { },
   SVGPathElement: { },
   SVGPathSeg: { },
   SVGPathSegArcAbs: { },
   SVGPathSegArcRel: { },
   SVGPathSegClosePath: { },
   SVGPathSegCurvetoCubicAbs: { },
   SVGPathSegCurvetoCubicRel: { },
   SVGPathSegCurvetoCubicSmoothAbs: { },
   SVGPathSegCurvetoCubicSmoothRel: { },
   SVGPathSegCurvetoQuadraticAbs: { },
   SVGPathSegCurvetoQuadraticRel: { },
   SVGPathSegCurvetoQuadraticSmoothAbs: { },
   SVGPathSegCurvetoQuadraticSmoothRel: { },
   SVGPathSegLinetoAbs: { },
   SVGPathSegLinetoHorizontalAbs: { },
   SVGPathSegLinetoHorizontalRel: { },
   SVGPathSegLinetoRel: { },
   SVGPathSegLinetoVerticalAbs: { },
   SVGPathSegLinetoVerticalRel: { },
   SVGPathSegList: { },
   SVGPathSegMovetoAbs: { },
   SVGPathSegMovetoRel: { },
   SVGPatternElement: { },
   SVGPoint: { },
   SVGPointList: { },
   SVGPolygonElement: { },
   SVGPolylineElement: { },
   SVGPreserveAspectRatio: { },
   SVGRadialGradientElement: { },
   SVGRect: { },
   SVGRectElement: { },
   SVGScriptElement: { },
   SVGStopElement: { },
   SVGStringList: { },
   SVGStyleElement: { },
   SVGSVGElement: { },
   SVGSwitchElement: { },
   SVGSymbolElement: { },
   SVGTextContentElement: { },
   SVGTextElement: { },
   SVGTextPathElement: { },
   SVGTextPositioningElement: { },
   SVGTitleElement: { },
   SVGTransform: { },
   SVGTransformList: { },
   SVGTSpanElement: { },
   SVGUnitTypes: { },
   SVGUseElement: { },
   SVGViewElement: { },
   SVGZoomAndPan: { },
   SVGZoomEvent: { },
   Text: { },
   TextEvent: { },
   TextMetrics: { },
   TextRange: { },
   TextRangeCollection: { },
   TextTrack: { },
   TextTrackCueList: { },
   TextTrackList: { },
   TimeRanges: { },
   top: { },
   TrackEvent: { },
   TransitionEvent: { },
   TreeWalker: { },
   TsCmcObj: { },
   UIEvent: { },
   undefined: undefined,
   URL: { },
   ValidityState: { },
   WEBGL_compressed_texture_s3tc: { },
   WEBGL_debug_renderer_info: { },
   WebGLActiveInfo: { },
   WebGLBuffer: { },
   WebGLFramebuffer: { },
   WebGLObject: { },
   WebGLProgram: { },
   WebGLRenderbuffer: { },
   WebGLRenderingContext: { },
   WebGLShader: { },
   WebGLShaderPrecisionFormat: { },
   WebGLTexture: { },
   WebGLUniformLocation: { },
   WheelEvent: { },
   window: { },
   Window: { },
   XMLDocument: { },
   XMLHttpRequestEventTarget: { }
}
-
WEBGL_compressed_texture_s3tc
{
   [functions]: ,
   __proto__: { },
   COMPRESSED_RGB_S3TC_DXT1_EXT: 33776,
   COMPRESSED_RGBA_S3TC_DXT1_EXT: 33777,
   COMPRESSED_RGBA_S3TC_DXT3_EXT: 33778,
   COMPRESSED_RGBA_S3TC_DXT5_EXT: 33779,
   prototype: { }
}
-
WEBGL_debug_renderer_info
{
   [functions]: ,
   __proto__: { },
   prototype: { },
   UNMASKED_RENDERER_WEBGL: 37446,
   UNMASKED_VENDOR_WEBGL: 37445
}
-
WheelEvent
{
   [functions]: ,
   __proto__: { },
   DOM_DELTA_LINE: 1,
   DOM_DELTA_PAGE: 2,
   DOM_DELTA_PIXEL: 0,
   prototype: { }
}
-
window
{
   [functions]: ,
   $_: { },
   __BROWSERTOOLS_CONSOLE: {
      [functions]: ,
      $_: { },
      __proto__: { },
      performBreakmodeIntellisense: { }
   },
   __BROWSERTOOLS_CONSOLE_BREAKMODE_INVOKER: {
      undefined: undefined
   },
   __BROWSERTOOLS_DEBUGGER: { },
   __BROWSERTOOLS_DOMEXPLORER_ADDED: true,
   __BROWSERTOOLS_EMULATIONTOOLS_ADDED: { },
   __BROWSERTOOLS_MEMORYANALYZER_ADDED: { },
   __proto__: { },
   ActiveXObject: undefined,
   AesGcmEncryptResult: { },
   ANGLE_instanced_arrays: { },
   AnimationEvent: { },
   animationStartTime: 4425046.8345313,
   applicationCache: { },
   ApplicationCache: { },
   Attr: { },
   AudioTrack: { },
   AudioTrackList: { },
   BeforeUnloadEvent: { },
   BookmarkCollection: { },
   c: undefined,
   CanvasGradient: { },
   CanvasPattern: { },
   CanvasRenderingContext2D: { },
   CDATASection: { },
   CharacterData: { },
   clientInformation: { },
   ClientRect: { },
   ClientRectList: { },
   clipboardData: { },
   closed: false,
   CloseEvent: { },
   Comment: { },
   CompositionEvent: { },
   console: { },
   Console: { },
   constructor: { },
   ControlRangeCollection: { },
   Coordinates: { },
   Crypto: { },
   CryptoOperation: { },
   CSSFontFaceRule: { },
   CSSImportRule: { },
   CSSKeyframeRule: { },
   CSSKeyframesRule: { },
   CSSMediaRule: { },
   CSSNamespaceRule: { },
   CSSPageRule: { },
   CSSRule: { },
   CSSRuleList: { },
   CSSStyleDeclaration: { },
   CSSStyleRule: { },
   CSSStyleSheet: { },
   CustomEvent: { },
   DataTransfer: { },
   Debug: { },
   defaultStatus: "",
   devicePixelRatio: 1,
   document: { },
   Document: { },
   DocumentFragment: { },
   DocumentType: { },
   DOMError: { },
   DOMException: { },
   DOMImplementation: { },
   DOMSettableTokenList: { },
   DOMStringList: { },
   DOMStringMap: { },
   DOMTokenList: { },
   doNotTrack: null,
   DragEvent: { },
   Element: { },
   ErrorEvent: { },
   event: undefined,
   Event: { },
   EventException: { },
   EXT_texture_filter_anisotropic: { },
   external: { },
   File: { },
   FileList: { },
   FocusEvent: { },
   frameElement: null,
   frames: { },
   Geolocation: { },
   history: { },
   History: { },
   HTMLAllCollection: { },
   HTMLAnchorElement: { },
   HTMLAppletElement: { },
   HTMLAreaElement: { },
   HTMLAreasCollection: { },
   HTMLAudioElement: { },
   HTMLBaseElement: { },
   HTMLBaseFontElement: { },
   HTMLBGSoundElement: { },
   HTMLBlockElement: { },
   HTMLBodyElement: { },
   HTMLBRElement: { },
   HTMLButtonElement: { },
   HTMLCanvasElement: { },
   HTMLCollection: { },
   HTMLDataListElement: { },
   HTMLDDElement: { },
   HTMLDirectoryElement: { },
   HTMLDivElement: { },
   HTMLDListElement: { },
   HTMLDocument: { },
   HTMLDTElement: { },
   HTMLElement: { },
   HTMLEmbedElement: { },
   HTMLFieldSetElement: { },
   HTMLFontElement: { },
   HTMLFormElement: { },
   HTMLFrameElement: { },
   HTMLFrameSetElement: { },
   HTMLHeadElement: { },
   HTMLHeadingElement: { },
   HTMLHRElement: { },
   HTMLHtmlElement: { },
   HTMLIFrameElement: { },
   HTMLImageElement: { },
   HTMLInputElement: { },
   HTMLIsIndexElement: { },
   HTMLLabelElement: { },
   HTMLLegendElement: { },
   HTMLLIElement: { },
   HTMLLinkElement: { },
   HTMLMapElement: { },
   HTMLMarqueeElement: { },
   HTMLMediaElement: { },
   HTMLMenuElement: { },
   HTMLMetaElement: { },
   HTMLModElement: { },
   HTMLNextIdElement: { },
   HTMLObjectElement: { },
   HTMLOListElement: { },
   HTMLOptGroupElement: { },
   HTMLOptionElement: { },
   HTMLParagraphElement: { },
   HTMLParamElement: { },
   HTMLPhraseElement: { },
   HTMLPreElement: { },
   HTMLProgressElement: { },
   HTMLQuoteElement: { },
   HTMLScriptElement: { },
   HTMLSelectElement: { },
   HTMLSourceElement: { },
   HTMLSpanElement: { },
   HTMLStyleElement: { },
   HTMLTableCaptionElement: { },
   HTMLTableCellElement: { },
   HTMLTableColElement: { },
   HTMLTableDataCellElement: { },
   HTMLTableElement: { },
   HTMLTableHeaderCellElement: { },
   HTMLTableRowElement: { },
   HTMLTableSectionElement: { },
   HTMLTextAreaElement: { },
   HTMLTitleElement: { },
   HTMLTrackElement: { },
   HTMLUListElement: { },
   HTMLUnknownElement: { },
   HTMLVideoElement: { },
   IDBCursor: { },
   IDBCursorWithValue: { },
   IDBDatabase: { },
   IDBFactory: { },
   IDBIndex: { },
   IDBKeyRange: { },
   IDBObjectStore: { },
   IDBOpenDBRequest: { },
   IDBRequest: { },
   IDBTransaction: { },
   IDBVersionChangeEvent: { },
   ImageData: { },
   indexedDB: undefined,
   Infinity: Infinity,
   innerHeight: 226,
   innerWidth: 828,
   Intl: { },
   JSON: { },
   Key: { },
   KeyboardEvent: { },
   KeyOperation: { },
   KeyPair: { },
   length: 0,
   localStorage: undefined,
   Location: { },
   location: { },
   Math: { },
   maxConnectionsPerServer: 6,
   MediaError: { },
   MediaList: { },
   MediaQueryList: { },
   MessageEvent: { },
   MessagePort: { },
   MimeType: { },
   MimeTypeArray: { },
   MouseEvent: { },
   MouseWheelEvent: { },
   msAnimationStartTime: 4425046.8345313,
   MSBehaviorUrnsCollection: { },
   MSCompatibleInfo: { },
   MSCompatibleInfoCollection: { },
   msCrypto: { },
   MSCSSProperties: { },
   MSCSSRuleList: { },
   MSCurrentStyleCSSProperties: { },
   MSEventObj: { },
   MSGestureEvent: { },
   msIndexedDB: undefined,
   MSInputMethodContext: { },
   MSManipulationEvent: { },
   MSMimeTypesCollection: { },
   MSPluginsCollection: { },
   MSPointerEvent: { },
   MSRangeCollection: { },
   MSSiteModeEvent: { },
   MSStream: { },
   MSStyleCSSProperties: { },
   MutationEvent: { },
   MutationRecord: { },
   name: "",
   NamedNodeMap: { },
   NaN: NaN,
   navigator: { },
   Navigator: { },
   Node: { },
   NodeFilter: { },
   NodeIterator: { },
   NodeList: { },
   OES_element_index_uint: { },
   OES_standard_derivatives: { },
   OES_texture_float: { },
   OES_texture_float_linear: { },
   offscreenBuffering: "auto",
   onabort: null,
   onafterprint: null,
   onbeforeprint: null,
   onbeforeunload: null,
   onblur: null,
   oncanplay: null,
   oncanplaythrough: null,
   onchange: null,
   onclick: null,
   oncontextmenu: null,
   ondblclick: null,
   ondrag: null,
   ondragend: null,
   ondragenter: null,
   ondragleave: null,
   ondragover: null,
   ondragstart: null,
   ondrop: null,
   ondurationchange: null,
   onemptied: null,
   onended: null,
   onerror: null,
   onfocus: null,
   onfocusin: null,
   onfocusout: null,
   onhashchange: null,
   onhelp: null,
   oninput: null,
   onkeydown: null,
   onkeypress: null,
   onkeyup: null,
   onload: null,
   onloadeddata: null,
   onloadedmetadata: null,
   onloadstart: null,
   onmessage: null,
   onmousedown: null,
   onmouseenter: null,
   onmouseleave: null,
   onmousemove: null,
   onmouseout: null,
   onmouseover: null,
   onmouseup: null,
   onmousewheel: null,
   onmsgesturechange: null,
   onmsgesturedoubletap: null,
   onmsgestureend: null,
   onmsgesturehold: null,
   onmsgesturestart: null,
   onmsgesturetap: null,
   onmsinertiastart: null,
   onmspointercancel: null,
   onmspointerdown: null,
   onmspointerenter: null,
   onmspointerleave: null,
   onmspointermove: null,
   onmspointerout: null,
   onmspointerover: null,
   onmspointerup: null,
   onoffline: null,
   ononline: null,
   onpagehide: null,
   onpageshow: null,
   onpause: null,
   onplay: null,
   onplaying: null,
   onpointercancel: null,
   onpointerdown: null,
   onpointerenter: null,
   onpointerleave: null,
   onpointermove: null,
   onpointerout: null,
   onpointerover: null,
   onpointerup: null,
   onpopstate: null,
   onprogress: null,
   onratechange: null,
   onreadystatechange: null,
   onreset: null,
   onresize: null,
   onscroll: null,
   onseeked: null,
   onseeking: null,
   onselect: null,
   onstalled: null,
   onstorage: null,
   onsubmit: null,
   onsuspend: null,
   ontimeupdate: null,
   onunload: null,
   onvolumechange: null,
   onwaiting: null,
   opener: undefined,
   outerHeight: 514,
   outerWidth: 828,
   PageTransitionEvent: { },
   pageXOffset: 0,
   pageYOffset: 0,
   parent: { },
   performance: { },
   Performance: { },
   PerformanceEntry: { },
   PerformanceMark: { },
   PerformanceMeasure: { },
   PerformanceNavigation: { },
   PerformanceNavigationTiming: { },
   PerformanceResourceTiming: { },
   PerformanceTiming: { },
   Plugin: { },
   PluginArray: { },
   PointerEvent: { },
   PopStateEvent: { },
   Position: { },
   PositionError: { },
   ProcessingInstruction: { },
   ProgressEvent: { },
   Range: { },
   RangeException: { },
   screen: { },
   Screen: { },
   screenLeft: 0,
   screenTop: 139,
   screenX: 0,
   screenY: 78,
   Selection: { },
   self: { },
   sessionStorage: undefined,
   status: "",
   Storage: { },
   StorageEvent: { },
   styleMedia: { },
   StyleMedia: { },
   StyleSheet: { },
   StyleSheetList: { },
   StyleSheetPageList: { },
   SubtleCrypto: { },
   SVGAElement: { },
   SVGAngle: { },
   SVGAnimatedAngle: { },
   SVGAnimatedBoolean: { },
   SVGAnimatedEnumeration: { },
   SVGAnimatedInteger: { },
   SVGAnimatedLength: { },
   SVGAnimatedLengthList: { },
   SVGAnimatedNumber: { },
   SVGAnimatedNumberList: { },
   SVGAnimatedPreserveAspectRatio: { },
   SVGAnimatedRect: { },
   SVGAnimatedString: { },
   SVGAnimatedTransformList: { },
   SVGCircleElement: { },
   SVGClipPathElement: { },
   SVGComponentTransferFunctionElement: { },
   SVGDefsElement: { },
   SVGDescElement: { },
   SVGElement: { },
   SVGElementInstance: { },
   SVGElementInstanceList: { },
   SVGEllipseElement: { },
   SVGException: { },
   SVGFEBlendElement: { },
   SVGFEColorMatrixElement: { },
   SVGFEComponentTransferElement: { },
   SVGFECompositeElement: { },
   SVGFEConvolveMatrixElement: { },
   SVGFEDiffuseLightingElement: { },
   SVGFEDisplacementMapElement: { },
   SVGFEDistantLightElement: { },
   SVGFEFloodElement: { },
   SVGFEFuncAElement: { },
   SVGFEFuncBElement: { },
   SVGFEFuncGElement: { },
   SVGFEFuncRElement: { },
   SVGFEGaussianBlurElement: { },
   SVGFEImageElement: { },
   SVGFEMergeElement: { },
   SVGFEMergeNodeElement: { },
   SVGFEMorphologyElement: { },
   SVGFEOffsetElement: { },
   SVGFEPointLightElement: { },
   SVGFESpecularLightingElement: { },
   SVGFESpotLightElement: { },
   SVGFETileElement: { },
   SVGFETurbulenceElement: { },
   SVGFilterElement: { },
   SVGGElement: { },
   SVGGradientElement: { },
   SVGImageElement: { },
   SVGLength: { },
   SVGLengthList: { },
   SVGLinearGradientElement: { },
   SVGLineElement: { },
   SVGMarkerElement: { },
   SVGMaskElement: { },
   SVGMatrix: { },
   SVGMetadataElement: { },
   SVGNumber: { },
   SVGNumberList: { },
   SVGPathElement: { },
   SVGPathSeg: { },
   SVGPathSegArcAbs: { },
   SVGPathSegArcRel: { },
   SVGPathSegClosePath: { },
   SVGPathSegCurvetoCubicAbs: { },
   SVGPathSegCurvetoCubicRel: { },
   SVGPathSegCurvetoCubicSmoothAbs: { },
   SVGPathSegCurvetoCubicSmoothRel: { },
   SVGPathSegCurvetoQuadraticAbs: { },
   SVGPathSegCurvetoQuadraticRel: { },
   SVGPathSegCurvetoQuadraticSmoothAbs: { },
   SVGPathSegCurvetoQuadraticSmoothRel: { },
   SVGPathSegLinetoAbs: { },
   SVGPathSegLinetoHorizontalAbs: { },
   SVGPathSegLinetoHorizontalRel: { },
   SVGPathSegLinetoRel: { },
   SVGPathSegLinetoVerticalAbs: { },
   SVGPathSegLinetoVerticalRel: { },
   SVGPathSegList: { },
   SVGPathSegMovetoAbs: { },
   SVGPathSegMovetoRel: { },
   SVGPatternElement: { },
   SVGPoint: { },
   SVGPointList: { },
   SVGPolygonElement: { },
   SVGPolylineElement: { },
   SVGPreserveAspectRatio: { },
   SVGRadialGradientElement: { },
   SVGRect: { },
   SVGRectElement: { },
   SVGScriptElement: { },
   SVGStopElement: { },
   SVGStringList: { },
   SVGStyleElement: { },
   SVGSVGElement: { },
   SVGSwitchElement: { },
   SVGSymbolElement: { },
   SVGTextContentElement: { },
   SVGTextElement: { },
   SVGTextPathElement: { },
   SVGTextPositioningElement: { },
   SVGTitleElement: { },
   SVGTransform: { },
   SVGTransformList: { },
   SVGTSpanElement: { },
   SVGUnitTypes: { },
   SVGUseElement: { },
   SVGViewElement: { },
   SVGZoomAndPan: { },
   SVGZoomEvent: { },
   Text: { },
   TextEvent: { },
   TextMetrics: { },
   TextRange: { },
   TextRangeCollection: { },
   TextTrack: { },
   TextTrackCueList: { },
   TextTrackList: { },
   TimeRanges: { },
   top: { },
   TrackEvent: { },
   TransitionEvent: { },
   TreeWalker: { },
   TsCmcObj: { },
   UIEvent: { },
   undefined: undefined,
   URL: { },
   ValidityState: { },
   WEBGL_compressed_texture_s3tc: { },
   WEBGL_debug_renderer_info: { },
   WebGLActiveInfo: { },
   WebGLBuffer: { },
   WebGLFramebuffer: { },
   WebGLObject: { },
   WebGLProgram: { },
   WebGLRenderbuffer: { },
   WebGLRenderingContext: { },
   WebGLShader: { },
   WebGLShaderPrecisionFormat: { },
   WebGLTexture: { },
   WebGLUniformLocation: { },
   WheelEvent: { },
   window: { },
   Window: { },
   XMLDocument: { },
   XMLHttpRequestEventTarget: { }
}






2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
   WEBGL_compressed_texture_s3tc: { },
   WEBGL_debug_renderer_info: { },
   WebGLActiveInfo: { },
   WebGLBuffer: { },
   WebGLFramebuffer: { },
   WebGLObject: { },
   WebGLProgram: { },
   WebGLRenderbuffer: { },
   WebGLRenderingContext: { },
   WebGLShader: { },
   WebGLShaderPrecisionFormat: { },
   WebGLTexture: { },
   WebGLUniformLocation: { },
   WheelEvent: { },
   window: { },
   Window: { },
   XMLDocument: { },
   XMLHttpRequestEventTarget: { }
}


