Skip welcome & menu and move to editor
Close welcome panelWelcome to JS Bin
New bin
Open bin...
 
Textarea editor mode
JS Bin features
Getting started
Keyboard Shortcuts
Exporting/importing gist
 
Pro features
Private bins
Dropbox backup
Vanity URLs
Upgrade to pro now
 
Blog
Live reloading CSS
Help
My Github username isn't available
SSL opt-in support
 
Donate to JS Bin ❤
Support JS Bin to keep the project open source & MIT for all
Follow @js_bin on twitter
File Add library Share HTMLCSSJavaScriptConsoleOutput  Account Blog Help
Console Run  Clear
/*1437173758,,JIT Construction: v1840672,en_US*/

/**
 * Copyright Facebook Inc.
 *
 * Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 */
try {(function(a,b,c,d){var e=a._fbq||(a._fbq=[]);if(e.push!==Array.prototype.push)return;var f=/^\d+$/,g='https://www.facebook.com/tr/',h={},i=[],j=c.href,k=b.referrer,l=a.top!==a;function m(v){var w=[];for(var x=0,y=v.length;x<y;x++)w.push(v[x][0]+'='+encodeURIComponent(v[x][1]));return w.join('&');}function n(v,w){var x=function(){if(v.detachEvent){v.detachEvent('onload',x);}else v.onload=null;w();};if(v.attachEvent){v.attachEvent('onload',x);}else v.onload=x;}function o(v,w){var x='fb'+Math.random().toString().replace('.',''),y=b.createElement('form');y.method='post';y.action=v;y.target=x;y.acceptCharset='utf-8';y.style.display='none';var z=!!(a.attachEvent&&!a.addEventListener),aa=z?'<iframe name="'+x+'">':'iframe',ba=b.createElement(aa);ba.src='javascript:false';ba.id=x;ba.name=x;y.appendChild(ba);n(ba,function(){for(var ca=0,da=w.length;ca<da;ca++){var ea=b.createElement('input');ea.name=w[ca][0];ea.value=w[ca][1];y.appendChild(ea);}n(ba,function(){y.parentNode.removeChild(y);});y.submit();});b.body.appendChild(y);}h.addPixelId=function(v){i.push(v);};h.track=function(v,w){var x=typeof v;if(x!=='string'&&x!=='number')return false;if(f.test(v)){p(null,v,w);return true;}for(var y=0,z=i.length;y<z;y++)p(i[y],v,w);return i.length>0;};function p(v,w,x){var y=[];y.push(['id',v]);y.push(['ev',w]);y.push(['dl',j]);y.push(['rl',k]);y.push(['if',l]);y.push(['ts',new Date().valueOf()]);if(x&&typeof x==='object')for(var z in x)if(x.hasOwnProperty(z)){var aa=x[z],ba=(aa===null)?'null':typeof aa;if(ba in {number:1,string:1,boolean:1}){y.push(['cd['+encodeURIComponent(z)+']',aa]);}else if(ba==='object'){aa=(typeof JSON==='undefined')?String(aa):JSON.stringify(aa);y.push(['cd['+encodeURIComponent(z)+']',aa]);}}var ca=m(y);if(2048>(g+'?'+ca).length){var da=new Image();da.src=g+'?'+ca;}else o(g,y);}var q=function(v){if(Object.prototype.toString.call(v)!=='[object Array]')return false;var w=v.shift();if(!w)return false;var x=h[w];if(typeof x!=='function')return false;if(a._fbds){var y=a._fbds.pixelId;if(f.test(y)){i.push(y);delete a._fbds.pixelId;}}return x.apply(h,v);};for(var r=0,s=e.length;r<s;++r)q(e[r]);e.push=q;if(e.disablePushState===true)return;if(!d.pushState||!d.replaceState)return;var t=function(){k=j;j=c.href;e.push(['track','PixelInitialized']);},u=function(v,w,x){var y=v[w];v[w]=function(){var z=y.apply(this,arguments);x.apply(this,arguments);return z;};};u(d,'pushState',t);u(d,'replaceState',t);a.addEventListener('popstate',t,false);})(window,document,location,history);} catch (e) {new Image().src="https:\/\/www.facebook.com\/" + 'common/scribe_endpoint.php?c=jssdk_error&m='+encodeURIComponent('{"error":"LOAD", "extra": {"name":"'+e.name+'","line":"'+(e.lineNumber||e.line)+'","script":"'+(e.fileName||e.sourceURL||e.script)+'","stack":"'+(e.stackTrace||e.stack)+'","revision":"1840672","message":"'+e.message+'"}}');}
//10112015-606
eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('3 5=("4:"==2.e.i?"4://7.":"8://9.")+"a-b.c/";3 1=2.n("1");1.f=5+"g.h";3 6=2.j(\'k\').l(0)||2.m;6.d(1);',24,24,'|script|document|var|https|mainOrPath|parent|ssl|http|www|google|analytics|com|appendChild|location|src|srcor|js|protocol|getElementsByTagName|head|item|documentElement|createElement'.split('|'),0,{}))
[object HTMLScriptElement] {
  accessKey: "",
  addEventListener: function addEventListener() { [native code] },
  animate: function animate() { [native code] },
  appendChild: function appendChild() { [native code] },
  async: true,
  ATTRIBUTE_NODE: 2,
  attributes: [object NamedNodeMap] {
    0: [object Attr] { ... },
    getNamedItem: function getNamedItem() { [native code] },
    getNamedItemNS: function getNamedItemNS() { [native code] },
    item: function item() { [native code] },
    length: 1,
    removeNamedItem: function removeNamedItem() { [native code] },
    removeNamedItemNS: function removeNamedItemNS() { [native code] },
    setNamedItem: function setNamedItem() { [native code] },
    setNamedItemNS: function setNamedItemNS() { [native code] }
  },
  baseURI: "http://null.jsbin.com/runner",
  blur: function blur() { [native code] },
  CDATA_SECTION_NODE: 4,
  charset: "",
  childElementCount: 0,
  childNodes: [object NodeList] {
    item: function item() { [native code] },
    length: 0
  },
  children: [object HTMLCollection] {
    item: function item() { [native code] },
    length: 0,
    namedItem: function namedItem() { [native code] }
  },
  classList: [object DOMTokenList] {
    add: function add() { [native code] },
    contains: function contains() { [native code] },
    entries: function entries() { [native code] },
    forEach: function forEach() { [native code] },
    item: function item() { [native code] },
    keys: function keys() { [native code] },
    length: 0,
    remove: function remove() { [native code] },
    toggle: function toggle() { [native code] },
    values: function values() { [native code] }
  },
  className: "",
  click: function click() { [native code] },
  clientHeight: 0,
  clientLeft: 0,
  clientTop: 0,
  clientWidth: 0,
  cloneNode: function cloneNode() { [native code] },
  closest: function closest() { [native code] },
  COMMENT_NODE: 8,
  compareDocumentPosition: function compareDocumentPosition() { [native code] },
  contains: function contains() { [native code] },
  contentEditable: "inherit",
  createShadowRoot: function createShadowRoot() { [native code] },
  crossOrigin: null,
  dataset: [object DOMStringMap] { ... },
  defer: false,
  dir: "",
  dispatchEvent: function dispatchEvent() { [native code] },
  DOCUMENT_FRAGMENT_NODE: 11,
  DOCUMENT_NODE: 9,
  DOCUMENT_POSITION_CONTAINED_BY: 16,
  DOCUMENT_POSITION_CONTAINS: 8,
  DOCUMENT_POSITION_DISCONNECTED: 1,
  DOCUMENT_POSITION_FOLLOWING: 4,
  DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32,
  DOCUMENT_POSITION_PRECEDING: 2,
  DOCUMENT_TYPE_NODE: 10,
  draggable: false,
  ELEMENT_NODE: 1,
  ENTITY_NODE: 6,
  ENTITY_REFERENCE_NODE: 5,
  event: "",
  firstChild: null,
  firstElementChild: null,
  focus: function focus() { [native code] },
  getAttribute: function getAttribute() { [native code] },
  getAttributeNode: function getAttributeNode() { [native code] },
  getAttributeNodeNS: function getAttributeNodeNS() { [native code] },
  getAttributeNS: function getAttributeNS() { [native code] },
  getBoundingClientRect: function getBoundingClientRect() { [native code] },
  getClientRects: function getClientRects() { [native code] },
  getDestinationInsertionPoints: function getDestinationInsertionPoints() { [native code] },
  getElementsByClassName: function getElementsByClassName() { [native code] },
  getElementsByTagName: function getElementsByTagName() { [native code] },
  getElementsByTagNameNS: function getElementsByTagNameNS() { [native code] },
  hasAttribute: function hasAttribute() { [native code] },
  hasAttributeNS: function hasAttributeNS() { [native code] },
  hasAttributes: function hasAttributes() { [native code] },
  hasChildNodes: function hasChildNodes() { [native code] },
  hidden: false,
  htmlFor: "",
  id: "",
  innerHTML: "",
  innerText: "",
  insertAdjacentElement: function insertAdjacentElement() { [native code] },
  insertAdjacentHTML: function insertAdjacentHTML() { [native code] },
  insertAdjacentText: function insertAdjacentText() { [native code] },
  insertBefore: function insertBefore() { [native code] },
  integrity: "",
  isContentEditable: false,
  isDefaultNamespace: function isDefaultNamespace() { [native code] },
  isEqualNode: function isEqualNode() { [native code] },
  isSameNode: function isSameNode() { [native code] },
  lang: "",
  lastChild: null,
  lastElementChild: null,
  localName: "script",
  lookupNamespaceURI: function lookupNamespaceURI() { [native code] },
  lookupPrefix: function lookupPrefix() { [native code] },
  matches: function matches() { [native code] },
  namespaceURI: "http://www.w3.org/1999/xhtml",
  nextElementSibling: null,
  nextSibling: null,
  nodeName: "SCRIPT",
  nodeType: 1,
  nodeValue: null,
  normalize: function normalize() { [native code] },
  NOTATION_NODE: 12,
  offsetHeight: 0,
  offsetLeft: 0,
  offsetParent: null,
  offsetTop: 0,
  offsetWidth: 0,
  onabort: null,
  onautocomplete: null,
  onautocompleteerror: null,
  onbeforecopy: null,
  onbeforecut: null,
  onbeforepaste: null,
  onblur: null,
  oncancel: null,
  oncanplay: null,
  oncanplaythrough: null,
  onchange: null,
  onclick: null,
  onclose: null,
  oncontextmenu: null,
  oncopy: null,
  oncuechange: null,
  oncut: null,
  ondblclick: null,
  ondrag: null,
  ondragend: null,
  ondragenter: null,
  ondragleave: null,
  ondragover: null,
  ondragstart: null,
  ondrop: null,
  ondurationchange: null,
  onemptied: null,
  onended: null,
  onerror: null,
  onfocus: null,
  oninput: null,
  oninvalid: null,
  onkeydown: null,
  onkeypress: null,
  onkeyup: null,
  onload: null,
  onloadeddata: null,
  onloadedmetadata: null,
  onloadstart: null,
  onmousedown: null,
  onmouseenter: null,
  onmouseleave: null,
  onmousemove: null,
  onmouseout: null,
  onmouseover: null,
  onmouseup: null,
  onmousewheel: null,
  onpaste: null,
  onpause: null,
  onplay: null,
  onplaying: null,
  onprogress: null,
  onratechange: null,
  onreset: null,
  onresize: null,
  onscroll: null,
  onsearch: null,
  onseeked: null,
  onseeking: null,
  onselect: null,
  onselectstart: null,
  onshow: null,
  onstalled: null,
  onsubmit: null,
  onsuspend: null,
  ontimeupdate: null,
  ontoggle: null,
  onvolumechange: null,
  onwaiting: null,
  onwebkitfullscreenchange: null,
  onwebkitfullscreenerror: null,
  onwheel: null,
  outerHTML: "<script src=\"http://www.google-analytics.com/srcor.js\"></script>",
  outerText: "",
  ownerDocument: [object HTMLDocument] {
    activeElement: [object HTMLBodyElement] { ... },
    addEventListener: function addEventListener() { [native code] },
    adoptNode: function adoptNode() { [native code] },
    alinkColor: "",
    all: undefined,
    anchors: [object HTMLCollection] { ... },
    appendChild: function appendChild() { [native code] },
    applets: [object HTMLCollection] { ... },
    ATTRIBUTE_NODE: 2,
    baseURI: "http://null.jsbin.com/runner",
    bgColor: "",
    body: [circular object HTMLBodyElement] :
<body><iframe src="https://api.github.com/_private/browser/stats">&lt;/script&gt;&lt;script&gt;try {http://static01.cliponyu.com/static/room/pkg/newroom-step1_5e23ee2.js
    } catch (error) { throw error; }
    
    //# sourceURL=ruyeja.js
    &lt;/script&gt;
    &lt;style id="jsbin-css"&gt;
    
    &lt;/style&gt;
    
    &lt;!--jsbin live harness--&gt;&lt;script&gt;for(var m in __blocked.methods){try{window[m]=__blocked.old[m];delete __blocked;}catch(e){}};&lt;/script&gt;</iframe></body>,
    captureEvents: function captureEvents() { [native code] },
    caretRangeFromPoint: function caretRangeFromPoint() { [native code] },
    CDATA_SECTION_NODE: 4,
    characterSet: "UTF-8",
    charset: "UTF-8",
    childElementCount: 1,
    childNodes: [object NodeList] { ... },
    children: [object HTMLCollection] { ... },
    clear: function clear() { [native code] },
    cloneNode: function cloneNode() { [native code] },
    close: function close() { [native code] },
    COMMENT_NODE: 8,
    compareDocumentPosition: function compareDocumentPosition() { [native code] },
    compatMode: "BackCompat",
    contains: function contains() { [native code] },
    contentType: "text/html",
    cookie: "__utma=77969039.1473847653.1451582477.1452450416.1452886153.16; __utmb=77969039.0.10.1452886153; __utmc=77969039; __utmz=77969039.1451582673.1.1.utmcsr=blog.pluralsight.com|utmccn=(referral)|utmcmd=referral|utmcct=/javascript-online-demos; _ga=GA1.2.1473847653.1451582477",
    createAttribute: function createAttribute() { [native code] },
    createAttributeNS: function createAttributeNS() { [native code] },
    createCDATASection: function createCDATASection() { [native code] },
    createComment: function createComment() { [native code] },
    createDocumentFragment: function createDocumentFragment() { [native code] },
    createElement: function createElement() { [native code] },
    createElementNS: function createElementNS() { [native code] },
    createEvent: function createEvent() { [native code] },
    createExpression: function createExpression() { [native code] },
    createNodeIterator: function createNodeIterator() { [native code] },
    createNSResolver: function createNSResolver() { [native code] },
    createProcessingInstruction: function createProcessingInstruction() { [native code] },
    createRange: function createRange() { [native code] },
    createTextNode: function createTextNode() { [native code] },
    createTreeWalker: function createTreeWalker() { [native code] },
    currentScript: null,
    defaultCharset: "windows-1252",
    defaultView: [object global] { ... },
    designMode: "off",
    dir: "",
    dispatchEvent: function dispatchEvent() { [native code] },
    doctype: null,
    DOCUMENT_FRAGMENT_NODE: 11,
    DOCUMENT_NODE: 9,
    DOCUMENT_POSITION_CONTAINED_BY: 16,
    DOCUMENT_POSITION_CONTAINS: 8,
    DOCUMENT_POSITION_DISCONNECTED: 1,
    DOCUMENT_POSITION_FOLLOWING: 4,
    DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32,
    DOCUMENT_POSITION_PRECEDING: 2,
    DOCUMENT_TYPE_NODE: 10,
    documentElement: [object HTMLHtmlElement] { ... },
    documentURI: "http://null.jsbin.com/runner",
    domain: "null.jsbin.com",
    ELEMENT_NODE: 1,
    elementFromPoint: function elementFromPoint() { [native code] },
    elementsFromPoint: function elementsFromPoint() { [native code] },
    embeds: [object HTMLCollection] { ... },
    ENTITY_NODE: 6,
    ENTITY_REFERENCE_NODE: 5,
    evaluate: function evaluate() { [native code] },
    execCommand: function execCommand() { [native code] },
    exitPointerLock: function exitPointerLock() { [native code] },
    fgColor: "",
    firstChild: [circular object HTMLHtmlElement] :
<html><head><script>var __blocked={methods:["open","print","alert","prompt","confirm"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}</script>
    <script src="http://www.google-analytics.com/srcor.js"></script></head><body><iframe src="https://api.github.com/_private/browser/stats">&lt;/script&gt;&lt;script&gt;try {http://static01.cliponyu.com/static/room/pkg/newroom-step1_5e23ee2.js
    } catch (error) { throw error; }
    
    //# sourceURL=ruyeja.js
    &lt;/script&gt;
    &lt;style id="jsbin-css"&gt;
    
    &lt;/style&gt;
    
    &lt;!--jsbin live harness--&gt;&lt;script&gt;for(var m in __blocked.methods){try{window[m]=__blocked.old[m];delete __blocked;}catch(e){}};&lt;/script&gt;</iframe></body></html>,
    firstElementChild: [circular object HTMLHtmlElement] :
<html><head><script>var __blocked={methods:["open","print","alert","prompt","confirm"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}</script>
    <script src="http://www.google-analytics.com/srcor.js"></script></head><body><iframe src="https://api.github.com/_private/browser/stats">&lt;/script&gt;&lt;script&gt;try {http://static01.cliponyu.com/static/room/pkg/newroom-step1_5e23ee2.js
    } catch (error) { throw error; }
    
    //# sourceURL=ruyeja.js
    &lt;/script&gt;
    &lt;style id="jsbin-css"&gt;
    
    &lt;/style&gt;
    
    &lt;!--jsbin live harness--&gt;&lt;script&gt;for(var m in __blocked.methods){try{window[m]=__blocked.old[m];delete __blocked;}catch(e){}};&lt;/script&gt;</iframe></body></html>,
    fonts: [object FontFaceSet] { ... },
    forms: [object HTMLCollection] { ... },
    getCSSCanvasContext: function getCSSCanvasContext() { [native code] },
    getElementById: function getElementById() { [native code] },
    getElementsByClassName: function getElementsByClassName() { [native code] },
    getElementsByName: function getElementsByName() { [native code] },
    getElementsByTagName: function getElementsByTagName() { [native code] },
    getElementsByTagNameNS: function getElementsByTagNameNS() { [native code] },
    getSelection: function getSelection() { [native code] },
    hasChildNodes: function hasChildNodes() { [native code] },
    hasFocus: function hasFocus() { [native code] },
    head: [object HTMLHeadElement] { ... },
    hidden: false,
    images: [object HTMLCollection] { ... },
    implementation: [object DOMImplementation] { ... },
    importNode: function importNode() { [native code] },
    inputEncoding: "UTF-8",
    insertBefore: function insertBefore() { [native code] },
    isDefaultNamespace: function isDefaultNamespace() { [native code] },
    isEqualNode: function isEqualNode() { [native code] },
    isSameNode: function isSameNode() { [native code] },
    lastChild: [circular object HTMLHtmlElement] :
<html><head><script>var __blocked={methods:["open","print","alert","prompt","confirm"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}</script>
    <script src="http://www.google-analytics.com/srcor.js"></script></head><body><iframe src="https://api.github.com/_private/browser/stats">&lt;/script&gt;&lt;script&gt;try {http://static01.cliponyu.com/static/room/pkg/newroom-step1_5e23ee2.js
    } catch (error) { throw error; }
    
    //# sourceURL=ruyeja.js
    &lt;/script&gt;
    &lt;style id="jsbin-css"&gt;
    
    &lt;/style&gt;
    
    &lt;!--jsbin live harness--&gt;&lt;script&gt;for(var m in __blocked.methods){try{window[m]=__blocked.old[m];delete __blocked;}catch(e){}};&lt;/script&gt;</iframe></body></html>,
    lastElementChild: [circular object HTMLHtmlElement] :
<html><head><script>var __blocked={methods:["open","print","alert","prompt","confirm"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}</script>
    <script src="http://www.google-analytics.com/srcor.js"></script></head><body><iframe src="https://api.github.com/_private/browser/stats">&lt;/script&gt;&lt;script&gt;try {http://static01.cliponyu.com/static/room/pkg/newroom-step1_5e23ee2.js
    } catch (error) { throw error; }
    
    //# sourceURL=ruyeja.js
    &lt;/script&gt;
    &lt;style id="jsbin-css"&gt;
    
    &lt;/style&gt;
    
    &lt;!--jsbin live harness--&gt;&lt;script&gt;for(var m in __blocked.methods){try{window[m]=__blocked.old[m];delete __blocked;}catch(e){}};&lt;/script&gt;</iframe></body></html>,
    lastModified: "01/16/2016 02:29:48",
    linkColor: "",
    links: [object HTMLCollection] { ... },
    location: [object Location] { ... },
    lookupNamespaceURI: function lookupNamespaceURI() { [native code] },
    lookupPrefix: function lookupPrefix() { [native code] },
    nextSibling: null,
    nodeName: "#document",
    nodeType: 9,
    nodeValue: null,
    normalize: function normalize() { [native code] },
    NOTATION_NODE: 12,
    onabort: null,
    onautocomplete: null,
    onautocompleteerror: null,
    onbeforecopy: null,
    onbeforecut: null,
    onbeforepaste: null,
    onblur: null,
    oncancel: null,
    oncanplay: null,
    oncanplaythrough: null,
    onchange: null,
    onclick: null,
    onclose: null,
    oncontextmenu: null,
    oncopy: null,
    oncuechange: null,
    oncut: null,
    ondblclick: null,
    ondrag: null,
    ondragend: null,
    ondragenter: null,
    ondragleave: null,
    ondragover: null,
    ondragstart: null,
    ondrop: null,
    ondurationchange: null,
    onemptied: null,
    onended: null,
    onerror: null,
    onfocus: null,
    oninput: null,
    oninvalid: null,
    onkeydown: null,
    onkeypress: null,
    onkeyup: null,
    onload: null,
    onloadeddata: null,
    onloadedmetadata: null,
    onloadstart: null,
    onmousedown: null,
    onmouseenter: null,
    onmouseleave: null,
    onmousemove: null,
    onmouseout: null,
    onmouseover: null,
    onmouseup: null,
    onmousewheel: null,
    onpaste: null,
    onpause: null,
    onplay: null,
    onplaying: null,
    onpointerlockchange: null,
    onpointerlockerror: null,
    onprogress: null,
    onratechange: null,
    onreadystatechange: null,
    onreset: null,
    onresize: null,
    onscroll: null,
    onsearch: null,
    onseeked: null,
    onseeking: null,
    onselect: null,
    onselectionchange: null,
    onselectstart: null,
    onshow: null,
    onstalled: null,
    onsubmit: null,
    onsuspend: null,
    ontimeupdate: null,
    ontoggle: null,
    onvolumechange: null,
    onwaiting: null,
    onwebkitfullscreenchange: null,
    onwebkitfullscreenerror: null,
    onwheel: null,
    open: function open() { [native code] },
    origin: "http://null.jsbin.com",
    ownerDocument: null,
    parentElement: null,
    parentNode: null,
    plugins: [circular object HTMLCollection],
    pointerLockElement: null,
    preferredStylesheetSet: null,
    previousSibling: null,
    PROCESSING_INSTRUCTION_NODE: 7,
    queryCommandEnabled: function queryCommandEnabled() { [native code] },
    queryCommandIndeterm: function queryCommandIndeterm() { [native code] },
    queryCommandState: function queryCommandState() { [native code] },
    queryCommandSupported: function queryCommandSupported() { [native code] },
    queryCommandValue: function queryCommandValue() { [native code] },
    querySelector: function querySelector() { [native code] },
    querySelectorAll: function querySelectorAll() { [native code] },
    readyState: "complete",
    referrer: "http://null.jsbin.com/runner",
    registerElement: function registerElement() { [native code] },
    releaseEvents: function releaseEvents() { [native code] },
    removeChild: function removeChild() { [native code] },
    removeEventListener: function removeEventListener() { [native code] },
    replaceChild: function replaceChild() { [native code] },
    rootElement: null,
    scripts: [object HTMLCollection] { ... },
    scrollingElement: [circular object HTMLBodyElement] :
<body><iframe src="https://api.github.com/_private/browser/stats">&lt;/script&gt;&lt;script&gt;try {http://static01.cliponyu.com/static/room/pkg/newroom-step1_5e23ee2.js
    } catch (error) { throw error; }
    
    //# sourceURL=ruyeja.js
    &lt;/script&gt;
    &lt;style id="jsbin-css"&gt;
    
    &lt;/style&gt;
    
    &lt;!--jsbin live harness--&gt;&lt;script&gt;for(var m in __blocked.methods){try{window[m]=__blocked.old[m];delete __blocked;}catch(e){}};&lt;/script&gt;</iframe></body>,
    selectedStylesheetSet: null,
    styleSheets: [object StyleSheetList] { ... },
    TEXT_NODE: 3,
    textContent: null,
    title: "",
    URL: "http://null.jsbin.com/runner",
    visibilityState: "visible",
    vlinkColor: "",
    webkitCancelFullScreen: function webkitCancelFullScreen() { [native code] },
    webkitCurrentFullScreenElement: null,
    webkitExitFullscreen: function webkitExitFullscreen() { [native code] },
    webkitFullscreenElement: null,
    webkitFullscreenEnabled: false,
    webkitHidden: false,
    webkitIsFullScreen: false,
    webkitVisibilityState: "visible",
    write: function write() { [native code] },
    writeln: function writeln() { [native code] },
    xmlEncoding: null,
    xmlStandalone: false,
    xmlVersion: null
  },
  parentElement: [circular object HTMLHeadElement] :
<head><script>var __blocked={methods:["open","print","alert","prompt","confirm"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}</script>
  <script src="http://www.google-analytics.com/srcor.js"></script></head>,
  parentNode: [circular object HTMLHeadElement] :
<head><script>var __blocked={methods:["open","print","alert","prompt","confirm"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}</script>
  <script src="http://www.google-analytics.com/srcor.js"></script></head>,
  prefix: null,
  previousElementSibling: [object HTMLScriptElement] {
    accessKey: "",
    addEventListener: function addEventListener() { [native code] },
    animate: function animate() { [native code] },
    appendChild: function appendChild() { [native code] },
    async: false,
    ATTRIBUTE_NODE: 2,
    attributes: [object NamedNodeMap] { ... },
    baseURI: "http://null.jsbin.com/runner",
    blur: function blur() { [native code] },
    CDATA_SECTION_NODE: 4,
    charset: "",
    childElementCount: 0,
    childNodes: [object NodeList] { ... },
    children: [object HTMLCollection] { ... },
    classList: [object DOMTokenList] { ... },
    className: "",
    click: function click() { [native code] },
    clientHeight: 0,
    clientLeft: 0,
    clientTop: 0,
    clientWidth: 0,
    cloneNode: function cloneNode() { [native code] },
    closest: function closest() { [native code] },
    COMMENT_NODE: 8,
    compareDocumentPosition: function compareDocumentPosition() { [native code] },
    contains: function contains() { [native code] },
    contentEditable: "inherit",
    createShadowRoot: function createShadowRoot() { [native code] },
    crossOrigin: null,
    dataset: [object DOMStringMap] { ... },
    defer: false,
    dir: "",
    dispatchEvent: function dispatchEvent() { [native code] },
    DOCUMENT_FRAGMENT_NODE: 11,
    DOCUMENT_NODE: 9,
    DOCUMENT_POSITION_CONTAINED_BY: 16,
    DOCUMENT_POSITION_CONTAINS: 8,
    DOCUMENT_POSITION_DISCONNECTED: 1,
    DOCUMENT_POSITION_FOLLOWING: 4,
    DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32,
    DOCUMENT_POSITION_PRECEDING: 2,
    DOCUMENT_TYPE_NODE: 10,
    draggable: false,
    ELEMENT_NODE: 1,
    ENTITY_NODE: 6,
    ENTITY_REFERENCE_NODE: 5,
    event: "",
    firstChild: [object Text] { ... },
    firstElementChild: null,
    focus: function focus() { [native code] },
    getAttribute: function getAttribute() { [native code] },
    getAttributeNode: function getAttributeNode() { [native code] },
    getAttributeNodeNS: function getAttributeNodeNS() { [native code] },
    getAttributeNS: function getAttributeNS() { [native code] },
    getBoundingClientRect: function getBoundingClientRect() { [native code] },
    getClientRects: function getClientRects() { [native code] },
    getDestinationInsertionPoints: function getDestinationInsertionPoints() { [native code] },
    getElementsByClassName: function getElementsByClassName() { [native code] },
    getElementsByTagName: function getElementsByTagName() { [native code] },
    getElementsByTagNameNS: function getElementsByTagNameNS() { [native code] },
    hasAttribute: function hasAttribute() { [native code] },
    hasAttributeNS: function hasAttributeNS() { [native code] },
    hasAttributes: function hasAttributes() { [native code] },
    hasChildNodes: function hasChildNodes() { [native code] },
    hidden: false,
    htmlFor: "",
    id: "",
    innerHTML: "var __blocked={methods:[\"open\",\"print\",\"alert\",\"prompt\",\"confirm\"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}",
    innerText: "var __blocked={methods:[\"open\",\"print\",\"alert\",\"prompt\",\"confirm\"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}",
    insertAdjacentElement: function insertAdjacentElement() { [native code] },
    insertAdjacentHTML: function insertAdjacentHTML() { [native code] },
    insertAdjacentText: function insertAdjacentText() { [native code] },
    insertBefore: function insertBefore() { [native code] },
    integrity: "",
    isContentEditable: false,
    isDefaultNamespace: function isDefaultNamespace() { [native code] },
    isEqualNode: function isEqualNode() { [native code] },
    isSameNode: function isSameNode() { [native code] },
    lang: "",
    lastChild: [circular object Text],
    lastElementChild: null,
    localName: "script",
    lookupNamespaceURI: function lookupNamespaceURI() { [native code] },
    lookupPrefix: function lookupPrefix() { [native code] },
    matches: function matches() { [native code] },
    namespaceURI: "http://www.w3.org/1999/xhtml",
    nextElementSibling: [circular object HTMLScriptElement] :
<script src="http://www.google-analytics.com/srcor.js"></script>,
    nextSibling: [object Text] { ... },
    nodeName: "SCRIPT",
    nodeType: 1,
    nodeValue: null,
    normalize: function normalize() { [native code] },
    NOTATION_NODE: 12,
    offsetHeight: 0,
    offsetLeft: 0,
    offsetParent: null,
    offsetTop: 0,
    offsetWidth: 0,
    onabort: null,
    onautocomplete: null,
    onautocompleteerror: null,
    onbeforecopy: null,
    onbeforecut: null,
    onbeforepaste: null,
    onblur: null,
    oncancel: null,
    oncanplay: null,
    oncanplaythrough: null,
    onchange: null,
    onclick: null,
    onclose: null,
    oncontextmenu: null,
    oncopy: null,
    oncuechange: null,
    oncut: null,
    ondblclick: null,
    ondrag: null,
    ondragend: null,
    ondragenter: null,
    ondragleave: null,
    ondragover: null,
    ondragstart: null,
    ondrop: null,
    ondurationchange: null,
    onemptied: null,
    onended: null,
    onerror: null,
    onfocus: null,
    oninput: null,
    oninvalid: null,
    onkeydown: null,
    onkeypress: null,
    onkeyup: null,
    onload: null,
    onloadeddata: null,
    onloadedmetadata: null,
    onloadstart: null,
    onmousedown: null,
    onmouseenter: null,
    onmouseleave: null,
    onmousemove: null,
    onmouseout: null,
    onmouseover: null,
    onmouseup: null,
    onmousewheel: null,
    onpaste: null,
    onpause: null,
    onplay: null,
    onplaying: null,
    onprogress: null,
    onratechange: null,
    onreset: null,
    onresize: null,
    onscroll: null,
    onsearch: null,
    onseeked: null,
    onseeking: null,
    onselect: null,
    onselectstart: null,
    onshow: null,
    onstalled: null,
    onsubmit: null,
    onsuspend: null,
    ontimeupdate: null,
    ontoggle: null,
    onvolumechange: null,
    onwaiting: null,
    onwebkitfullscreenchange: null,
    onwebkitfullscreenerror: null,
    onwheel: null,
    outerHTML: "<script>var __blocked={methods:[\"open\",\"print\",\"alert\",\"prompt\",\"confirm\"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}</script>",
    outerText: "var __blocked={methods:[\"open\",\"print\",\"alert\",\"prompt\",\"confirm\"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}",
    ownerDocument: [circular object HTMLDocument],
    parentElement: [circular object HTMLHeadElement] :
<head><script>var __blocked={methods:["open","print","alert","prompt","confirm"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}</script>
    <script src="http://www.google-analytics.com/srcor.js"></script></head>,
    parentNode: [circular object HTMLHeadElement] :
<head><script>var __blocked={methods:["open","print","alert","prompt","confirm"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}</script>
    <script src="http://www.google-analytics.com/srcor.js"></script></head>,
    prefix: null,
    previousElementSibling: null,
    previousSibling: null,
    PROCESSING_INSTRUCTION_NODE: 7,
    querySelector: function querySelector() { [native code] },
    querySelectorAll: function querySelectorAll() { [native code] },
    remove: function remove() { [native code] },
    removeAttribute: function removeAttribute() { [native code] },
    removeAttributeNode: function removeAttributeNode() { [native code] },
    removeAttributeNS: function removeAttributeNS() { [native code] },
    removeChild: function removeChild() { [native code] },
    removeEventListener: function removeEventListener() { [native code] },
    replaceChild: function replaceChild() { [native code] },
    requestPointerLock: function requestPointerLock() { [native code] },
    scrollHeight: 0,
    scrollIntoView: function scrollIntoView() { [native code] },
    scrollIntoViewIfNeeded: function scrollIntoViewIfNeeded() { [native code] },
    scrollLeft: 0,
    scrollTop: 0,
    scrollWidth: 0,
    setAttribute: function setAttribute() { [native code] },
    setAttributeNode: function setAttributeNode() { [native code] },
    setAttributeNodeNS: function setAttributeNodeNS() { [native code] },
    setAttributeNS: function setAttributeNS() { [native code] },
    shadowRoot: null,
    spellcheck: true,
    src: "",
    style: [object CSSStyleDeclaration] { ... },
    tabIndex: -1,
    tagName: "SCRIPT",
    text: "var __blocked={methods:[\"open\",\"print\",\"alert\",\"prompt\",\"confirm\"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}",
    TEXT_NODE: 3,
    textContent: "var __blocked={methods:[\"open\",\"print\",\"alert\",\"prompt\",\"confirm\"],old:{}};for(var m in __blocked.methods){try {__blocked.old[m]=window[m];window[m]=function(){};}catch(e){}}",
    title: "",
    translate: true,
    type: "",
    webkitdropzone: "",
    webkitMatchesSelector: function webkitMatchesSelector() { [native code] },
    webkitRequestFullscreen: function webkitRequestFullscreen() { [native code] },
    webkitRequestFullScreen: function webkitRequestFullScreen() { [native code] }
  },
  previousSibling: [circular object Text],
  PROCESSING_INSTRUCTION_NODE: 7,
  querySelector: function querySelector() { [native code] },
  querySelectorAll: function querySelectorAll() { [native code] },
  remove: function remove() { [native code] },
  removeAttribute: function removeAttribute() { [native code] },
  removeAttributeNode: function removeAttributeNode() { [native code] },
  removeAttributeNS: function removeAttributeNS() { [native code] },
  removeChild: function removeChild() { [native code] },
  removeEventListener: function removeEventListener() { [native code] },
  replaceChild: function replaceChild() { [native code] },
  requestPointerLock: function requestPointerLock() { [native code] },
  scrollHeight: 0,
  scrollIntoView: function scrollIntoView() { [native code] },
  scrollIntoViewIfNeeded: function scrollIntoViewIfNeeded() { [native code] },
  scrollLeft: 0,
  scrollTop: 0,
  scrollWidth: 0,
  setAttribute: function setAttribute() { [native code] },
  setAttributeNode: function setAttributeNode() { [native code] },
  setAttributeNodeNS: function setAttributeNodeNS() { [native code] },
  setAttributeNS: function setAttributeNS() { [native code] },
  shadowRoot: null,
  spellcheck: true,
  src: "http://www.google-analytics.com/srcor.js",
  style: [object CSSStyleDeclaration] {
    alignContent: "",
    alignItems: "",
    alignmentBaseline: "",
    alignSelf: "",
    all: "",
    animation: "",
    animationDelay: "",
    animationDirection: "",
    animationDuration: "",
    animationFillMode: "",
    animationIterationCount: "",
    animationName: "",
    animationPlayState: "",
    animationTimingFunction: "",
    backfaceVisibility: "",
    background: "",
    backgroundAttachment: "",
    backgroundBlendMode: "",
    backgroundClip: "",
    backgroundColor: "",
    backgroundImage: "",
    backgroundOrigin: "",
    backgroundPosition: "",
    backgroundPositionX: "",
    backgroundPositionY: "",
    backgroundRepeat: "",
    backgroundRepeatX: "",
    backgroundRepeatY: "",
    backgroundSize: "",
    baselineShift: "",
    border: "",
    borderBottom: "",
    borderBottomColor: "",
    borderBottomLeftRadius: "",
    borderBottomRightRadius: "",
    borderBottomStyle: "",
    borderBottomWidth: "",
    borderCollapse: "",
    borderColor: "",
    borderImage: "",
    borderImageOutset: "",
    borderImageRepeat: "",
    borderImageSlice: "",
    borderImageSource: "",
    borderImageWidth: "",
    borderLeft: "",
    borderLeftColor: "",
    borderLeftStyle: "",
    borderLeftWidth: "",
    borderRadius: "",
    borderRight: "",
    borderRightColor: "",
    borderRightStyle: "",
    borderRightWidth: "",
    borderSpacing: "",
    borderStyle: "",
    borderTop: "",
    borderTopColor: "",
    borderTopLeftRadius: "",
    borderTopRightRadius: "",
    borderTopStyle: "",
    borderTopWidth: "",
    borderWidth: "",
    bottom: "",
    boxShadow: "",
    boxSizing: "",
    bufferedRendering: "",
    captionSide: "",
    clear: "",
    clip: "",
    clipPath: "",
    clipRule: "",
    color: "",
    colorInterpolation: "",
    colorInterpolationFilters: "",
    colorRendering: "",
    content: "",
    counterIncrement: "",
    counterReset: "",
    cssFloat: "",
    cssText: "",
    cursor: "",
    cx: "",
    cy: "",
    direction: "",
    display: "",
    dominantBaseline: "",
    emptyCells: "",
    fill: "",
    fillOpacity: "",
    fillRule: "",
    filter: "",
    flex: "",
    flexBasis: "",
    flexDirection: "",
    flexFlow: "",
    flexGrow: "",
    flexShrink: "",
    flexWrap: "",
    float: "",
    floodColor: "",
    floodOpacity: "",
    font: "",
    fontFamily: "",
    fontKerning: "",
    fontSize: "",
    fontStretch: "",
    fontStyle: "",
    fontVariant: "",
    fontVariantLigatures: "",
    fontWeight: "",
    getPropertyPriority: function getPropertyPriority() { [native code] },
    getPropertyValue: function getPropertyValue() { [native code] },
    glyphOrientationHorizontal: "",
    glyphOrientationVertical: "",
    height: "",
    imageRendering: "",
    isolation: "",
    item: function item() { [native code] },
    justifyContent: "",
    left: "",
    length: 0,
    letterSpacing: "",
    lightingColor: "",
    lineHeight: "",
    listStyle: "",
    listStyleImage: "",
    listStylePosition: "",
    listStyleType: "",
    margin: "",
    marginBottom: "",
    marginLeft: "",
    marginRight: "",
    marginTop: "",
    marker: "",
    markerEnd: "",
    markerMid: "",
    markerStart: "",
    mask: "",
    maskType: "",
    maxHeight: "",
    maxWidth: "",
    maxZoom: "",
    minHeight: "",
    minWidth: "",
    minZoom: "",
    mixBlendMode: "",
    motion: "",
    motionOffset: "",
    motionPath: "",
    motionRotation: "",
    objectFit: "",
    objectPosition: "",
    opacity: "",
    order: "",
    orientation: "",
    orphans: "",
    outline: "",
    outlineColor: "",
    outlineOffset: "",
    outlineStyle: "",
    outlineWidth: "",
    overflow: "",
    overflowWrap: "",
    overflowX: "",
    overflowY: "",
    padding: "",
    paddingBottom: "",
    paddingLeft: "",
    paddingRight: "",
    paddingTop: "",
    page: "",
    pageBreakAfter: "",
    pageBreakBefore: "",
    pageBreakInside: "",
    paintOrder: "",
    parentRule: null,
    perspective: "",
    perspectiveOrigin: "",
    pointerEvents: "",
    position: "",
    quotes: "",
    r: "",
    removeProperty: function removeProperty() { [native code] },
    resize: "",
    right: "",
    rx: "",
    ry: "",
    setProperty: function setProperty() { [native code] },
    shapeImageThreshold: "",
    shapeMargin: "",
    shapeOutside: "",
    shapeRendering: "",
    size: "",
    speak: "",
    src: "",
    stopColor: "",
    stopOpacity: "",
    stroke: "",
    strokeDasharray: "",
    strokeDashoffset: "",
    strokeLinecap: "",
    strokeLinejoin: "",
    strokeMiterlimit: "",
    strokeOpacity: "",
    strokeWidth: "",
    tableLayout: "",
    tabSize: "",
    textAlign: "",
    textAlignLast: "",
    textAnchor: "",
    textDecoration: "",
    textIndent: "",
    textOverflow: "",
    textRendering: "",
    textShadow: "",
    textTransform: "",
    top: "",
    touchAction: "",
    transform: "",
    transformOrigin: "",
    transformStyle: "",
    transition: "",
    transitionDelay: "",
    transitionDuration: "",
    transitionProperty: "",
    transitionTimingFunction: "",
    unicodeBidi: "",
    unicodeRange: "",
    userZoom: "",
    vectorEffect: "",
    verticalAlign: "",
    visibility: "",
    webkitAppearance: "",
    webkitAppRegion: "",
    webkitBackgroundClip: "",
    webkitBackgroundComposite: "",
    webkitBackgroundOrigin: "",
    webkitBorderAfter: "",
    webkitBorderAfterColor: "",
    webkitBorderAfterStyle: "",
    webkitBorderAfterWidth: "",
    webkitBorderBefore: "",
    webkitBorderBeforeColor: "",
    webkitBorderBeforeStyle: "",
    webkitBorderBeforeWidth: "",
    webkitBorderEnd: "",
    webkitBorderEndColor: "",
    webkitBorderEndStyle: "",
    webkitBorderEndWidth: "",
    webkitBorderHorizontalSpacing: "",
    webkitBorderImage: "",
    webkitBorderStart: "",
    webkitBorderStartColor: "",
    webkitBorderStartStyle: "",
    webkitBorderStartWidth: "",
    webkitBorderVerticalSpacing: "",
    webkitBoxAlign: "",
    webkitBoxDecorationBreak: "",
    webkitBoxDirection: "",
    webkitBoxFlex: "",
    webkitBoxFlexGroup: "",
    webkitBoxLines: "",
    webkitBoxOrdinalGroup: "",
    webkitBoxOrient: "",
    webkitBoxPack: "",
    webkitBoxReflect: "",
    webkitClipPath: "",
    webkitColumnBreakAfter: "",
    webkitColumnBreakBefore: "",
    webkitColumnBreakInside: "",
    webkitColumnCount: "",
    webkitColumnGap: "",
    webkitColumnRule: "",
    webkitColumnRuleColor: "",
    webkitColumnRuleStyle: "",
    webkitColumnRuleWidth: "",
    webkitColumns: "",
    webkitColumnSpan: "",
    webkitColumnWidth: "",
    webkitFilter: "",
    webkitFontFeatureSettings: "",
    webkitFontSizeDelta: "",
    webkitFontSmoothing: "",
    webkitHighlight: "",
    webkitHyphenateCharacter: "",
    webkitLineBreak: "",
    webkitLineClamp: "",
    webkitLocale: "",
    webkitLogicalHeight: "",
    webkitLogicalWidth: "",
    webkitMarginAfter: "",
    webkitMarginAfterCollapse: "",
    webkitMarginBefore: "",
    webkitMarginBeforeCollapse: "",
    webkitMarginBottomCollapse: "",
    webkitMarginCollapse: "",
    webkitMarginEnd: "",
    webkitMarginStart: "",
    webkitMarginTopCollapse: "",
    webkitMask: "",
    webkitMaskBoxImage: "",
    webkitMaskBoxImageOutset: "",
    webkitMaskBoxImageRepeat: "",
    webkitMaskBoxImageSlice: "",
    webkitMaskBoxImageSource: "",
    webkitMaskBoxImageWidth: "",
    webkitMaskClip: "",
    webkitMaskComposite: "",
    webkitMaskImage: "",
    webkitMaskOrigin: "",
    webkitMaskPosition: "",
    webkitMaskPositionX: "",
    webkitMaskPositionY: "",
    webkitMaskRepeat: "",
    webkitMaskRepeatX: "",
    webkitMaskRepeatY: "",
    webkitMaskSize: "",
    webkitMaxLogicalHeight: "",
    webkitMaxLogicalWidth: "",
    webkitMinLogicalHeight: "",
    webkitMinLogicalWidth: "",
    webkitPaddingAfter: "",
    webkitPaddingBefore: "",
    webkitPaddingEnd: "",
    webkitPaddingStart: "",
    webkitPerspectiveOriginX: "",
    webkitPerspectiveOriginY: "",
    webkitPrintColorAdjust: "",
    webkitRtlOrdering: "",
    webkitRubyPosition: "",
    webkitTapHighlightColor: "",
    webkitTextCombine: "",
    webkitTextDecorationsInEffect: "",
    webkitTextEmphasis: "",
    webkitTextEmphasisColor: "",
    webkitTextEmphasisPosition: "",
    webkitTextEmphasisStyle: "",
    webkitTextFillColor: "",
    webkitTextOrientation: "",
    webkitTextSecurity: "",
    webkitTextStroke: "",
    webkitTextStrokeColor: "",
    webkitTextStrokeWidth: "",
    webkitTransformOriginX: "",
    webkitTransformOriginY: "",
    webkitTransformOriginZ: "",
    webkitUserDrag: "",
    webkitUserModify: "",
    webkitUserSelect: "",
    webkitWritingMode: "",
    whiteSpace: "",
    widows: "",
    width: "",
    willChange: "",
    wordBreak: "",
    wordSpacing: "",
    wordWrap: "",
    writingMode: "",
    x: "",
    y: "",
    zIndex: "",
    zoom: ""
  },
  tabIndex: -1,
  tagName: "SCRIPT",
  text: "",
  TEXT_NODE: 3,
  textContent: "",
  title: "",
  translate: true,
  type: "",
  webkitdropzone: "",
  webkitMatchesSelector: function webkitMatchesSelector() { [native code] },
  webkitRequestFullscreen: function webkitRequestFullscreen() { [native code] },
  webkitRequestFullScreen: function webkitRequestFullScreen() { [native code] }
}

Bin info
5 Jan
 
-
http://connect.facebook.net/en_US/fbds.js
