-By Muhammad Adi Nugroho,S.Adm.Neg.:
-Via My Notepad (HTML Editor):
-Sources:
-Content:-
chrome-extension://ooebklgpfnbcnpokahmdidgbmlcdepkm/js/engine_loader_v2.js
function IsIE(){var a=navigator.userAgent.toLowerCase(),b=a.indexOf("msie")>-1||navigator.appName.toLowerCase().indexOf("microsoft internet explorer")>-1||!!window.ActiveXObject||"ActiveXObject"in window;return b}var $gjjq,GJ_MINI_BAR_ENGINE={m_strGJGuid:"",m_isIE:!1,m_nIEVersion:-1,m_nBID:0,m_ElementMain:null,m_Timer:null,m_oricontextmenu:null,index:0,sindex:0,cindex:0,timer:null,shader_timer:null,circle_timer:null,bclick:!1,bPostAni:!1,bhover:!1,bHasShownSTip:!1,tipstimer:null,cl_timer:null,number_timer:null,objAdcJson:null,objAdcount:"",bClear:!1,hoverTime:0,numberTime:0,nAdCount:0,nWeekCount:0,nJustNowCount:0,nJustNowCountTemp:0,bJustNowShowd:!1,nUseCount:0,bIsClicked:0,conf:{strDaohangFrameId:"gj_SafeDaohang",strAddFrameId:"gj_SafeDaohangAdd",strDaohangDivId:"gj_NavDiv",strDaohangAddDivId:"gj_NavAddDiv",strDaohangHotNews:"gj_HotNews",strDaohangJSId:"adc_loader",strMiniId:"gj_mini",strShardId:"gj_shard",strCircleId:"gj_circle",strBarId:"gj_bar_left",strMiniImgId:"gj_MiniImg",nGetReportMaxCnt:1024,strReoprtCgi:"http://c.gj.qq.com/fcgi-bin/microreport",version:12101032,nReportInsertJsId:0,nReportHoveredId:1,nReportClickUrlId:2,nReportAddUrl:3,nReportDelUrl:4,nReportShowHotNews:5,nReportInsertAdc:10,nReportShowAdc:11,nReportClickAdc:12,nReportRClickAdc:13,nReportCompleteAdc:14,nReportCompleteAuto:15,nReportTipsJustNow:31,nReportTipsClickMe:32,nReportTipsWeekShow:33,nReportTipsNoAd:34},Log:function(a){},getTop:function(a){var b=a.offsetTop;return null!=a.offsetParent&&(b+=this.getTop(a.offsetParent)),b},getLeft:function(a){var b=a.offsetLeft;return null!=a.offsetParent&&(b+=this.getLeft(a.offsetParent)),b},getScrollTop:function(){var a=document.documentElement.scrollTop||window.pageYOffset||document.body.scrollTop;return a},tipstime_handle:function(){GJ_MINI_BAR_ENGINE.hoverTime++,GJ_MINI_BAR_ENGINE.hoverTime>23&&(clearInterval(GJ_MINI_BAR_ENGINE.tipstimer),GJ_MINI_BAR_ENGINE.bHasShownSTip||GJ_MINI_BAR_ENGINE.bClear||(GJ_MINI_BAR_ENGINE.bHasShownSTip=!GJ_MINI_BAR_ENGINE.bHasShownSTip,GJ_MINI_BAR_ENGINE.ShowTips()))},number_handle:function(){GJ_MINI_BAR_ENGINE.numberTime++,GJ_MINI_BAR_ENGINE.numberTime>23&&clearInterval(GJ_MINI_BAR_ENGINE.number_timer);var a=document.getElementById("gj_justnow_num");GJ_MINI_BAR_ENGINE.nJustNowCountTemp<GJ_MINI_BAR_ENGINE.nJustNowCount&&(a.innerText=GJ_MINI_BAR_ENGINE.nJustNowCountTemp.toString(),GJ_MINI_BAR_ENGINE.nJustNowCountTemp++)},hover_handler:function(){var a=document.getElementById("gj_mini"),b=0;b=-58*GJ_MINI_BAR_ENGINE.index,a.style.backgroundPosition=b+"px 0px",GJ_MINI_BAR_ENGINE.index++,GJ_MINI_BAR_ENGINE.index>15&&clearInterval(GJ_MINI_BAR_ENGINE.timer)},animationMuti:function(a){elemObj=document.getElementById(a),GJ_MINI_BAR_ENGINE.animationElement(elemObj)},animationElement:function(a){var b,c,d,e,f,g,h;elemObj=a,elemObj&&(b=new jsAnimManager,elemObj.style.width=elemObj.offsetWidth+"px",elemObj.style.height=elemObj.offsetHeight+"px",elemObj.style.overflow="hidden",c=this.getLeft(elemObj),d=this.getTop(elemObj),c+=elemObj.offsetWidth/2,d+=elemObj.offsetHeight/2,b.registerElemPosition(elemObj,!0),elemObj.setPosition(-(document.body.offsetWidth/2)+c,d),e=b.createAnimElemObject(a),f=b.createAnimElemObject(a),g=150*Math.floor(10*Math.random()+1),h=document.getElementById("gj_mini"),e.add({property:Prop.position,to:new Pos(document.body.offsetWidth/2-10-22-10,this.getTop(h)+22),duration:g,ease:jsAnimEase.parabolicPos}),f.add({property:Prop.dimension,to:new Dim(0,0),duration:g+100,ease:jsAnimEase.parabolicPos,onComplete:function(){elemObj=a,elemObj.style.zIndex=0,elemObj.parentNode.removeChild(elemObj)}}))},calc_dis:function(a){if(a){var b=GJ_MINI_BAR_ENGINE.getLeft(a);b+600>GJ_MINI_BAR_ENGINE.getLeft(document.getElementById("gj_mini"))&&(GJ_MINI_BAR_ENGINE.DrawCircle(),clearInterval(GJ_MINI_BAR_ENGINE.cl_timer))}},mouseover_handler:function(){var a=document.getElementById("gj_mini"),b=0;b=-58*GJ_MINI_BAR_ENGINE.index,a.style.backgroundPosition=b+"px 0px",GJ_MINI_BAR_ENGINE.index--,GJ_MINI_BAR_ENGINE.index<0&&clearInterval(GJ_MINI_BAR_ENGINE.timer)},mousedown_handler:function(){var a=document.getElementById("gj_mini"),b=0;b=-58*GJ_MINI_BAR_ENGINE.index,a.style.backgroundPosition=b+"px 0px",GJ_MINI_BAR_ENGINE.index++,GJ_MINI_BAR_ENGINE.index>6&&clearInterval(GJ_MINI_BAR_ENGINE.timer)},mouseup_handler:function(){var a=document.getElementById("gj_mini"),b=0;b=-58*GJ_MINI_BAR_ENGINE.index,a.style.backgroundPosition=b+"px 0px",GJ_MINI_BAR_ENGINE.index++,GJ_MINI_BAR_ENGINE.index>91&&(GJ_MINI_BAR_ENGINE.index=0,clearInterval(GJ_MINI_BAR_ENGINE.timer),setTimeout("GJ_MINI_BAR_ENGINE.Reset()",2e3)),17==GJ_MINI_BAR_ENGINE.index&&GJ_MINI_BAR_ENGINE.StartShard(),57==GJ_MINI_BAR_ENGINE.index&&GJ_MINI_BAR_ENGINE.StopShard(),25==GJ_MINI_BAR_ENGINE.index&&GJ_MINI_BAR_ENGINE.collect(),91==GJ_MINI_BAR_ENGINE.index&&($gjjq("#gj_shard").hide(),$gjjq("#gj_bar_left").animate({width:150},"slow"))},filterpost_handler:function(){var a=document.getElementById("gj_mini"),b=0;b=-58*GJ_MINI_BAR_ENGINE.index,a.style.backgroundPosition=b+"px 0px",GJ_MINI_BAR_ENGINE.index++,GJ_MINI_BAR_ENGINE.index>91&&(GJ_MINI_BAR_ENGINE.index=0,clearInterval(GJ_MINI_BAR_ENGINE.timer),setTimeout("GJ_MINI_BAR_ENGINE.Reset()",50)),17==GJ_MINI_BAR_ENGINE.index&&GJ_MINI_BAR_ENGINE.StartShard(),57==GJ_MINI_BAR_ENGINE.index&&GJ_MINI_BAR_ENGINE.StopShard(),91==GJ_MINI_BAR_ENGINE.index&&$gjjq("#gj_shard").hide()},collect_ani_handler:function(){GJ_MINI_BAR_ENGINE.collect()},shard_handle:function(){var a=document.getElementById("gj_shard"),b=0;b=-200*GJ_MINI_BAR_ENGINE.sindex,a.style.backgroundPosition=b+"px 0px",GJ_MINI_BAR_ENGINE.sindex++,GJ_MINI_BAR_ENGINE.sindex>39&&clearInterval(GJ_MINI_BAR_ENGINE.shader_timer)},circle_handle:function(){var a=document.getElementById("gj_circle"),b=0;b=-58*GJ_MINI_BAR_ENGINE.cindex,a.style.backgroundPosition=b+"px 1px",GJ_MINI_BAR_ENGINE.cindex++,GJ_MINI_BAR_ENGINE.cindex>17&&(GJ_MINI_BAR_ENGINE.cindex=0,clearInterval(GJ_MINI_BAR_ENGINE.circle_timer),$gjjq("#gj_circle").hide())},reset_handle:function(){var a=document.getElementById("gj_mini"),b=0;b=-58*GJ_MINI_BAR_ENGINE.index,a.style.backgroundPosition=b+"px 0px",GJ_MINI_BAR_ENGINE.index++,GJ_MINI_BAR_ENGINE.index>25&&(GJ_MINI_BAR_ENGINE.index=0,clearInterval(GJ_MINI_BAR_ENGINE.timer),GJ_MINI_BAR_ENGINE.bclick=!1,GJ_MINI_BAR_ENGINE.bPostAni?GJ_MINI_BAR_ENGINE.bPostAni=!1:GJ_MINI_BAR_ENGINE.bClear=!0,$gjjq("#gj_mini").css({"background-position":"0px 0px","background-image":"url(http://s.pc.qq.com/navigate/adc/v2/hover-ok.png)"}),$gjjq("#gj_bar_left").animate({width:0},"slow"))},breathe_handle:function(){var a=document.getElementById("gj_mini"),b=0;b=-58*GJ_MINI_BAR_ENGINE.index,a.style.backgroundPosition=b+"px 0px",GJ_MINI_BAR_ENGINE.index++,GJ_MINI_BAR_ENGINE.index>36&&(GJ_MINI_BAR_ENGINE.index=0,clearInterval(GJ_MINI_BAR_ENGINE.timer),setTimeout("GJ_MINI_BAR_ENGINE.StartBreathe()",300))},DrawCircle:function(){GJ_MINI_BAR_ENGINE.cindex=0,$gjjq("#gj_circle").show(),GJ_MINI_BAR_ENGINE.circle_timer=setInterval(GJ_MINI_BAR_ENGINE.circle_handle,41.6)},StartShard:function(){GJ_MINI_BAR_ENGINE.sindex=0;var a=$gjjq("#gj_shard");a.css({display:"block"}),GJ_MINI_BAR_ENGINE.shader_timer=setInterval(GJ_MINI_BAR_ENGINE.shard_handle,41.6)},StopShard:function(){$gjjq("#gj_shard").hide()},StartBreathe:function(){clearInterval(GJ_MINI_BAR_ENGINE.timer),GJ_MINI_BAR_ENGINE.index=0,$gjjq("#gj_mini").css({"background-position":"0px 0px","background-image":"url(http://s.pc.qq.com/navigate/adc/v2/breathe.png)"}),GJ_MINI_BAR_ENGINE.timer=setInterval(GJ_MINI_BAR_ENGINE.breathe_handle,41.6)},initVelocity:function(){},InitJq:function(){$gjjq=$},Reset:function(){clearInterval(GJ_MINI_BAR_ENGINE.timer),GJ_MINI_BAR_ENGINE.index=0,$gjjq("#gj_mini").css({"background-position":"0px 0px","background-image":"url(http://s.pc.qq.com/navigate/adc/v2/over_ok.png)"}),GJ_MINI_BAR_ENGINE.timer=setInterval(GJ_MINI_BAR_ENGINE.reset_handle,41.6)},setAdcJson:function(a){var c,d,e,f,b=JSON.parse(a);if(b.bwhite||!b.bcss)return!1;for(b.css_value=b.css_value.replace("\n",""),b.css_value=b.css_value.replace('],"}',']"}'),","==b.css_value.charAt(b.css_value.length-1)&&(b.css_value=b.css_value.substring(0,b.css_value.length-1)),b.bexcept&&(b.except_value=b.except_value.replace("\n",""),b.except_value=b.except_value.replace('],"}',']"}'),","==b.except_value.charAt(b.except_value.length-1)&&(b.except_value=b.except_value.substring(0,b.except_value.length-1))),GJ_MINI_BAR_ENGINE.objAdcJson=b,c=GJ_MINI_BAR_ENGINE.objAdcJson.css_value.split(","),d=new Array,e=0;e<c.length;e++)c[e].length<1||d.push(c[e]);return b.bhit?(GJ_MINI_BAR_ENGINE.hitDomAndContinue(!0),!0):(f=d.join(","),$gjjq(f).size()>0?(GJ_MINI_BAR_ENGINE.hitDomAndContinue(!1),void 0):!1)},hitDomAndContinue:function(a){GJ_MINI_BAR_ENGINE.AdjustZindex(),GJ_MINI_BAR_ENGINE.InsertCss(),GJ_MINI_BAR_ENGINE.InsertDiv(),GJ_MINI_BAR_ENGINE.InsertFrame(),GJ_MINI_BAR_ENGINE.InsertMini(),GJ_MINI_BAR_ENGINE.InsertShard(),GJ_MINI_BAR_ENGINE.InsertCircle(),GJ_MINI_BAR_ENGINE.InsertBar(),setTimeout(" GJ_MINI_BAR_ENGINE.getAdCount()",1e4),setTimeout("GJ_MINI_BAR_ENGINE.BindJqueryEvent()",100),a?(setTimeout(" GJ_MINI_BAR_ENGINE.RunAdFilterPostAni()",100),GJ_MINI_BAR_ENGINE.reportCompleteAuto()):setTimeout(" GJ_MINI_BAR_ENGINE.RunAni()",100)},getAdCount:function(){var a="";IsIE()?"object"==typeof window.TsCmcObj&&"undefined"!=typeof window.TsCmcObj.GetAdCount&&(a=window.TsCmcObj.GetAdCount(),a.length>0&&(GJ_MINI_BAR_ENGINE.objAdcount=a,GJ_MINI_BAR_ENGINE.ShowWeekTips(!0))):chrome.extension.sendRequest({cmd:"getADCCount",id:0},function(a){a.count.length>0&&(GJ_MINI_BAR_ENGINE.objAdcount=a.count,GJ_MINI_BAR_ENGINE.ShowWeekTips(!0))})},getAdcJson:function(){var a="";return null!=GJ_MINI_BAR_ENGINE.objAdcJson&&GJ_MINI_BAR_ENGINE.objAdcJson.bcss?!0:(IsIE()?"object"==typeof window.TsCmcObj&&"undefined"!=typeof window.TsCmcObj.GetAdRule&&"unknown"!=typeof window.TsCmcObj.GetAdRule&&(a=window.TsCmcObj.GetAdRule(window.location.href),GJ_MINI_BAR_ENGINE.setAdcJson(a)):chrome.extension.sendRequest({cmd:"getADCJson",url:location.href},function(a){a&&(GJ_MINI_BAR_ENGINE.Log(a),GJ_MINI_BAR_ENGINE.setAdcJson(a.rule))}),void 0)},collect:function(){var b,c,d,e,f,g,h,i,j,k;if(GJ_MINI_BAR_ENGINE.objAdcJson&&!GJ_MINI_BAR_ENGINE.objAdcJson.bwhite&&GJ_MINI_BAR_ENGINE.objAdcJson.bcss){for(b=new Array,GJ_MINI_BAR_ENGINE.objAdcJson.bexcept&&(b=$gjjq(GJ_MINI_BAR_ENGINE.objAdcJson.except_value)),c=GJ_MINI_BAR_ENGINE.objAdcJson.css_value.split(","),d=c.length,e=new Array,f=new Array,g=0;d>g;g++)c[g].length<1||(c[g].indexOf("background")>0?f.push(c[g]):e.push(c[g]));h=e.join(","),i=f.join(","),i.length>0&&$gjjq(i).each(function(){$gjjq(this).css("background","url()")}),$gjjq(h).each(function(a,c){for(var d=$gjjq(this),e=b.length;e--;)if(b[e]===c)return!0;return a>10?!0:(d.css({"z-index":2147483647,position:"fixed",overflow:"hidden",top:$gjjq(this).offset().top+"px",left:$gjjq(this).offset().left+"px",width:$gjjq(this).width()+"px",height:$gjjq(this).height()+"px"}),void 0)}),j=document.body.offsetWidth-10-22-15,k=GJ_MINI_BAR_ENGINE.getTop($gjjq("#gj_mini").get(0))+22,$gjjq(h).each(function(a,c){for(var e,f,d=b.length;d--;)if(b[d]===c)return!0;return GJ_MINI_BAR_ENGINE.nAdCount++,a>10?($gjjq(this).hide(),!0):(e=150*Math.floor(10*Math.random()+1),f=$gjjq(this),f.velocity({top:k,left:j,width:20,height:20},e,"easeInOutExpo",function(){$gjjq(this).hide()}),1==a&&(GJ_MINI_BAR_ENGINE.cl_timer=setInterval(GJ_MINI_BAR_ENGINE.calc_dis,20,$gjjq(this).get(0))),void 0)}),GJ_MINI_BAR_ENGINE.UpdateBar(),IsIE()?"undefined"!=typeof window.TsCmcObj.ADCallBack&&"unknown"!=typeof window.TsCmcObj.ADCallBack&&window.TsCmcObj.ADCallBack(window.location.href,GJ_MINI_BAR_ENGINE.nAdCount):chrome.extension.sendRequest({cmd:"ADCallBack",url:window.location.href,count:GJ_MINI_BAR_ENGINE.nAdCount},function(){}),GJ_MINI_BAR_ENGINE.reportCompleteAdc(d,GJ_MINI_BAR_ENGINE.nAdCount)}},HideAllTip:function(){GJ_MINI_BAR_ENGINE.HideTips(),GJ_MINI_BAR_ENGINE.HideNoAdTips(),GJ_MINI_BAR_ENGINE.ShowJustNowTips(!1),GJ_MINI_BAR_ENGINE.ShowWeekTips(!1)},BindJqueryEvent:function(){this.m_oricontextmenu=document.oncontextmenu,$gjjq("#gj_shard").hover(function(){GJ_MINI_BAR_ENGINE.bPostAni&&GJ_MINI_BAR_ENGINE.objAdcJson.bhit&&GJ_MINI_BAR_ENGINE.ShowJustNowTips(!0)},function(){}),$gjjq("#gj_mini").hover(function(){GJ_MINI_BAR_ENGINE.bclick||GJ_MINI_BAR_ENGINE.objAdcJson.bhit&&!GJ_MINI_BAR_ENGINE.bJustNowShowd||(clearInterval(GJ_MINI_BAR_ENGINE.timer),GJ_MINI_BAR_ENGINE.index=0,$gjjq(this).css("background-image","url(http://s.pc.qq.com/navigate/adc/v2/hover-ok.png)"),GJ_MINI_BAR_ENGINE.timer=setInterval(GJ_MINI_BAR_ENGINE.hover_handler,41.6),GJ_MINI_BAR_ENGINE.hoverTime=0,GJ_MINI_BAR_ENGINE.tipstimer=setInterval(GJ_MINI_BAR_ENGINE.tipstime_handle,40)),!GJ_MINI_BAR_ENGINE.bJustNowShowd&&GJ_MINI_BAR_ENGINE.objAdcJson.bhit&&GJ_MINI_BAR_ENGINE.ShowJustNowTips(!0)},function(){GJ_MINI_BAR_ENGINE.bclick||(GJ_MINI_BAR_ENGINE.index=14,clearInterval(GJ_MINI_BAR_ENGINE.timer),$gjjq(this).css("background-image","url(http://s.pc.qq.com/navigate/adc/v2/hover-ok.png)"),GJ_MINI_BAR_ENGINE.timer=setInterval(GJ_MINI_BAR_ENGINE.mouseover_handler,41.6)),clearInterval(GJ_MINI_BAR_ENGINE.tipstimer),GJ_MINI_BAR_ENGINE.HideAllTip(),document.oncontextmenu=GJ_MINI_BAR_ENGINE.m_oricontextmenu}),$gjjq("#gj_mini").mousedown(function(){GJ_MINI_BAR_ENGINE.bclick||(clearInterval(GJ_MINI_BAR_ENGINE.timer),GJ_MINI_BAR_ENGINE.index=0,$gjjq(this).css({"background-position":"0px 0px","background-image":"url(http://s.pc.qq.com/navigate/adc/v2/click_down.png)"}),clearInterval(GJ_MINI_BAR_ENGINE.tipstimer),GJ_MINI_BAR_ENGINE.timer=setInterval(GJ_MINI_BAR_ENGINE.mousedown_handler,41.6))}),$gjjq("#gj_mini").mouseup(function(a){return GJ_MINI_BAR_ENGINE.HideTips(),GJ_MINI_BAR_ENGINE.HideNoAdTips(),3==a.which?(document.oncontextmenu=function(){return!1},GJ_MINI_BAR_ENGINE.HideAllTip(),GJ_MINI_BAR_ENGINE.ShowPannel(!0),!1):(1==a.which&&(GJ_MINI_BAR_ENGINE.bIsClicked=1,GJ_MINI_BAR_ENGINE.reportClickAdc(),GJ_MINI_BAR_ENGINE.AutoCollect()),void 0)})},onMiniMouseOver:function(){var b=document.getElementById("gj_NavDiv"),c=document.getElementById("gj_MiniImg");b.style.display="block",c.setAttribute("src","http://s.pc.qq.com/navigate/js2/nav_mini_hover.png")},onFrameMouseOver:function(){var b=document.getElementById("gj_NavDiv"),c=document.getElementById("gj_MiniImg");b.style.display="block",c.setAttribute("src","http://s.pc.qq.com/navigate/js2/nav_mini_hover.png")},onMiniMouseOut:function(){var c,b=document.getElementById("gj_NavDiv");b.style.display="none",c=document.getElementById("gj_MiniImg"),c.setAttribute("src","http://s.pc.qq.com/navigate/js2/nav_mini.png")},onDivMouseOver:function(){var c,b=document.getElementById("gj_NavDiv");b.style.display="none",c=document.getElementById("gj_MiniImg"),c.setAttribute("src","http://s.pc.qq.com/navigate/js2/nav_mini.png")},isIEBrowser:function(){var c,a={isIE:!1,nVersion:-1},b=navigator.userAgent.toLowerCase();return a.isIE=b.indexOf("msie")>-1||navigator.appName.toLowerCase().indexOf("microsoft internet explorer")>-1||!!window.ActiveXObject||"ActiveXObject"in window,a.isIE&&(c=null,(c=b.match(/rv:([\d.]+)\) like gecko/))?a.nVersion=parseInt(c[1]):(c=b.match(/msie ([\d.]+)/))?a.nVersion=parseInt(c[1]):-1),a},reportInsertJs:function(){GJ_MINI_BAR_ENGINE.report(GJ_MINI_BAR_ENGINE.conf.nReportInsertAdc,!0,{})},reportShowAdc:function(){GJ_MINI_BAR_ENGINE.report(GJ_MINI_BAR_ENGINE.conf.nReportShowAdc,!0,{})},reportClickAdc:function(){GJ_MINI_BAR_ENGINE.report(GJ_MINI_BAR_ENGINE.conf.nReportClickAdc,!0,{})},reportRClickAdc:function(){GJ_MINI_BAR_ENGINE.report(GJ_MINI_BAR_ENGINE.conf.nReportRClickAdc,!0,{})},ReportTipsJustNow:function(){GJ_MINI_BAR_ENGINE.report(GJ_MINI_BAR_ENGINE.conf.nReportTipsJustNow,!0,{})},ReportTipsClickMe:function(){GJ_MINI_BAR_ENGINE.report(GJ_MINI_BAR_ENGINE.conf.nReportTipsClickMe,!0,{})},ReportTipsWeekShow:function(){GJ_MINI_BAR_ENGINE.report(GJ_MINI_BAR_ENGINE.conf.nReportTipsWeekShow,!0,{})},ReportTipsNoAd:function(){GJ_MINI_BAR_ENGINE.report(GJ_MINI_BAR_ENGINE.conf.nReportTipsNoAd,!0,{})},reportCompleteAdc:function(a,b){var c={};c.ad_found=a,c.ad_collect=b,c.reserve2=GJ_MINI_BAR_ENGINE.nUseCount,c.reserve4=GJ_MINI_BAR_ENGINE.bIsClicked,GJ_MINI_BAR_ENGINE.report(GJ_MINI_BAR_ENGINE.conf.nReportCompleteAdc,!0,c)},reportCompleteAuto:function(){GJ_MINI_BAR_ENGINE.report(GJ_MINI_BAR_ENGINE.conf.nReportCompleteAuto,!0,{})},report:function(a,b,c){var d,e,f,g,h,i;if(void 0!==a){d=function(a,b,c){for(var d in b)!b.hasOwnProperty(d)||a.hasOwnProperty(d)&&!c||(a[d]=b[d])},e={},e.gjguid=GJ_MINI_BAR_ENGINE.m_strGJGuid,e.type=a,e.reserve1="2",e.bid=GJ_MINI_BAR_ENGINE.m_nBID,e.rand=Math.random(),e.refer=encodeURIComponent(location.href),e.reserve3=GJ_MINI_BAR_ENGINE.conf.version,d(e,c),f=0;for(g in e)f+=g.toString().length+e[g].toString().length+2;c&&f>this.conf.nGetReportMaxCnt&&(h="&cut=1",i=f-this.conf.nGetReportMaxCnt,e.refer.toString().length>=i+h.length&&(e.refer=e.refer.substr(0,e.refer.toString().length-i-h.length)),e.cut="1"),this.getReport(this.conf.strReoprtCgi,e,this.conf.nGetReportMaxCnt,b)}},getReport:function(a,b,c,d){var e,f,g,h,i;if(void 0===a||void 0===b||""==a)return 0;e="",f="?";for(g in b)e+=f+g+"="+b[g].toString(),f="&";return""==e?0:(h=a+e,"number"==typeof c&&h.length>c&&(h=h.substr(0,c)),d?(i=new Image(1,1),i.src=h,i.onerror=i.onload=null,i.complete):this.sendAjaxRequest(h),h.length)},addEvent:function(a,b,c){return a.addEventListener?(a.addEventListener(b,c,!1),!0):a.attachEvent?(a.attachEvent("on"+b,c),!0):!1},InsertMini:function(){var a=document.getElementsByTagName("body")[0],b=document.createElement("div");b.setAttribute("id",this.conf.strMiniId),b.style.cssText="right: 10px; bottom: 50px; position: fixed; z-index:  2147483640;",document.getElementById(this.conf.strMiniId)||a.appendChild(b)},InsertShard:function(){var a=document.getElementsByTagName("body")[0],b=document.createElement("div");b.setAttribute("id",this.conf.strShardId),b.style.cssText="right: -70px; bottom: -20px; position: fixed; z-index: 2147483643;",document.getElementById(this.conf.strShardId)||a.appendChild(b)},InsertCss:function(){var a='#gj_mini{background-image:url(http://s.pc.qq.com/navigate/adc/v2/hover-ok.png);background-repeat:no-repeat;display:block;width:58px;height:58px;background-position:0 0}#gj_shard{background-image:url(http://s.pc.qq.com/navigate/adc/v2/suipian.png);background-repeat:no-repeat;display:none;width:200px;height:200px;background-position:0 0}#gj_circle{background-image:url(http://s.pc.qq.com/navigate/adc/v2/guangquan.png);background-repeat:no-repeat;display:none;width:58px;height:58px;background-position:0 0}#gj_bar_left{background: url(http://s.pc.qq.com/navigate/adc/v2/zuo.png) no-repeat; height:42px; width :0px; font-family: "Microsoft YaHei" ! important;overflow:hidden; display:block;}#gj_bar_left #tipstext{line-height:normal;padding-left: 20px;padding-top: 3px;font-size: 12px;padding-right: 10px;color: #fff;overflow:hidden;}#gj_bar_left span{font-size: 14px;font-weight: bold;overflow:hidden;}',b=document.createElement("style");b.type="text/css",b.styleSheet?b.styleSheet.cssText=a:b.innerHTML=a,document.getElementsByTagName("head")[0].appendChild(b)},InsertCircle:function(){var a=document.getElementsByTagName("body")[0],b=document.createElement("div");b.setAttribute("id",this.conf.strCircleId),b.style.cssText="right: 10px; bottom: 50px; position: fixed; z-index: 2147483642;",document.getElementById(this.conf.strCircleId)||a.appendChild(b)},InsertBar:function(){var a=document.getElementsByTagName("body")[0],b=document.createElement("div");b.setAttribute("id",this.conf.strBarId),b.style.cssText="right: 60px; bottom: 58px; position: fixed; z-index: 2147483640;",b.innerHTML='<div id= "tipstext" style="white-space:nowrap;font-size: 14px;font-weight: bold;overflow:hidden;">'+GJ_MINI_BAR_ENGINE.nAdCount+'个广告已降服</div><div id= "tipstext" style="color:#CFDFFE;overflow:hidden;padding-top:0px;white-space: nowrap;">可以清爽的上网了~</div>',document.getElementById(this.conf.strBarId)||a.appendChild(b)},UpdateBar:function(){var a=document.getElementById(GJ_MINI_BAR_ENGINE.conf.strBarId);a&&(a.innerHTML='<div id= "tipstext" style="white-space:nowrap;font-size: 14px;font-weight: bold;overflow:hidden;">'+GJ_MINI_BAR_ENGINE.nAdCount+'个广告已降服</div><div id= "tipstext" style="color:#CFDFFE;overflow:hidden;padding-top:0px;white-space: nowrap;">可以清爽的上网了~</div>')},InsertDiv:function(){var a=document.getElementsByTagName("body")[0],b=document.createElement("div");b.setAttribute("id",this.conf.strDaohangDivId),b.style.cssText="position: fixed;  z-index: 2147483640; right: 0px; width: 0px; height: 0px; bottom: 59px; display: block;",document.getElementById(this.conf.strDaohangDivId)||a.appendChild(b)},InsertFrame:function(){var a=document.createElement("iframe"),b=document.getElementById(this.conf.strDaohangDivId),c=encodeURIComponent(location.href);a.setAttribute("src","http://s.pc.qq.com/navigate/adc/v2/adcpage.html#"+GJ_MINI_BAR_ENGINE.m_strGJGuid+"#"+GJ_MINI_BAR_ENGINE.m_nBID+"#"+c),a.setAttribute("id",this.conf.strDaohangFrameId),a.style.cssText="position: fixed; z-index: 2147483640; right: 0px; width: 0px; height: 0px; bottom: 99px;border: 0px none;",a.setAttribute("frameBorder",0),a.setAttribute("scrolling","0"),a.setAttribute("width","100%"),a.setAttribute("height","100%"),a.setAttribute("noresize","noresize"),document.getElementById(this.conf.strDaohangFrameId)||b.appendChild(a)},IsDocument:function(){return!0},HidePannel:function(){GJ_MINI_BAR_ENGINE.ShowPannel(!1)},dhShowCustomItem:function(a){var b,c,d;try{switch(a){case 0:b=document.getElementById("gj_NavAddDiv"),b.style.display="none";break;case 1:b=document.getElementById("gj_NavAddDiv"),b.style.display="block";break;case 2:c=document.getElementById("gj_NavDiv"),c.style.display="block";break;case 12:d=document.getElementById("gj_NavDiv"),d.style.display="none";break;case 13:d=document.getElementById("gj_NavDiv"),d.style.display="none",d=document.getElementById("gj_mini"),d.style.display="none",d=document.getElementById("gj_shard"),d.style.display="none",d=document.getElementById("gj_circle"),d.style.display="none",d=document.getElementById("gj_bar_left"),d.style.display="none"}}catch(e){}},ShowTips:function(){if(!GJ_MINI_BAR_ENGINE.bclick){if(!document.getElementById("gj_adctipsmall_id")){var a=document.createElement("div");a.setAttribute("id","gj_adctipsmall_id"),a.setAttribute("class","gj_adctipsmall"),a.style.cssText='background: url(http://s.pc.qq.com/navigate/adc/v2/tips_small.png) no-repeat;height:39px;width :125px;font-family: "Microsoft YaHei" ! important;position: fixed;  z-index: 2147483647; right: 8px; bottom: 110px; display: block;',document.getElementsByTagName("body")[0].appendChild(a)}document.getElementById("gj_adctipsmall_id").innerHTML='<div style="line-height:normal;font-family:Microsoft YaHei;padding-left:8px;padding-top:8px;font-size:12px;padding-right:10px;color:#fff">广告爆棚！点我收</div>',document.getElementById("gj_adctipsmall_id").style.display="block",GJ_MINI_BAR_ENGINE.ReportTipsClickMe()}},ShowJustNowTips:function(a){var b,c;return a?(GJ_MINI_BAR_ENGINE.nJustNowCount>0||(GJ_MINI_BAR_ENGINE.nJustNowCount=Math.floor(20*Math.random()),document.getElementById("gj_autofilter_id")||(c=document.createElement("div"),c.setAttribute("id","gj_autofilter_id"),c.setAttribute("class","gj_autofilter"),c.style.cssText='background: url(http://s.pc.qq.com/navigate/adc/v2/img/t3.png) no-repeat;height:39px;width :234px;font-family: "Microsoft YaHei" ! important;position: fixed;  z-index: 2147483647; right: 8px; bottom: 110px; display: block;',document.getElementsByTagName("body")[0].appendChild(c)),document.getElementById("gj_autofilter_id").innerHTML='<div id="gj_justnow_num" style="width:20px;height:20px;font-weight: bold;line-height:normal;font-family:Microsoft YaHei;margin-left:143px;margin-top:8px;font-size:12px;margin-right:10px;color:#ff7f7f">0</div>',document.getElementById("gj_autofilter_id").style.display="block",GJ_MINI_BAR_ENGINE.numberTime=0,GJ_MINI_BAR_ENGINE.nJustNowCountTemp=0,GJ_MINI_BAR_ENGINE.number_timer=setInterval(GJ_MINI_BAR_ENGINE.number_handle,100),GJ_MINI_BAR_ENGINE.ReportTipsJustNow(),GJ_MINI_BAR_ENGINE.bJustNowShowd=!0),void 0):(b=document.getElementById("gj_autofilter_id"),b&&(b.style.display="none"),void 0)},ShowWeekTips:function(a){var b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t;if(!GJ_MINI_BAR_ENGINE.bclick){if(!a)return b=document.getElementById("gj_weektips_id"),b&&(b.style.display="none"),void 0;if(c=new Array,d=new Array,e=new Array,0!=GJ_MINI_BAR_ENGINE.objAdcount.length&&(f=JSON.parse(GJ_MINI_BAR_ENGINE.objAdcount),f.need_show)){for(g=0,h=0,i=0,j=0,k=4;k>=0;k--)l=new Date,l.setDate(l.getDate()-k),m=l.getMonth()+1,n=l.getDate(),o=m>9?"":"0",p=n>9?"":"0",q=o+m+"."+p+n,e.push(q),r=0,s=0,null!=f.days&&(f.days[""+q]?(r=f.days[""+q],i+=r):r=0),null!=f.days_auto&&(f.days_auto[""+q]?(s=f.days_auto[""+q],h+=s):s=0),r>j&&(j=r),c.push(r),d.push(s);g=i+h,document.getElementById("gj_weektips_id")||(t=document.createElement("div"),t.setAttribute("id","gj_weektips_id"),t.setAttribute("class","gj_gj_weektips"),t.style.cssText='background: url(http://s.pc.qq.com/navigate/adc/v2/img/t4.png) no-repeat;height:55px;width :204px;font-family: "Microsoft YaHei" ! important;position: fixed;  z-index: 2147483647; right: 8px; bottom: 110px; display: block;',document.getElementsByTagName("body")[0].appendChild(t)),document.getElementById("gj_weektips_id").innerHTML='<div style="padding-top:10px;float:right;width:14px;height:10px" onclick="document.getElementById(\'gj_weektips_id\').style.display=\'none\';"></div><div style="font-family:Microsoft YaHei;padding-top:26px;font-size:14px;"><span style="float:left;padding-left:20px;font-weight: bold;line-height:normal;font-size:12px;color:#ff7f7f">'+g+'</span><span style="float:right;font-weight: bold;line-height:normal;font-size:12px;color:#fff;padding-right:20px;"><a id="gj_open_pannel" style="font-weight: bold;line-height:normal;font-size:12px;color:#fff;" href="#" >查看详情</a></span></div>',document.getElementById("gj_weektips_id").style.display="block",document.getElementById("gj_open_pannel").onclick=function(){return GJ_MINI_BAR_ENGINE.ShowPannel(!0),GJ_MINI_BAR_ENGINE.HideAllTip(),!1},GJ_MINI_BAR_ENGINE.ReportTipsWeekShow()}}},ShowPannel:function(a){var e,f,b=0,c=0,d=0;a&&(b=440,c=393,d=255,GJ_MINI_BAR_ENGINE.reportRClickAdc()),e=document.getElementById("gj_NavDiv"),e.style.cssText="position: fixed;  z-index: 2147483640; right: 0px; width: "+d+"px; height: "+b+"px; bottom: 59px; display: block;",f=document.getElementById(GJ_MINI_BAR_ENGINE.conf.strDaohangFrameId),f.style.cssText="position: fixed; z-index: 2147483640; right: 0px; width: "+d+"px; height: "+c+"px; bottom: 99px;border: 0px none;"},ShowNoAdTips:function(){if(!document.getElementById("gj_adctipnoad_id")){var a=document.createElement("div");a.setAttribute("id","gj_adctipnoad_id"),a.setAttribute("class","gj_adctips"),a.style.cssText='background:url(http://s.pc.qq.com/navigate/adc/v2/tips_big.png) no-repeat;height:46px;width:165px;font-family:"Microsoft YaHei"!important;position: fixed;  z-index: 2147483647; right: 8px; bottom: 110px; display: block;',document.getElementsByTagName("body")[0].appendChild(a)}document.getElementById("gj_adctipnoad_id").innerHTML='<div style="line-height:normal;font-family: Microsoft YaHei;padding-left:8px;padding-top:3px;font-size:12px;padding-right:10px;color:#fff">没有小广告如何让我发功呢<br><span style="font-size:12px">右键一下</span> 有惊喜哦!</div>',document.getElementById("gj_adctipnoad_id").style.display="block",GJ_MINI_BAR_ENGINE.ReportTipsNoAd()},HideTips:function(){var a=document.getElementById("gj_adctipsmall_id");a&&(a.style.display="none")},HideNoAdTips:function(){var a=document.getElementById("gj_adctipnoad_id");a&&(a.style.display="none")},insertJS:function(a){var b=document.createElement("script");b.type="text/javascript",b.src=a,b.charset="UTF-8",document.body.appendChild(b)},SetupJson:function(){IsIE()&&"undefined"==typeof JSON&&this.insertJS("http://s.pc.qq.com/navigate/adc/json2.js")},onWindowActive:function(){clearInterval(GJ_MINI_BAR_ENGINE.m_Timer),GJ_MINI_BAR_ENGINE.m_Timer=setInterval(GJ_MINI_BAR_ENGINE.GetHotNews,2e3)},onWindowBlur:function(){clearInterval(GJ_MINI_BAR_ENGINE.m_Timer)},AutoCollect:function(){if(!GJ_MINI_BAR_ENGINE.bclick){if(clearInterval(GJ_MINI_BAR_ENGINE.timer),GJ_MINI_BAR_ENGINE.bclick=!0,!GJ_MINI_BAR_ENGINE.objAdcJson.bcss||GJ_MINI_BAR_ENGINE.objAdcJson.bwhite||GJ_MINI_BAR_ENGINE.bClear)return GJ_MINI_BAR_ENGINE.ShowNoAdTips(),GJ_MINI_BAR_ENGINE.bclick=!1,void 0;GJ_MINI_BAR_ENGINE.index=0,GJ_MINI_BAR_ENGINE.nAdCount=0,GJ_MINI_BAR_ENGINE.HidePannel();var a=document.getElementById("gj_mini");a.style.cssText='right: 10px; bottom: 50px; display: block; position: fixed; z-index: 2147483641; background-image: url("http://s.pc.qq.com/navigate/adc/v2/click_up.png"); background-position-x: 0px; background-position-y: 0px;',GJ_MINI_BAR_ENGINE.timer=setInterval(GJ_MINI_BAR_ENGINE.mouseup_handler,41.6)}},RunGuide:function(a){GJ_MINI_BAR_ENGINE.nUseCount=a,1==a?setTimeout("GJ_MINI_BAR_ENGINE.AutoCollect()",2e3):setTimeout("GJ_MINI_BAR_ENGINE.StartBreathe()",100),GJ_MINI_BAR_ENGINE.reportShowAdc()},AdjustZindex:function(){$gjjq("div").each(function(){var c=$gjjq(this).css("z-index");c>2147483600&&$gjjq(this).css("z-index",c-100)})},RunAni:function(){var a=0;IsIE()?"object"==typeof window.TsCmcObj&&"undefined"!=typeof window.TsCmcObj.GetUseCount&&"unknown"!=typeof window.TsCmcObj.GetUseCount&&(a=window.TsCmcObj.GetUseCount(),GJ_MINI_BAR_ENGINE.RunGuide(a)):chrome.extension.sendRequest({cmd:"getAdHitCount",id:0},function(a){if(a){GJ_MINI_BAR_ENGINE.Log(a);var b=a.count;GJ_MINI_BAR_ENGINE.RunGuide(b)}})},RunAdFilterPostAni:function(){if(!GJ_MINI_BAR_ENGINE.bclick){clearInterval(GJ_MINI_BAR_ENGINE.timer),GJ_MINI_BAR_ENGINE.bclick=!0,GJ_MINI_BAR_ENGINE.bPostAni=!0,GJ_MINI_BAR_ENGINE.index=45;var a=document.getElementById("gj_mini");a.style.cssText='right: 10px; bottom: 50px; display: block; position: fixed; z-index: 2147483641; background-image: url("http://s.pc.qq.com/navigate/adc/v2/click_up.png"); background-position-x: 0px; background-position-y: 0px;',GJ_MINI_BAR_ENGINE.reportShowAdc(),GJ_MINI_BAR_ENGINE.timer=setInterval(GJ_MINI_BAR_ENGINE.filterpost_handler,41.6)}},init:function(){GJ_MINI_BAR_ENGINE.getAdcJson()},initSwitch:function(){if(IsIE()){var a=document.getElementById(this.conf.strDaohangJSId);a&&(GJ_MINI_BAR_ENGINE.m_strGJGuid=a.getAttribute("gjguid"),GJ_MINI_BAR_ENGINE.m_nBID=a.getAttribute("Bid")),GJ_MINI_BAR_ENGINE.OnSwitchOpen()}else chrome.extension.sendRequest({cmd:"queryAdcSwitch",id:2},function(a){a&&a.cmdret&&(GJ_MINI_BAR_ENGINE.m_strGJGuid=a.gjguid,GJ_MINI_BAR_ENGINE.m_nBID=514,GJ_MINI_BAR_ENGINE.OnSwitchOpen())}),chrome.extension.onRequest.addListener(function(a){"closeAdcPanel"==a.cmd&&GJ_MINI_BAR_ENGINE.HidePannel(),"exit"==a.cmd&&GJ_MINI_BAR_ENGINE.dhShowCustomItem(13)})},OnSwitchOpen:function(){var a=this.isIEBrowser();GJ_MINI_BAR_ENGINE.reportInsertJs(),GJ_MINI_BAR_ENGINE.IsDocument()&&a.isIE&&a.nVersion>7?(setTimeout("GJ_MINI_BAR_ENGINE.InitJq()",200),setTimeout("GJ_MINI_BAR_ENGINE.init()",400)):GJ_MINI_BAR_ENGINE.IsDocument()&&!a.isIE&&(setTimeout("GJ_MINI_BAR_ENGINE.InitJq()",200),setTimeout("GJ_MINI_BAR_ENGINE.init()",400))},Run:function(){this.SetupJson(),this.initSwitch()}};GJ_MINI_BAR_ENGINE.Run();
-HAR:
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": []
  }
}
-To be evaluated in console:
2016-03-20 03:53:20.346 c:\Users\Axioo\Favorites\ad.js:1 Uncaught TypeError: Cannot read property 'sendRequest' of undefined
2016-03-20 03:53:44.079 c:\Users\Axioo\Favorites\ad.js:1 Uncaught TypeError: Cannot read property 'sendRequest' of undefinedGJ_MINI_BAR_ENGINE.initSwitch @ c:\Users\Axioo\Favorites\ad.js:1GJ_MINI_BAR_ENGINE.Run @ c:\Users\Axioo\Favorites\ad.js:1(anonymous function) @ c:\Users\Axioo\Favorites\ad.js:1
2016-03-20 03:53:44.174 Navigated to file:///C:/Users/Axioo/Favorites/tpc.html
2016-03-20 03:54:22.296 Error saving setting with name: eventListenerBreakpoints, value length: 538. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:22.309 Ten largest settings: 
2016-03-20 03:54:22.497 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:22.498 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:22.498 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:22.498 Setting: 'breakpoints', size: 227
2016-03-20 03:54:22.498 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:22.498 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:22.498 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:22.499 Setting: 'experiments', size: 2
2016-03-20 03:54:22.499 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:22.499 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:25.011 Error saving setting with name: eventListenerBreakpoints, value length: 1000. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:25.018 Ten largest settings: 
2016-03-20 03:54:25.196 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:25.197 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:25.197 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:25.197 Setting: 'breakpoints', size: 227
2016-03-20 03:54:25.197 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:25.197 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:25.197 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:25.198 Setting: 'experiments', size: 2
2016-03-20 03:54:25.198 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:25.198 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:27.777 Error saving setting with name: eventListenerBreakpoints, value length: 1121. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:27.784 Ten largest settings: 
2016-03-20 03:54:27.963 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:27.963 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:27.963 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:27.963 Setting: 'breakpoints', size: 227
2016-03-20 03:54:27.964 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:27.964 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:27.964 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:27.964 Setting: 'experiments', size: 2
2016-03-20 03:54:27.964 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:27.966 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:30.360 Error saving setting with name: eventListenerBreakpoints, value length: 1814. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:30.362 Ten largest settings: 
2016-03-20 03:54:30.537 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:30.537 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:30.538 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:30.538 Setting: 'breakpoints', size: 227
2016-03-20 03:54:30.538 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:30.539 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:30.539 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:30.539 Setting: 'experiments', size: 2
2016-03-20 03:54:30.540 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:30.540 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:33.020 Error saving setting with name: eventListenerBreakpoints, value length: 2028. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:33.026 Ten largest settings: 
2016-03-20 03:54:33.200 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:33.201 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:33.201 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:33.202 Setting: 'breakpoints', size: 227
2016-03-20 03:54:33.202 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:33.202 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:33.202 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:33.203 Setting: 'experiments', size: 2
2016-03-20 03:54:33.203 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:33.203 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:35.477 Error saving setting with name: eventListenerBreakpoints, value length: 2237. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:35.481 Ten largest settings: 
2016-03-20 03:54:35.652 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:35.653 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:35.653 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:35.653 Setting: 'breakpoints', size: 227
2016-03-20 03:54:35.653 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:35.654 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:35.654 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:35.654 Setting: 'experiments', size: 2
2016-03-20 03:54:35.654 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:35.654 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:41.882 Error saving setting with name: eventListenerBreakpoints, value length: 2609. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:41.889 Ten largest settings: 
2016-03-20 03:54:42.064 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:42.064 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:42.065 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:42.065 Setting: 'breakpoints', size: 227
2016-03-20 03:54:42.065 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:42.066 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:42.066 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:42.066 Setting: 'experiments', size: 2
2016-03-20 03:54:42.066 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:42.067 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:43.965 Error saving setting with name: eventListenerBreakpoints, value length: 4065. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:43.967 Ten largest settings: 
2016-03-20 03:54:44.161 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:44.162 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:44.162 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:44.162 Setting: 'breakpoints', size: 227
2016-03-20 03:54:44.162 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:44.162 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:44.162 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:44.163 Setting: 'experiments', size: 2
2016-03-20 03:54:44.163 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:44.163 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:45.588 Error saving setting with name: eventListenerBreakpoints, value length: 4718. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:45.589 Ten largest settings: 
2016-03-20 03:54:45.767 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:45.767 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:45.769 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:45.769 Setting: 'breakpoints', size: 227
2016-03-20 03:54:45.769 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:45.769 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:45.770 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:45.771 Setting: 'experiments', size: 2
2016-03-20 03:54:45.771 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:45.771 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:47.283 Error saving setting with name: eventListenerBreakpoints, value length: 4783. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:47.285 Ten largest settings: 
2016-03-20 03:54:47.480 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:47.481 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:47.482 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:47.482 Setting: 'breakpoints', size: 227
2016-03-20 03:54:47.482 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:47.483 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:47.484 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:47.484 Setting: 'experiments', size: 2
2016-03-20 03:54:47.484 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:47.484 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:52.755 Error saving setting with name: eventListenerBreakpoints, value length: 5437. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:52.757 Ten largest settings: 
2016-03-20 03:54:52.935 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:52.936 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:52.937 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:52.937 Setting: 'breakpoints', size: 227
2016-03-20 03:54:52.938 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:52.941 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:52.945 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:52.946 Setting: 'experiments', size: 2
2016-03-20 03:54:52.949 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:52.954 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:54.244 Error saving setting with name: eventListenerBreakpoints, value length: 5510. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:54.246 Ten largest settings: 
2016-03-20 03:54:54.429 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:54.430 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:54.430 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:54.430 Setting: 'breakpoints', size: 227
2016-03-20 03:54:54.430 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:54.430 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:54.430 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:54.431 Setting: 'experiments', size: 2
2016-03-20 03:54:54.434 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:54.434 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:55.618 Error saving setting with name: eventListenerBreakpoints, value length: 5697. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:55.621 Ten largest settings: 
2016-03-20 03:54:55.797 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:55.797 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:55.797 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:55.798 Setting: 'breakpoints', size: 227
2016-03-20 03:54:55.798 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:55.798 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:55.798 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:55.798 Setting: 'experiments', size: 2
2016-03-20 03:54:55.798 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:55.798 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:54:56.880 Error saving setting with name: eventListenerBreakpoints, value length: 5919. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:54:56.882 Ten largest settings: 
2016-03-20 03:54:57.056 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:54:57.057 Setting: 'savedURLs', size: 3698
2016-03-20 03:54:57.057 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:54:57.057 Setting: 'breakpoints', size: 227
2016-03-20 03:54:57.057 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:54:57.057 Setting: 'watchExpressions', size: 45
2016-03-20 03:54:57.058 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:54:57.058 Setting: 'experiments', size: 2
2016-03-20 03:54:57.058 Setting: 'domBreakpoints', size: 2
2016-03-20 03:54:57.059 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:55:04.077 Error saving setting with name: eventListenerBreakpoints, value length: 6057. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:55:04.079 Ten largest settings: 
2016-03-20 03:55:04.254 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:55:04.254 Setting: 'savedURLs', size: 3698
2016-03-20 03:55:04.254 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:55:04.255 Setting: 'breakpoints', size: 227
2016-03-20 03:55:04.255 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:55:04.255 Setting: 'watchExpressions', size: 45
2016-03-20 03:55:04.255 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:55:04.255 Setting: 'experiments', size: 2
2016-03-20 03:55:04.255 Setting: 'domBreakpoints', size: 2
2016-03-20 03:55:04.256 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:55:05.588 Error saving setting with name: eventListenerBreakpoints, value length: 6115. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:55:05.589 Ten largest settings: 
2016-03-20 03:55:05.761 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:55:05.762 Setting: 'savedURLs', size: 3698
2016-03-20 03:55:05.762 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:55:05.763 Setting: 'breakpoints', size: 227
2016-03-20 03:55:05.763 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:55:05.763 Setting: 'watchExpressions', size: 45
2016-03-20 03:55:05.764 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:55:05.764 Setting: 'experiments', size: 2
2016-03-20 03:55:05.764 Setting: 'domBreakpoints', size: 2
2016-03-20 03:55:05.764 Setting: 'workspaceExcludedFolders', size: 2
2016-03-20 03:55:07.015 Error saving setting with name: eventListenerBreakpoints, value length: 6832. Error: Failed to set the 'eventListenerBreakpoints' property on 'Storage': Setting the value of 'eventListenerBreakpoints' exceeded the quota.
2016-03-20 03:55:07.016 Ten largest settings: 
2016-03-20 03:55:07.192 Setting: 'consoleHistory', size: 5235316
2016-03-20 03:55:07.192 Setting: 'savedURLs', size: 3698
2016-03-20 03:55:07.192 Setting: 'previouslyViewedFiles', size: 3146
2016-03-20 03:55:07.193 Setting: 'breakpoints', size: 227
2016-03-20 03:55:07.193 Setting: 'eventListenerBreakpoints', size: 220
2016-03-20 03:55:07.193 Setting: 'watchExpressions', size: 45
2016-03-20 03:55:07.193 Setting: 'lastSelectedSourcesSidebarPaneTab', size: 7
2016-03-20 03:55:07.193 Setting: 'experiments', size: 2
2016-03-20 03:55:07.193 Setting: 'domBreakpoints', size: 2
2016-03-20 03:55:07.193 Setting: 'workspaceExcludedFolders', size: 2
-
Animation

Request Animation Frame

Cancel Animation Frame

Animation Frame Fired
-VM66:
Global
Infinity
:
Infinity
$gjjq
:
undefined
AnalyserNode
:
AnalyserNode()
arguments
:
null
caller
:
null
length
:
0
name
:
"AnalyserNode"
prototype
:
AudioNode
__proto__
:
AudioNode()
AnimationEvent
:
AnimationEvent()
AppBannerPromptResult
:
AppBannerPromptResult()
ApplicationCache
:
ApplicationCache()
ApplicationCacheErrorEvent
:
ApplicationCacheErrorEvent()
Array
:
Array()
ArrayBuffer
:
ArrayBuffer()
Attr
:
Attr()
Audio
:
HTMLAudioElement()
AudioBuffer
:
AudioBuffer()
AudioBufferSourceNode
:
AudioBufferSourceNode()
AudioContext
:
AudioContext()
AudioDestinationNode
:
AudioDestinationNode()
AudioListener
:
AudioListener()
AudioNode
:
AudioNode()
AudioParam
:
AudioParam()
AudioProcessingEvent
:
AudioProcessingEvent()
AutocompleteErrorEvent
:
AutocompleteErrorEvent()
BarProp
:
BarProp()
BatteryManager
:
BatteryManager()
BeforeInstallPromptEvent
:
BeforeInstallPromptEvent()
BeforeUnloadEvent
:
BeforeUnloadEvent()
BiquadFilterNode
:
BiquadFilterNode()
Blob
:
Blob()
BlobEvent
:
BlobEvent()
Boolean
:
Boolean()
CDATASection
:
CDATASection()
CSS
:
CSS()
CSSFontFaceRule
:
CSSFontFaceRule()
CSSGroupingRule
:
CSSGroupingRule()
CSSImportRule
:
CSSImportRule()
CSSKeyframeRule
:
CSSKeyframeRule()
CSSKeyframesRule
:
CSSKeyframesRule()
CSSMediaRule
:
CSSMediaRule()
CSSNamespaceRule
:
CSSNamespaceRule()
CSSPageRule
:
CSSPageRule()
CSSRule
:
CSSRule()
CSSRuleList
:
CSSRuleList()
CSSStyleDeclaration
:
CSSStyleDeclaration()
CSSStyleRule
:
CSSStyleRule()
CSSStyleSheet
:
CSSStyleSheet()
CSSSupportsRule
:
CSSSupportsRule()
CSSViewportRule
:
CSSViewportRule()
Cache
:
Cache()
CacheStorage
:
CacheStorage()
CanvasGradient
:
CanvasGradient()
CanvasPattern
:
CanvasPattern()
CanvasRenderingContext2D
:
CanvasRenderingContext2D()
ChannelMergerNode
:
ChannelMergerNode()
ChannelSplitterNode
:
ChannelSplitterNode()
CharacterData
:
CharacterData()
ClientRect
:
ClientRect()
ClientRectList
:
ClientRectList()
ClipboardEvent
:
ClipboardEvent()
CloseEvent
:
CloseEvent()
Comment
:
Comment()
CompositionEvent
:
CompositionEvent()
ConvolverNode
:
ConvolverNode()
Crypto
:
Crypto()
CryptoKey
:
CryptoKey()
CustomEvent
:
CustomEvent()
DOMError
:
DOMError()
DOMException
:
DOMException()
DOMImplementation
:
DOMImplementation()
DOMParser
:
DOMParser()
DOMSettableTokenList
:
DOMSettableTokenList()
DOMStringList
:
DOMStringList()
DOMStringMap
:
DOMStringMap()
DOMTokenList
:
DOMTokenList()
DataTransfer
:
DataTransfer()
DataTransferItem
:
DataTransferItem()
DataTransferItemList
:
DataTransferItemList()
DataView
:
DataView()
Date
:
Date()
DelayNode
:
DelayNode()
DeviceMotionEvent
:
DeviceMotionEvent()
DeviceOrientationEvent
:
DeviceOrientationEvent()
Document
:
Document()
DocumentFragment
:
DocumentFragment()
DocumentType
:
DocumentType()
DragEvent
:
DragEvent()
DynamicsCompressorNode
:
DynamicsCompressorNode()
Element
:
Element()
Error
:
Error()
ErrorEvent
:
ErrorEvent()
EvalError
:
EvalError()
Event
:
Event()
EventSource
:
EventSource()
EventTarget
:
EventTarget()
File
:
File()
FileError
:
FileError()
FileList
:
FileList()
FileReader
:
FileReader()
Float32Array
:
Float32Array()
Float64Array
:
Float64Array()
FocusEvent
:
FocusEvent()
FontFace
:
FontFace()
FormData
:
FormData()
Function
:
Function()
GJ_MINI_BAR_ENGINE
:
Object
GainNode
:
GainNode()
Gamepad
:
Gamepad()
GamepadButton
:
GamepadButton()
GamepadEvent
:
GamepadEvent()
HTMLAllCollection
:
HTMLAllCollection()
HTMLAnchorElement
:
HTMLAnchorElement()
HTMLAreaElement
:
HTMLAreaElement()
HTMLAudioElement
:
HTMLAudioElement()
HTMLBRElement
:
HTMLBRElement()
HTMLBaseElement
:
HTMLBaseElement()
HTMLBodyElement
:
HTMLBodyElement()
HTMLButtonElement
:
HTMLButtonElement()
HTMLCanvasElement
:
HTMLCanvasElement()
HTMLCollection
:
HTMLCollection()
HTMLContentElement
:
HTMLContentElement()
HTMLDListElement
:
HTMLDListElement()
HTMLDataListElement
:
HTMLDataListElement()
HTMLDetailsElement
:
HTMLDetailsElement()
HTMLDialogElement
:
HTMLDialogElement()
HTMLDirectoryElement
:
HTMLDirectoryElement()
HTMLDivElement
:
HTMLDivElement()
HTMLDocument
:
HTMLDocument()
HTMLElement
:
HTMLElement()
HTMLEmbedElement
:
HTMLEmbedElement()
HTMLFieldSetElement
:
HTMLFieldSetElement()
HTMLFontElement
:
HTMLFontElement()
HTMLFormControlsCollection
:
HTMLFormControlsCollection()
HTMLFormElement
:
HTMLFormElement()
HTMLFrameElement
:
HTMLFrameElement()
HTMLFrameSetElement
:
HTMLFrameSetElement()
HTMLHRElement
:
HTMLHRElement()
HTMLHeadElement
:
HTMLHeadElement()
HTMLHeadingElement
:
HTMLHeadingElement()
HTMLHtmlElement
:
HTMLHtmlElement()
HTMLIFrameElement
:
HTMLIFrameElement()
HTMLImageElement
:
HTMLImageElement()
HTMLInputElement
:
HTMLInputElement()
HTMLKeygenElement
:
HTMLKeygenElement()
HTMLLIElement
:
HTMLLIElement()
HTMLLabelElement
:
HTMLLabelElement()
HTMLLegendElement
:
HTMLLegendElement()
HTMLLinkElement
:
HTMLLinkElement()
HTMLMapElement
:
HTMLMapElement()
HTMLMarqueeElement
:
HTMLMarqueeElement()
HTMLMediaElement
:
HTMLMediaElement()
HTMLMenuElement
:
HTMLMenuElement()
HTMLMetaElement
:
HTMLMetaElement()
HTMLMeterElement
:
HTMLMeterElement()
HTMLModElement
:
HTMLModElement()
HTMLOListElement
:
HTMLOListElement()
HTMLObjectElement
:
HTMLObjectElement()
HTMLOptGroupElement
:
HTMLOptGroupElement()
HTMLOptionElement
:
HTMLOptionElement()
HTMLOptionsCollection
:
HTMLOptionsCollection()
HTMLOutputElement
:
HTMLOutputElement()
HTMLParagraphElement
:
HTMLParagraphElement()
HTMLParamElement
:
HTMLParamElement()
HTMLPictureElement
:
HTMLPictureElement()
HTMLPreElement
:
HTMLPreElement()
HTMLProgressElement
:
HTMLProgressElement()
HTMLQuoteElement
:
HTMLQuoteElement()
HTMLScriptElement
:
HTMLScriptElement()
HTMLSelectElement
:
HTMLSelectElement()
HTMLShadowElement
:
HTMLShadowElement()
HTMLSourceElement
:
HTMLSourceElement()
HTMLSpanElement
:
HTMLSpanElement()
HTMLStyleElement
:
HTMLStyleElement()
HTMLTableCaptionElement
:
HTMLTableCaptionElement()
HTMLTableCellElement
:
HTMLTableCellElement()
HTMLTableColElement
:
HTMLTableColElement()
HTMLTableElement
:
HTMLTableElement()
HTMLTableRowElement
:
HTMLTableRowElement()
HTMLTableSectionElement
:
HTMLTableSectionElement()
HTMLTemplateElement
:
HTMLTemplateElement()
HTMLTextAreaElement
:
HTMLTextAreaElement()
HTMLTitleElement
:
HTMLTitleElement()
HTMLTrackElement
:
HTMLTrackElement()
HTMLUListElement
:
HTMLUListElement()
HTMLUnknownElement
:
HTMLUnknownElement()
HTMLVideoElement
:
HTMLVideoElement()
HashChangeEvent
:
HashChangeEvent()
Headers
:
Headers()
History
:
History()
IDBCursor
:
IDBCursor()
IDBCursorWithValue
:
IDBCursorWithValue()
IDBDatabase
:
IDBDatabase()
IDBFactory
:
IDBFactory()
IDBIndex
:
IDBIndex()
IDBKeyRange
:
IDBKeyRange()
IDBObjectStore
:
IDBObjectStore()
IDBOpenDBRequest
:
IDBOpenDBRequest()
IDBRequest
:
IDBRequest()
IDBTransaction
:
IDBTransaction()
IDBVersionChangeEvent
:
IDBVersionChangeEvent()
IIRFilterNode
:
IIRFilterNode()
IdleDeadline
:
IdleDeadline()
Image
:
HTMLImageElement()
ImageBitmap
:
ImageBitmap()
ImageData
:
ImageData()
InputDeviceCapabilities
:
InputDeviceCapabilities()
Int8Array
:
Int8Array()
Int16Array
:
Int16Array()
Int32Array
:
Int32Array()
Intl
:
Object
IsIE
:
IsIE()
JSON
:
JSON
KeyboardEvent
:
KeyboardEvent()
Location
:
Location()
MIDIAccess
:
MIDIAccess()
MIDIConnectionEvent
:
MIDIConnectionEvent()
MIDIInput
:
MIDIInput()
MIDIInputMap
:
MIDIInputMap()
MIDIMessageEvent
:
MIDIMessageEvent()
MIDIOutput
:
MIDIOutput()
MIDIOutputMap
:
MIDIOutputMap()
MIDIPort
:
MIDIPort()
Map
:
Map()
Math
:
Math
MediaDevices
:
MediaDevices()
MediaElementAudioSourceNode
:
MediaElementAudioSourceNode()
MediaEncryptedEvent
:
MediaEncryptedEvent()
MediaError
:
MediaError()
MediaKeyMessageEvent
:
MediaKeyMessageEvent()
MediaKeySession
:
MediaKeySession()
MediaKeyStatusMap
:
MediaKeyStatusMap()
MediaKeySystemAccess
:
MediaKeySystemAccess()
MediaKeys
:
MediaKeys()
MediaList
:
MediaList()
MediaQueryList
:
MediaQueryList()
MediaQueryListEvent
:
MediaQueryListEvent()
MediaRecorder
:
MediaRecorder()
MediaSource
:
MediaSource()
MediaStreamAudioDestinationNode
:
MediaStreamAudioDestinationNode()
MediaStreamAudioSourceNode
:
MediaStreamAudioSourceNode()
MediaStreamEvent
:
MediaStreamEvent()
MediaStreamTrack
:
MediaStreamTrack()
MessageChannel
:
MessageChannel()
MessageEvent
:
MessageEvent()
MessagePort
:
MessagePort()
MimeType
:
MimeType()
MimeTypeArray
:
MimeTypeArray()
MouseEvent
:
MouseEvent()
MutationEvent
:
MutationEvent()
MutationObserver
:
MutationObserver()
MutationRecord
:
MutationRecord()
NaN
:
NaN
NamedNodeMap
:
NamedNodeMap()
Navigator
:
Navigator()
Node
:
Node()
NodeFilter
:
NodeFilter()
NodeIterator
:
NodeIterator()
NodeList
:
NodeList()
Notification
:
Notification()
Number
:
Number()
Object
:
Object()
OfflineAudioCompletionEvent
:
OfflineAudioCompletionEvent()
OfflineAudioContext
:
OfflineAudioContext()
Option
:
HTMLOptionElement()
OscillatorNode
:
OscillatorNode()
PERSISTENT
:
1
PageTransitionEvent
:
PageTransitionEvent()
Path2D
:
Path2D()
Performance
:
Performance()
PerformanceEntry
:
PerformanceEntry()
PerformanceMark
:
PerformanceMark()
PerformanceMeasure
:
PerformanceMeasure()
PerformanceNavigation
:
PerformanceNavigation()
PerformanceResourceTiming
:
PerformanceResourceTiming()
PerformanceTiming
:
PerformanceTiming()
PeriodicWave
:
PeriodicWave()
PermissionStatus
:
PermissionStatus()
Permissions
:
Permissions()
Plugin
:
Plugin()
PluginArray
:
PluginArray()
PopStateEvent
:
PopStateEvent()
Presentation
:
Presentation()
PresentationAvailability
:
PresentationAvailability()
PresentationConnection
:
PresentationConnection()
PresentationConnectionAvailableEvent
:
PresentationConnectionAvailableEvent()
PresentationRequest
:
PresentationRequest()
ProcessingInstruction
:
ProcessingInstruction()
ProgressEvent
:
ProgressEvent()
Promise
:
Promise()
PromiseRejectionEvent
:
PromiseRejectionEvent()
Proxy
:
Proxy()
PushManager
:
PushManager()
PushSubscription
:
PushSubscription()
RTCCertificate
:
RTCCertificate()
RTCIceCandidate
:
RTCIceCandidate()
RTCSessionDescription
:
RTCSessionDescription()
RadioNodeList
:
RadioNodeList()
Range
:
Range()
RangeError
:
RangeError()
ReadableByteStream
:
ReadableByteStream()
ReadableStream
:
ReadableStream()
ReferenceError
:
ReferenceError()
Reflect
:
Object
RegExp
:
RegExp()
Request
:
Request()
Response
:
Response()
SVGAElement
:
SVGAElement()
SVGAngle
:
SVGAngle()
SVGAnimateElement
:
SVGAnimateElement()
SVGAnimateMotionElement
:
SVGAnimateMotionElement()
SVGAnimateTransformElement
:
SVGAnimateTransformElement()
SVGAnimatedAngle
:
SVGAnimatedAngle()
SVGAnimatedBoolean
:
SVGAnimatedBoolean()
SVGAnimatedEnumeration
:
SVGAnimatedEnumeration()
SVGAnimatedInteger
:
SVGAnimatedInteger()
SVGAnimatedLength
:
SVGAnimatedLength()
SVGAnimatedLengthList
:
SVGAnimatedLengthList()
SVGAnimatedNumber
:
SVGAnimatedNumber()
SVGAnimatedNumberList
:
SVGAnimatedNumberList()
SVGAnimatedPreserveAspectRatio
:
SVGAnimatedPreserveAspectRatio()
SVGAnimatedRect
:
SVGAnimatedRect()
SVGAnimatedString
:
SVGAnimatedString()
SVGAnimatedTransformList
:
SVGAnimatedTransformList()
SVGAnimationElement
:
SVGAnimationElement()
SVGCircleElement
:
SVGCircleElement()
SVGClipPathElement
:
SVGClipPathElement()
SVGComponentTransferFunctionElement
:
SVGComponentTransferFunctionElement()
SVGCursorElement
:
SVGCursorElement()
SVGDefsElement
:
SVGDefsElement()
SVGDescElement
:
SVGDescElement()
SVGDiscardElement
:
SVGDiscardElement()
SVGElement
:
SVGElement()
SVGEllipseElement
:
SVGEllipseElement()
SVGFEBlendElement
:
SVGFEBlendElement()
SVGFEColorMatrixElement
:
SVGFEColorMatrixElement()
SVGFEComponentTransferElement
:
SVGFEComponentTransferElement()
SVGFECompositeElement
:
SVGFECompositeElement()
SVGFEConvolveMatrixElement
:
SVGFEConvolveMatrixElement()
SVGFEDiffuseLightingElement
:
SVGFEDiffuseLightingElement()
SVGFEDisplacementMapElement
:
SVGFEDisplacementMapElement()
SVGFEDistantLightElement
:
SVGFEDistantLightElement()
SVGFEDropShadowElement
:
SVGFEDropShadowElement()
SVGFEFloodElement
:
SVGFEFloodElement()
SVGFEFuncAElement
:
SVGFEFuncAElement()
SVGFEFuncBElement
:
SVGFEFuncBElement()
SVGFEFuncGElement
:
SVGFEFuncGElement()
SVGFEFuncRElement
:
SVGFEFuncRElement()
SVGFEGaussianBlurElement
:
SVGFEGaussianBlurElement()
SVGFEImageElement
:
SVGFEImageElement()
SVGFEMergeElement
:
SVGFEMergeElement()
SVGFEMergeNodeElement
:
SVGFEMergeNodeElement()
SVGFEMorphologyElement
:
SVGFEMorphologyElement()
SVGFEOffsetElement
:
SVGFEOffsetElement()
SVGFEPointLightElement
:
SVGFEPointLightElement()
SVGFESpecularLightingElement
:
SVGFESpecularLightingElement()
SVGFESpotLightElement
:
SVGFESpotLightElement()
SVGFETileElement
:
SVGFETileElement()
SVGFETurbulenceElement
:
SVGFETurbulenceElement()
SVGFilterElement
:
SVGFilterElement()
SVGForeignObjectElement
:
SVGForeignObjectElement()
SVGGElement
:
SVGGElement()
SVGGeometryElement
:
SVGGeometryElement()
SVGGradientElement
:
SVGGradientElement()
SVGGraphicsElement
:
SVGGraphicsElement()
SVGImageElement
:
SVGImageElement()
SVGLength
:
SVGLength()
SVGLengthList
:
SVGLengthList()
SVGLineElement
:
SVGLineElement()
SVGLinearGradientElement
:
SVGLinearGradientElement()
SVGMPathElement
:
SVGMPathElement()
SVGMarkerElement
:
SVGMarkerElement()
SVGMaskElement
:
SVGMaskElement()
SVGMatrix
:
SVGMatrix()
SVGMetadataElement
:
SVGMetadataElement()
SVGNumber
:
SVGNumber()
SVGNumberList
:
SVGNumberList()
SVGPathElement
:
SVGPathElement()
SVGPatternElement
:
SVGPatternElement()
SVGPoint
:
SVGPoint()
SVGPointList
:
SVGPointList()
SVGPolygonElement
:
SVGPolygonElement()
SVGPolylineElement
:
SVGPolylineElement()
SVGPreserveAspectRatio
:
SVGPreserveAspectRatio()
SVGRadialGradientElement
:
SVGRadialGradientElement()
SVGRect
:
SVGRect()
SVGRectElement
:
SVGRectElement()
SVGSVGElement
:
SVGSVGElement()
SVGScriptElement
:
SVGScriptElement()
SVGSetElement
:
SVGSetElement()
SVGStopElement
:
SVGStopElement()
SVGStringList
:
SVGStringList()
SVGStyleElement
:
SVGStyleElement()
SVGSwitchElement
:
SVGSwitchElement()
SVGSymbolElement
:
SVGSymbolElement()
SVGTSpanElement
:
SVGTSpanElement()
SVGTextContentElement
:
SVGTextContentElement()
SVGTextElement
:
SVGTextElement()
SVGTextPathElement
:
SVGTextPathElement()
SVGTextPositioningElement
:
SVGTextPositioningElement()
SVGTitleElement
:
SVGTitleElement()
SVGTransform
:
SVGTransform()
SVGTransformList
:
SVGTransformList()
SVGUnitTypes
:
SVGUnitTypes()
SVGUseElement
:
SVGUseElement()
SVGViewElement
:
SVGViewElement()
SVGViewSpec
:
SVGViewSpec()
SVGZoomEvent
:
SVGZoomEvent()
Screen
:
Screen()
ScreenOrientation
:
ScreenOrientation()
ScriptProcessorNode
:
ScriptProcessorNode()
SecurityPolicyViolationEvent
:
SecurityPolicyViolationEvent()
Selection
:
Selection()
ServiceWorker
:
ServiceWorker()
ServiceWorkerContainer
:
ServiceWorkerContainer()
ServiceWorkerMessageEvent
:
ServiceWorkerMessageEvent()
ServiceWorkerRegistration
:
ServiceWorkerRegistration()
Set
:
Set()
ShadowRoot
:
ShadowRoot()
SharedWorker
:
SharedWorker()
SpeechSynthesisEvent
:
SpeechSynthesisEvent()
SpeechSynthesisUtterance
:
SpeechSynthesisUtterance()
Storage
:
Storage()
StorageEvent
:
StorageEvent()
String
:
String()
StyleSheet
:
StyleSheet()
StyleSheetList
:
StyleSheetList()
SubtleCrypto
:
SubtleCrypto()
Symbol
:
Symbol()
SyncManager
:
SyncManager()
SyntaxError
:
SyntaxError()
TEMPORARY
:
0
Text
:
Text()
TextDecoder
:
TextDecoder()
TextEncoder
:
TextEncoder()
TextEvent
:
TextEvent()
TextMetrics
:
TextMetrics()
TextTrack
:
TextTrack()
TextTrackCue
:
TextTrackCue()
TextTrackCueList
:
TextTrackCueList()
TextTrackList
:
TextTrackList()
TimeRanges
:
TimeRanges()
Touch
:
Touch()
TouchEvent
:
TouchEvent()
TouchList
:
TouchList()
TrackEvent
:
TrackEvent()
TransitionEvent
:
TransitionEvent()
TreeWalker
:
TreeWalker()
TypeError
:
TypeError()
UIEvent
:
UIEvent()
URIError
:
URIError()
URL
:
URL()
URLSearchParams
:
URLSearchParams()
Uint8Array
:
Uint8Array()
Uint8ClampedArray
:
Uint8ClampedArray()
Uint16Array
:
Uint16Array()
Uint32Array
:
Uint32Array()
VTTCue
:
VTTCue()
ValidityState
:
ValidityState()
WaveShaperNode
:
WaveShaperNode()
WeakMap
:
WeakMap()
WeakSet
:
WeakSet()
WebGLActiveInfo
:
WebGLActiveInfo()
WebGLBuffer
:
WebGLBuffer()
WebGLContextEvent
:
WebGLContextEvent()
WebGLFramebuffer
:
WebGLFramebuffer()
WebGLProgram
:
WebGLProgram()
WebGLRenderbuffer
:
WebGLRenderbuffer()
WebGLRenderingContext
:
WebGLRenderingContext()
WebGLShader
:
WebGLShader()
WebGLShaderPrecisionFormat
:
WebGLShaderPrecisionFormat()
WebGLTexture
:
WebGLTexture()
WebGLUniformLocation
:
WebGLUniformLocation()
WebKitAnimationEvent
:
AnimationEvent()
WebKitCSSMatrix
:
WebKitCSSMatrix()
WebKitMutationObserver
:
MutationObserver()
WebKitTransitionEvent
:
TransitionEvent()
WebSocket
:
WebSocket()
WheelEvent
:
WheelEvent()
Window
:
Window()
Worker
:
Worker()
XMLDocument
:
XMLDocument()
XMLHttpRequest
:
XMLHttpRequest()
XMLHttpRequestEventTarget
:
XMLHttpRequestEventTarget()
XMLHttpRequestProgressEvent
:
XMLHttpRequestProgressEvent()
XMLHttpRequestUpload
:
XMLHttpRequestUpload()
XMLSerializer
:
XMLSerializer()
XPathEvaluator
:
XPathEvaluator()
XPathExpression
:
XPathExpression()
XPathResult
:
XPathResult()
XSLTProcessor
:
XSLTProcessor()
__defineGetter__
:
__defineGetter__()
__defineSetter__
:
__defineSetter__()
__lookupGetter__
:
__lookupGetter__()
__lookupSetter__
:
__lookupSetter__()
addEventListener
:
addEventListener()
alert
:
alert()
applicationCache
:
ApplicationCache
atob
:
atob()
blur
:
()
btoa
:
btoa()
caches
:
CacheStorage
cancelAnimationFrame
:
cancelAnimationFrame()
cancelIdleCallback
:
cancelIdleCallback()
captureEvents
:
captureEvents()
chrome
:
Object
clearInterval
:
clearInterval()
clearTimeout
:
clearTimeout()
clientInformation
:
Navigator
close
:
()
closed
:
false
confirm
:
confirm()
console
:
Console
constructor
:
Window()
crypto
:
Crypto
decodeURI
:
decodeURI()
decodeURIComponent
:
decodeURIComponent()
defaultStatus
:
""
defaultstatus
:
""
devicePixelRatio
:
1
dispatchEvent
:
dispatchEvent()
document
:
document
donothing_error
:
donothing_error()
encodeURI
:
encodeURI()
encodeURIComponent
:
encodeURIComponent()
escape
:
escape()
eval
:
eval()
event
:
undefined
external
:
Object
fetch
:
fetch()
find
:
find()
focus
:
()
frameElement
:
null
frames
:
Window
getComputedStyle
:
getComputedStyle()
getMatchedCSSRules
:
getMatchedCSSRules()
getSelection
:
getSelection()
hasOwnProperty
:
hasOwnProperty()
history
:
History
indexedDB
:
IDBFactory
innerHeight
:
643
innerWidth
:
1366
isFinite
:
isFinite()
isNaN
:
isNaN()
isPrototypeOf
:
isPrototypeOf()
isSecureContext
:
true
length
:
0
localStorage
:
Storage
location
:
Location
locationbar
:
BarProp
matchMedia
:
matchMedia()
menubar
:
BarProp
moveBy
:
moveBy()
moveTo
:
moveTo()
name
:
""
navigator
:
Navigator
offscreenBuffering
:
true
onabort
:
null
onanimationend
:
null
onanimationiteration
:
null
onanimationstart
:
null
onautocomplete
:
null
onautocompleteerror
:
null
onbeforeunload
:
null
onblur
:
null
oncancel
:
null
oncanplay
:
null
oncanplaythrough
:
null
onchange
:
null
onclick
:
null
onclose
:
null
oncontextmenu
:
null
oncuechange
:
null
ondblclick
:
null
ondevicemotion
:
null
ondeviceorientation
:
null
ondrag
:
null
ondragend
:
null
ondragenter
:
null
ondragleave
:
null
ondragover
:
null
ondragstart
:
null
ondrop
:
null
ondurationchange
:
null
onemptied
:
null
onended
:
null
onerror
:
null
onfocus
:
null
onhashchange
:
null
oninput
:
null
oninvalid
:
null
onkeydown
:
null
onkeypress
:
null
onkeyup
:
null
onlanguagechange
:
null
onload
:
null
onloadeddata
:
null
onloadedmetadata
:
null
onloadstart
:
null
onmessage
:
null
onmousedown
:
null
onmouseenter
:
null
onmouseleave
:
null
onmousemove
:
null
onmouseout
:
null
onmouseover
:
null
onmouseup
:
null
onmousewheel
:
null
onoffline
:
null
ononline
:
null
onpagehide
:
null
onpageshow
:
null
onpause
:
null
onplay
:
null
onplaying
:
null
onpopstate
:
null
onprogress
:
null
onratechange
:
null
onrejectionhandled
:
null
onreset
:
null
onresize
:
null
onscroll
:
null
onsearch
:
null
onseeked
:
null
onseeking
:
null
onselect
:
null
onshow
:
null
onstalled
:
null
onstorage
:
null
onsubmit
:
null
onsuspend
:
null
ontimeupdate
:
null
ontoggle
:
null
ontransitionend
:
null
onunhandledrejection
:
null
onunload
:
null
onvolumechange
:
null
onwaiting
:
null
onwebkitanimationend
:
null
onwebkitanimationiteration
:
null
onwebkitanimationstart
:
null
onwebkittransitionend
:
null
onwheel
:
null
open
:
open()
openDatabase
:
openDatabase()
opener
:
null
outerHeight
:
728
outerWidth
:
1366
pageXOffset
:
0
pageYOffset
:
0
parent
:
Window
parseFloat
:
parseFloat()
parseInt
:
parseInt()
performance
:
Performance
personalbar
:
BarProp
postMessage
:
()
print
:
print()
prompt
:
prompt()
propertyIsEnumerable
:
propertyIsEnumerable()
releaseEvents
:
releaseEvents()
removeEventListener
:
removeEventListener()
requestAnimationFrame
:
requestAnimationFrame()
requestIdleCallback
:
requestIdleCallback()
resizeBy
:
resizeBy()
resizeTo
:
resizeTo()
screen
:
Screen
screenLeft
:
0
screenTop
:
0
screenX
:
0
screenY
:
0
scroll
:
scroll()
scrollBy
:
scrollBy()
scrollTo
:
scrollTo()
scrollX
:
0
scrollY
:
0
scrollbars
:
BarProp
self
:
Window
sessionStorage
:
Storage
setInterval
:
setInterval()
setTimeout
:
setTimeout()
speechSynthesis
:
SpeechSynthesis
status
:
""
statusbar
:
BarProp
stop
:
stop()
styleMedia
:
StyleMedia
toLocaleString
:
toLocaleString()
toString
:
()
toolbar
:
BarProp
top
:
Window
undefined
:
undefined
unescape
:
unescape()
valueOf
:
valueOf()
webkitAudioContext
:
AudioContext()
webkitCancelAnimationFrame
:
webkitCancelAnimationFrame()
webkitCancelRequestAnimationFrame
:
webkitCancelRequestAnimationFrame()
webkitIDBCursor
:
IDBCursor()
webkitIDBDatabase
:
IDBDatabase()
webkitIDBFactory
:
IDBFactory()
webkitIDBIndex
:
IDBIndex()
webkitIDBKeyRange
:
IDBKeyRange()
webkitIDBObjectStore
:
IDBObjectStore()
webkitIDBRequest
:
IDBRequest()
webkitIDBTransaction
:
IDBTransaction()
webkitIndexedDB
:
IDBFactory
webkitMediaStream
:
MediaStream()
webkitOfflineAudioContext
:
OfflineAudioContext()
webkitRTCPeerConnection
:
RTCPeerConnection()
webkitRequestAnimationFrame
:
webkitRequestAnimationFrame()
webkitRequestFileSystem
:
webkitRequestFileSystem()
webkitResolveLocalFileSystemURL
:
webkitResolveLocalFileSystemURL()
webkitSpeechGrammar
:
SpeechGrammar()
webkitSpeechGrammarList
:
SpeechGrammarList()
webkitSpeechRecognition
:
SpeechRecognition()
webkitSpeechRecognitionError
:
SpeechRecognitionError()
webkitSpeechRecognitionEvent
:
SpeechRecognitionEvent()
webkitStorageInfo
:
DeprecatedStorageInfo
webkitURL
:
URL()
window
:
Window

Console





Preserve log
﻿
2016-03-20 04:02:40.185 

